### ISSUE TITLE
Missing shadows

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#1278] opened 2017-02-02 19:42 UTC
Some layers with shadow are not rendering in Avocode.

For example:
![image](https://cloud.githubusercontent.com/assets/1464003/22565215/636e1380-e955-11e6-8430-214fe1ede178.png)

In Sketch, each menu item's background layer has the following style:
![image](https://cloud.githubusercontent.com/assets/1464003/22565254/7f743550-e955-11e6-899a-2017227d5b7b.png)

However, they're all missing in Avocode:
![image](https://cloud.githubusercontent.com/assets/1464003/22565277/930850ba-e955-11e6-92f4-b782b7be97a4.png)

However, this is not consistent. The same style on other layers show up fine in Avocode.

**Comment by connor-bean** [comment] 2017-02-03 08:46
Hey @n0rule5 -

Could you send us the problematic design to team@avocode.com? Please also include your OSX version, Avocode version, as well as Sketch plugin version.

Thank you,
Connor, Avocode Support

**Comment by connor-bean** [comment] 2017-02-10 12:20
Hey @n0rule5 -

Could you send us the problematic design to team@avocode.com? Please also include your OSX version, Avocode version, as well as Sketch plugin version.

Thank you,
Connor, Avocode Support

**Comment by n0rule5** [comment] 2017-02-10 16:35
Did the file I sent you not show the problem?



-ph

**Comment by bolekkerous** [comment] 2017-02-20 15:53
Sorry for the confusion, @n0rule5 - we've got the file and the issue is in our internal bug tracking system. It will be fixed once we use our new rendering engine for the stage rendering.

**Comment by bolekkerous** [comment] 2018-02-07 15:48
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team

**Closed by bolekkerous** 2018-02-07 15:48 UTC
Labels: onGitlab
