### ISSUE TITLE
Problem to send xd file

### ISSUE THREAD

**Issue by mayllats** [avocode/avocode#1935] opened 2018-03-16 17:08 UTC
---
* **Version**: 2.21.0
* **Sketch plugin version**: 48.2.8
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 288454
---
```
Error: Failed to open Adobe XD CC design in 20000ms.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4242332
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:360:21)
```

**Comment by jakubzitny** [comment] 2018-03-19 09:56
Hi @mayllats, thanks for the report. This might be happening due to special characters in the name or path of your XD file that you're trying to upload to Avocode. We have a fix prepared for next release so I will close this issue with respect to #1897 where we are tracking it. Similar problem can be caused by having the file in Dropbox/gDrive or similar service. If this is not the case, please let us know.

**Closed as completed by jakubzitny** 2018-03-19 09:56 UTC
Labels: bug, duplicate, xd
