### ISSUE TITLE
Sketch plugin doesn't work (all elements and layers white)

### ISSUE THREAD

**Issue by elenat82** [avocode/avocode#1005] opened 2016-08-01 07:42 UTC
Hi everyone,

the designer uploaded his Sketch mockup to Avocode and get no error, I am on the developer side so I opened the project in Avocode app but I see only white artboards. Elements and layers are present though.

He updated his plugin last friday.

**Comment by connor-bean** [comment] 2016-08-01 07:47
Hey @elenat82 -

This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by elenat82** [comment] 2016-08-02 08:36
Thank you Connor!

You were right, now it works.

Elena

**Comment by connor-bean** [comment] 2016-08-02 08:37
Excellent!

I will close this out. Please let us know of any questions in the future.

Thanks,
Connor, Avocode Support

**Closed by connor-bean** 2016-08-02 08:37 UTC
Labels: waitingForUser
