### ISSUE TITLE
After installation, the application runs in a light version

### ISSUE THREAD

**Issue by idp001** [avocode/avocode#2029] opened 2018-05-18 21:24 UTC
After installation, the application runs in a light version. Disabling the function Monroe solves the problem partially. How to fix it? 
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: win64
* **Avocode UID**: 320035

**Comment by bolekkerous** [comment] 2018-05-21 08:42
Hey @idp001 -
it's most likely related to some issue with Electron hardware support for specific GPU, which results in WebGL not working properly.

Could you please try out this Avocode experimental build instead? It might solve the problem:

https://upx.cz/5Xj

After you download it, please try to run the build with Monroe rendering ENABLED to see whether it works or not.

Thanks!

**Comment by jakubzitny** [comment] 2018-05-22 13:34
Hi @idp001, have you got time to try our experimental build to see if this issue is still happening, please?

**Comment by idp001** [comment] 2018-05-22 13:51
Hello @jakubzitny, in browser works fine, experimental build works a little better, but there are still problems. On the other computer experimental build is working fine. I told Bolek about it in the avocode chat.

**Comment by jakubzitny** [comment] 2018-05-22 14:00
Allright, thanks, got it now. I believe the problem is related to similar rendering issues we track in #1875. I'll close this issue for now, and we'll update you when this is improved. For now, accept our apologies and please use the web version 🙂

**Closed as completed by jakubzitny** 2018-05-22 14:00 UTC
Labels: waitingForUser, rendering
