### ISSUE TITLE
what is this?!

### ISSUE THREAD

**Issue by vindi-r** [avocode/avocode#1783] opened 2017-12-13 08:28 UTC
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 220452
---
```
TypeError: Cannot read property 'toJS' of undefined
    at a (file:///C:/Users/vindi/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:1385883)
    at Object.s [as convertColor] (file:///C:/Users/vindi/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:1386024)
    at file:///C:/Users/vindi/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:115378
    at C:\Users\vindi\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:3018:46
    at List.__iterate (C:\Users\vindi\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (C:\Users\vindi\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:3017:23)
    at seqIterate (C:\Users\vindi\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:606:16)
    at I
```

**Comment by jakubzitny** [comment] 2017-12-13 08:59
Hi @vindi-r, thanks for submitting this. This is a bug we have when creating code output for certain type of layers. We have already fixed it in our internal builds and we will release a fix in next Avocode version.

We'll update you in #1760 as this issue is a duplicate of that one.

**Closed as completed by jakubzitny** 2017-12-13 08:59 UTC
Labels: bug, duplicate
