### ISSUE TITLE
Conic Gradient crash

### ISSUE THREAD

**Issue by ikethepike** [avocode/avocode#1771] opened 2017-12-06 11:04 UTC
Error when trying to render conic gradient in CSS, instant crash

https://caniuse.com/#search=conic

---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 90293
---
```
TypeError: Cannot read property 'toJS' of undefined
    at a (file:///C:/Users/ike/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:1385883)
    at Object.s [as convertColor] (file:///C:/Users/ike/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:1386024)
    at file:///C:/Users/ike/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:115378
    at C:\Users\ike\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:3018:46
    at List.__iterate (C:\Users\ike\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (C:\Users\ike\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:3017:23)
    at seqIterate (C:\Users\ike\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\immutable\dist\immutable.js:606:16)
    at IndexedIterable
```

**Comment by vojtatranta** [comment] 2017-12-07 00:16
Hi,
this bug is known, we will fix it in the next release.

Thanks!

**Comment by jakubzitny** [comment] 2017-12-13 08:59
This is actually a duplicate of #1760, I'll close this one.

**Closed as completed by jakubzitny** 2017-12-13 08:59 UTC
Labels: bug, duplicate, onGitlab, willBeFixed
