### ISSUE TITLE
Trying to upload a 72MB PSD - Processing failed

### ISSUE THREAD

**Issue by larisagroza** [avocode/avocode#1374] opened 2017-04-10 09:53 UTC
* **Version**: 
2.13.2

* **Web/Desktop**:
web + desktop mac

* **Platform**: 
chrome

Hello,
I am trying to upload a PSD 72MB and it gets stuck at 96%.
Thanks,
Larisa

**Comment by bolekkerous** [comment] 2017-04-10 10:52
Hey, Larisa -
this looks like a problem caused by using huge bitmap images in the design (usually stock images with huge resolutions). This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. 

It also looks like you're using Photoshop Artboards in the design. That's a feature we don't support at the moment, so we would advise to not use the artboards with Avocode, because it can cause some issues.

We would suggest your designer to either ungroup the artboards or make a few smaller files containing just one of the artboards (ungrouped though).

If you want us to support Photoshop artboards, please upvote the feature on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

**Comment by larisagroza** [comment] 2017-04-10 10:56
Hello,

I do not have access to photoshop!

Larisa

**Comment by bolekkerous** [comment] 2017-04-10 10:58
Ok, could you either send us an e-mail to team@avocode.com or just write your e-mail address here, so we can send you the link to assign the uploaded design to your project?

**Comment by bolekkerous** [comment] 2017-04-11 10:06
Caused by huge bitmap stock image in the design. Should be fixed once we implement new processing architecture.

**Comment by jakubzitny** [comment] 2018-02-07 11:40
This should already be fixed in latest versions of Avocode.

**Closed by jakubzitny** 2018-02-07 11:40 UTC
Labels: inprogress, onGitlab, willBeFixed
