### ISSUE TITLE
otevření stejneho projektu po druhé

### ISSUE THREAD

**Issue by koty33** [avocode/avocode#894] opened 2016-06-01 15:38 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0-beta.6
Source UID: 70634
```
TypeError: Cannot read property 'scale' of null
    at React.createClass._getStageState (file:///Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:15649)
    at React.createClass._getState (file:///Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:15143)
    at React.createClass.componentWillReceiveProps (file:///Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:30:13900)
    at ReactCompositeComponentMixin.updateComponent (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:458:14)
    at ReactCompositeComponentMixin.receiveComponent (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.ReactReconciler.receiveComponent (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at ReactCompositeComponentMixin._updateRenderedComponent (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at ReactCompositeComponentMixin._performComponentUpdate (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at ReactCompositeComponentMixin.updateComponent (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/Koty/Downloads/Avocode-darwin-x64/Avocode.ap
```

**Comment by vojtatranta** [comment] 2016-06-02 09:14
You cannot give us that PSD I suppose, right?

**Comment by vojtatranta** [comment] 2016-06-02 09:30
This is a duplicate of https://github.com/avocode/avocode/issues/893 
Will close this one and continue there.

**Closed by vojtatranta** 2016-06-02 09:30 UTC
Labels: avocodeNext
