### ISSUE TITLE
don't start

### ISSUE THREAD

**Issue by Francois-Francois** [avocode/avocode#2259] opened 2018-11-12 18:55 UTC
crash at boot, on Archlinux

---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: linux
---
```
{ preventDefault: [Function: preventDefault],
  sender:
   WebContents {
     webContents: [Circular],
     history:
      [ 'file:///opt/avocode/resources/app.asar/desktop-index.html?appDataDirname=%2Fhome%2Ffrancois%2F.avocode' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Array],
        'did-navigate': [Function],
        destroyed: [Function],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        crashed: [
```
---
```
["app-finished-launching","app-crash-reporter-starting","app-crash-reporter-started","appready","appopenlisteners-replacing","appopenlisteners-replaced","appsplash-creating","appsplash-created","createwindow-starting","createwindow-browser-window-preparing","createwindow-browser-window-prepared","createwindow-crash-listener","createwindow-state-manage","createwindow-load-url","createwindow-dom-ready-listener","createwindow-finishing","ipc--calling-methog--setTitle","mainwindow-dom-ready","mainwindow-destroying-splash","mainwindow-showing","mainwindow-shown","mainwindow-maximizing","mainwindow-opening-init-urls","mainwindow-opening-init-files","mainwindow-initializing-menu-bar","ipc--setting-menu-bar-visibility"]
```

**Comment by crashmajstr** [comment] 2018-11-13 08:24
Hello @rikless  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by Francois-Francois** [comment] 2018-11-14 14:48
I can't open any project. I start the application, there is the loader, then it crashes

**Comment by crashmajstr** [comment] 2018-11-14 15:06
Ok thank you, we noticed that some of our user ~4 reported this problem as well, but we can't reproduce it on our end. So we'll try to investigate it more on our end. One thing you can try is to delete your ~.avocode folder, maybe it'll help. Otherwise, please use the web app it should work ok. I am very sorry for the inconvenience.

Closing with respect to #2109 #2146

**Closed as completed by crashmajstr** 2018-11-14 15:06 UTC
Labels: waitingForUser
