### ISSUE TITLE
Issue with system zoom in Windows other than 100%

### ISSUE THREAD

**Issue by Zidar** [avocode/avocode#1346] opened 2017-03-26 08:48 UTC
* **Version**: 2.13.1

* **Web/Desktop**: Desktop

* **Platform**: Windows 10

I use Avocode on laptop with 1600x900 screen resolution. **System zoom is set to 125%**.
**Workspace in Avocode looks blurry**. Sidebars in Avocode, icons, menu look ok.
![design-125](https://cloud.githubusercontent.com/assets/25146905/24329743/a326f1e4-120f-11e7-9789-24dd4f99a2ea.png)

If I set system zoom to 100%, everything looks ok.
![design-100](https://cloud.githubusercontent.com/assets/25146905/24329746/b0fb9eaa-120f-11e7-886a-c0b9f2a3d62f.png)

Image on screenshots is a .psd file with normal text. It is not a raster image.

In previous versions of Avocode I could set option "Disable zooming on hi-dpi screen" in properties of a shortcut to application. And it helped. **Now this option affects nothing.**
![options](https://cloud.githubusercontent.com/assets/25146905/24329776/a0095d98-1210-11e7-99ad-d7137174e771.png)

**Comment by vojtatranta** [comment] 2017-03-27 08:34
Thank you for this report.

We did not encountered in and we will try to reproduce it. Thanks!

**Comment by mbibko** [comment] 2017-03-28 08:24
My laptop 1920x1080 15". Everything is big, and the layout is blurred
http://c2n.me/3IV2OQU

**Comment by umesh-velir** [comment] 2017-08-07 15:32
This happens on windows 7 too, both desktop and web apps.

**Comment by vojtatranta** [comment] 2017-12-15 10:11
Hi @umesh-velir and @mbibko,
could you please try out this test build: https://upx.cz/iML

It might fix this problem.

**Comment by umesh-velir** [comment] 2017-12-15 13:55
@vojtatranta looks like the zip is empty. 

![image](https://user-images.githubusercontent.com/7364697/34045149-c357cd0e-e175-11e7-8bac-c319ce3e933f.png)

**Comment by vojtatranta** [comment] 2017-12-15 14:57
@umesh-velir oh, I am sorry. Seems like upload broke it somehow. Try this one please:
 https://upx.cz/iMf

**Comment by umesh-velir** [comment] 2017-12-15 15:22
@vojtatranta this one worked and the designs look good. Wondering when this build is going to get released?

Thank you!

**Comment by vojtatranta** [comment] 2017-12-15 16:18
@umesh-velir Designs should be OK anyway. 

I am interested in font rendering. Is it OK too?

**Comment by umesh-velir** [comment] 2017-12-15 16:34
@vojtatranta yup, font rendering is good too.

**Comment by vojtatranta** [comment] 2017-12-15 16:36
@umesh-velir compared to stable app version in production?

**Comment by umesh-velir** [comment] 2017-12-15 18:27
@vojtatranta  yes!

![image](https://user-images.githubusercontent.com/7364697/34055058-a44b5720-e19b-11e7-9c21-b066c1e002af.png)

**Comment by vojtatranta** [comment] 2017-12-15 23:46
@umesh-velir great, we will release it asap :) thanks!

**Comment by jakubzitny** [comment] 2018-01-23 11:49
This should be fixed in latest versions of Avocode. Please let us know if you still have similar problems..

**Closed by jakubzitny** 2018-01-23 11:49 UTC
Labels: bug, willBeFixed, windows
