### ISSUE TITLE
hotkeys propagated into text fields

### ISSUE THREAD

**Issue by lukyer** [avocode/avocode#282] opened 2015-06-07 16:54 UTC
Example really annoying use case:
- select more assets
- export separately
- when entering file names, input some with letter 's'
- your export is malformed, slice tool has been activated
- next exports are really not deterministic, restart avocode is needed

**Comment by rychlis** [comment] 2015-06-12 10:38
This is a duplicate of #131 which should be fixed in Avocode 2.2.0 that was released today

**Closed by rychlis** 2015-06-12 10:38 UTC
