### ISSUE TITLE
SVG use and desc

### ISSUE THREAD

**Issue by Winni-** [avocode/avocode#1635] opened 2017-09-19 14:24 UTC
* **Version**:  2.15.3

* **Web/Desktop**: Desktop

* **Platform/Browser**: Win 10

Avocode adds not only useless but harmful code to svgs. 
It puts `path` in `defs` and `use`, problem here that it uses same `id` for every exported svg, '#a'. At least make it same as filename.
Also `<desc>Generated with Avocode.</desc>`, lads, we know that it was created with your product, and we appreciate this, we pay money for this, user of our product will not see this, but will load this, maybe a hungered times. Remove this, it does not make you advertisement.

And what definitely a bug that was mentioned before in  #1617. it moves `path` and then moves it back in `use`.

**Comment by jakubzitny** [comment] 2017-09-19 14:46
Hi @Winni-, thanks for the feedback. We're using [svgo](https://github.com/svg/svgo) for optimizing SVGs and part of your problems are caused by the optimization. If you want to tune the SVG optimization for your exports, you can turn it off in Avocode (in menu Help -> Troubleshooting -> Export optimization) and run the svgo optimizer with your custom settings to fit your needs. You can even do it in [SVGOMG](https://jakearchibald.github.io/svgomg/).

We're planning to add a power-user feature where you would be able to tune the SVG optimization settings right in Avocode, however, this will not be in coming weeks for sure.

As for the included `desc` field, I'll look into it, it should not be included in optimized SVG export.

**Comment by jakubzitny** [comment] 2017-09-19 14:49
Also regarding the problem from issue #1617, we tried to reproduce it with a bunch of SVGs we use for testing but we were not able to reproduce it and we still haven't got the original file from the user who reported it. Would you be willing to send us the original design where you encountered the problem, please?

**Comment by jakubzitny** [comment] 2017-09-19 16:27
I have fixed the removal of `desc` fields, it will be included in next Avocode release.

**Comment by Winni-** [comment] 2017-09-20 12:57
Thanks for quick reaction, and your work. The issue with transform for me looks like designer puts svg in psd and then moves it in PS, so it applies transform to it. SVGO was not capable of removing it, there need to be used other tools, but i did not found such,(i did not search well).

**Comment by jakubzitny** [comment] 2017-09-25 09:39
So what would you expect from Avocode in this case? It's quite specific case which we are probably not going to be dealing with anytime soon.

**Comment by jakubzitny** [comment] 2017-10-11 13:50
Regarding the ids, @Winni- — would it make sense to you to have every id prefixed with a unique randomly-generated 6-letter string? The prefix would be changed for every export. What do you think about that?

**Comment by Winni-** [comment] 2017-10-13 22:57
That would solve the problem.

**Comment by jakubzitny** [comment] 2017-10-20 17:26
Hey @Winni-, the ids will be added in Avocode `2.16.2` some time (hopefully) next week 😉

**Comment by jakubzitny** [comment] 2017-11-01 17:33
Hi, prefixes should be automatically added to SVGs in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:

**Closed by jakubzitny** 2017-11-01 17:33 UTC
Labels: bug, enhancement, willBeFixed

**Comment by Winni-** [comment] 2017-11-01 22:18
U r awesome

**Comment by lubomirblazekcz** [comment] 2018-11-12 10:48
I have the same problem with current version of Avocode (3.6.3)

Exported from Avocode:
```
<svg id="SVGDoc" width="23" height="22" xmlns="http://www.w3.org/2000/svg" version="1.1"
     xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:avocode="https://avocode.com/" viewBox="0 0 23 22">
    <defs>
        <path d="M1245.67448,45.02808v1.05236c0,0.65773 -0.32886,1.7101 -3.61751,2.30206c-1.85399,0.31081 -3.30669,1.76352 -3.61751,3.61752h19.73189c-0.52542,-1.85517 -2.05261,-3.2551 -3.94638,-3.61752c-3.28864,-0.62485 -3.28864,-1.64433 -3.28864,-2.30206v-1.05236"
              id="Path-0"/>
        <path d="M1252.9095,40.02934c0,3.28865 -2.07185,6.05111 -4.60411,6.05111c-2.53226,0 -4.6041,-2.63092 -4.6041,-5.91956v-3.1571c0,-3.42019 2.4336,-4.73565 4.6041,-4.73565c2.17051,0 4.60411,1.18391 4.60411,4.60411z"
              id="Path-1"/>
    </defs>
    <desc>Generated with Avocode.</desc>
    <g transform="matrix(1,0,0,1,-1237,-31)">
        <g><title>avatar-2708_0fd55e72-abf9-437a-8a9d-fce5f063b8a9</title>
            <g><title>layer2</title>
                <use xlink:href="#Path-0" fill-opacity="0" fill="#ffffff" stroke-dashoffset="0" stroke-linejoin="round"
                     stroke-linecap="round" stroke-opacity="1" stroke="#ffffff" stroke-miterlimit="50"
                     stroke-width="2"/>
            </g>
            <g><title>layer1</title>
                <use xlink:href="#Path-1" fill-opacity="0" fill="#ffffff" stroke-dashoffset="0" stroke-linejoin="round"
                     stroke-linecap="round" stroke-opacity="1" stroke="#ffffff" stroke-miterlimit="50"
                     stroke-width="2"/>
            </g>
        </g>
    </g>
</svg>
```

Exported from Adobe XD
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21.731 21.732">
  <defs>
    <style>
      .cls-1 {
        fill: none;
        stroke: #263846;
        stroke-linecap: round;
        stroke-linejoin: round;
        stroke-miterlimit: 10;
        stroke-width: 2px;
      }
    </style>
  </defs>
  <g id="avatar-2708_0fd55e72-abf9-437a-8a9d-fce5f063b8a9" transform="translate(-1 -1)">
    <path id="layer2" class="cls-1" d="M9.235,40.8v1.052c0,.658-.329,1.71-3.618,2.3A4.407,4.407,0,0,0,2,47.772H21.732a5.1,5.1,0,0,0-3.946-3.618C14.5,43.53,14.5,42.51,14.5,41.852V40.8" transform="translate(0 -26.04)"/>
    <path id="layer1" class="cls-1" d="M27.208,9.761c0,3.289-2.072,6.051-4.6,6.051S18,13.181,18,9.893V6.736A4.4,4.4,0,0,1,22.6,2a4.292,4.292,0,0,1,4.6,4.6Z" transform="translate(-10.738)"/>
  </g>
</svg>
```

**Comment by jakubzitny** [comment] 2018-11-12 10:54
This looks like you have disabled export optimization in Avocode preferences. Click on your avatar in the top right corner, go to `App preferences` and make sure the `Disable image export optimization` is unchecked.

If there is still a problem, can you please try the same on our web version? Of if you already use web version, can you try desktop?

Thanks @evromalarkey.

**Comment by lubomirblazekcz** [comment] 2018-11-12 11:05
The output is the same with export optimization enabled/disabled, also same happens in web version / desktop.

**Comment by jakubzitny** [comment] 2018-11-12 11:07
I just tried it and it works for me, so this might be a specific layer problem in your design, can you send us the private link to your design (and layer name, or just describe which layer it is), so we can inspect it on our end? Thanks.

**Comment by lubomirblazekcz** [comment] 2018-11-12 11:16
https://app.avocode.com/view/038c5aabb64646d1a69d5aed1ef75545 and layer name is avatar-2708_0fd55e72-abf9-437a-8a9d-fce5f063b8a9 (it's top right in menu)

I got the feeling this worked for me ok few weeks ago in different XD design (on my personal account on 14 day trial)

**Comment by crashmajstr** [comment] 2018-11-12 12:21
Hello @evromalarkey that's strange, I've just tried to export your layers and everything seems fine with the enabled image export optimization. 

Please, can you record a screencast of the export scenario with enabled dev tools console tab?
How to enable dev tools: Hold Alt key and click on the "Help" menu in the navbar > Troubleshooting > Dev tools

Thank you and sorry for the inconvenience.

**Comment by lubomirblazekcz** [comment] 2018-11-12 12:36
here - https://drive.google.com/file/d/1k08CB4vUQAfEbrBAF6sM6zLFVWvfBaq8/view?usp=sharing

output is 
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="23" height="22"
     viewBox="0 0 23 22">
    <defs>
        <path id="x1lra"
              d="M1245.674 45.028v1.052c0 .658-.328 1.71-3.617 2.303a4.407 4.407 0 0 0-3.618 3.617h19.732a5.097 5.097 0 0 0-3.946-3.618c-3.289-.624-3.289-1.644-3.289-2.302v-1.052"/>
        <path id="x1lrb"
              d="M1252.91 40.03c0 3.288-2.072 6.05-4.605 6.05-2.532 0-4.604-2.63-4.604-5.92v-3.156c0-3.42 2.434-4.736 4.604-4.736s4.604 1.184 4.604 4.604z"/>
    </defs>
    <g>
        <g transform="translate(-1237 -31)">
            <g>
                <use fill="#fff" fill-opacity="0" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"
                     stroke-miterlimit="50" stroke-width="2" xlink:href="#x1lra"/>
            </g>
            <g>
                <use fill="#fff" fill-opacity="0" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"
                     stroke-miterlimit="50" stroke-width="2" xlink:href="#x1lrb"/>
            </g>
        </g>
    </g>
</svg>
```

**Comment by crashmajstr** [comment] 2018-11-12 14:20
@evromalarkey yes, that's right, I got the same export and it's different from the output with disabled image export optimization. Since we don't have the same export technology as XD is using, the output would have a different structure. So, may I ask you what's wrong about this SVG output, please?
Thanks

**Comment by lubomirblazekcz** [comment] 2018-11-12 14:39
It uses defs and use, which is totally unnecessary and I dont think it's svgo, because svgomg doesn't do such thing.

This is output from XD & optimazed with svgomg (svgo gui)
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21.732 21.732">
  <defs>
    <style>
      .cls-1{fill:none;stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;stroke-width:2px}
    </style>
  </defs>
  <g id="avatar-2708_0fd55e72-abf9-437a-8a9d-fce5f063b8a9" transform="translate(-1 -1)">
    <path id="layer2" d="M9.235 40.8v1.052c0 .658-.329 1.71-3.618 2.3A4.407 4.407 0 0 0 2 47.772h19.732a5.1 5.1 0 0 0-3.946-3.618C14.5 43.53 14.5 42.51 14.5 41.852V40.8" class="cls-1" transform="translate(0 -26.04)"/>
    <path id="layer1" d="M27.208 9.761c0 3.289-2.072 6.051-4.6 6.051S18 13.181 18 9.893V6.736A4.4 4.4 0 0 1 22.6 2a4.292 4.292 0 0 1 4.6 4.6z" class="cls-1" transform="translate(-10.738)"/>
  </g>
</svg>
```

To be honest desired output for me would be something like this (it's the most optimalized and does not using any classes and id's
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 536 512">
  <path fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="50" stroke-width="46.5455" d="M201.868 326.47v24.483c0 15.313-7.633 39.796-84.177 53.597-43.175 7.43-76.759 41.007-84.114 83.567l-.087.611h459.217c-12.455-43.008-47.48-75.488-91.082-84.077l-.752-.123c-76.544-14.522-76.544-38.26-76.544-53.574v-24.483"/>
  <path fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="50" stroke-width="46.5455" d="M370.269 210.153c0 76.52-48.221 140.8-107.171 140.8-58.927 0-107.147-61.207-107.147-137.774v-73.448c0-79.593 56.646-110.219 107.147-110.219s107.147 27.555 107.147 107.147z"/>
</svg>
```

**Comment by jakubzitny** [comment] 2018-11-12 17:54
Thanks for the info @evromalarkey, this is actually a thing we've been talking about in our team already.

First thing is, svgo/svgomg behaves a bit differently for different non-optimized sources (XD vs. Avocode) and we don't use the default settings for svgo, which is also a source of more differences between us and svgomg. Moreover, our SVG export logic uses `defs` and `use` even if the shapes are used within the SVG only once. This behaviour is present in our SVG export logic on several places as it optimizes cases for various effects and multiple usages of same shape etc. We know about it and we're already working on improvements. We'll release them once they make sense as a whole and are tested properly.

**Comment by lubomirblazekcz** [comment] 2018-11-12 18:35
Thanks, good to hear!
