### ISSUE TITLE
dosn't work

### ISSUE THREAD

**Issue by set-taviskaron** [avocode/avocode#1219] opened 2016-12-20 14:07 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 105633
```
Error: Cannot open a document with no revision or no current revision
    at t.openDesignById (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:53:9553)
    at Constructor._handleEntityOpen (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:54:28789)
    at Constructor._handleEntityDoubleClick (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:53:18188)
    at Object.invokeGuardedCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.processEventQueue (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:94:20)
    at dispatchEvent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:204:20)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:278:29)
```

**Comment by bolekkerous** [comment] 2016-12-20 14:41
Hello!
Thanks for the report.

Looks like this is a duplicate of #1216 .

We know about this issue and it will be soon fixed. You can see the progress on the previously mentioned issue.

Best regards,
Bolek, Avocode Team

**Closed by bolekkerous** 2016-12-20 14:41 UTC
