### ISSUE TITLE
Avocode uninstall does not remove all files if the App is running simultaneously

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#353] opened 2015-07-17 05:26 UTC
Every time after uninstall i try to install app again, i get this error: http://prntscr.com/7tno71

**Comment by VaclovasV** [comment] 2015-07-17 05:29
after removing items related with Avocode from C:\Users\******\AppData it started to work

**Comment by rychlis** [comment] 2015-07-28 11:48
when I try to uninstall Avocode there will only remain Update.exe in "%LocalAppData%\avocode" which is correct behavior. Did the uninstaller any more files there for you?

One way I can reproduce the error is if I leave the Avocode App open while I uninstall it and install it again. In this case installer will give me the same error because it is not able to change avocode binary and files as it's still running. Was this your case maybe?

**Comment by VaclovasV** [comment] 2015-08-10 06:43
can be :) maybe uninstall process shouldn't work while app is running?

**Comment by rychlis** [comment] 2015-10-23 13:06
Yes but it seems to be very minor issue, why would you try to uninstall the app while it's running? What's the usecase?

**Comment by VaclovasV** [comment] 2015-10-23 13:20
2 of 9 people in our company had this issue, uninstallation wizard allowed to uninstall app, then it was not closed. I don't think, that issue is minor.

**Comment by rychlis** [comment] 2015-10-23 13:37
Ok there are two related problems:
1. When you uninstall the app while it's running, the files are not completely deleted. This should be fixed and it would be easy to implement after this issue is fixed in the library we use: https://github.com/Squirrel/Squirrel.Windows/issues/197
2. If you try to install the app after 1. it will fail. When I asked for the usecase I was talking only about this second problem in my comment, why would you uninstall the app while running and install it again? 

But generally it's not that minor, sorry about that

**Comment by VaclovasV** [comment] 2015-10-23 13:40
Avocode had syncing problems, so i tried to install and reinstall it (what is the difference?), after this - I couldn't event install it, because files existed. Then i removed them - install completed.

**Comment by rychlis** [comment] 2015-10-23 13:46
OK thanks for the info. We'll investigate this further and try to kill all running Avocode instances when uninstalling which should fix the issue.

**Comment by VaclovasV** [comment] 2015-10-23 13:48
I think, you should go with solution like adobe does with their products: can't uninstall anything, while software is up. You can only press retry or cancel.

**Comment by VaclovasV** [comment] 2015-10-23 14:01
@rychlis now I see what you mean, but scenario was not like i wanted to install second avocode, then running first one. Steps to reproduce:
1. Run avocode
2. Then running - try to uninstall, uninstall process completes successfully
3. Close application, try to install avocode again.
4. App fails, because of existing files

**Comment by rychlis** [comment] 2016-01-26 10:22
We've updated the installer to newer version of Squirrel.Windows in Avocode 2.5.2, the uninstaller will now automatically close any running Avocode instances before uninstalling.

**Closed by rychlis** 2016-01-26 10:22 UTC
Labels: windows
