### ISSUE TITLE
Windows desktop app should update itself automatically

### ISSUE THREAD

**Issue by kure-** [avocode/avocode#244] opened 2015-05-11 08:09 UTC
Hello,

i've run into an issue, that the Windows desktop app doesn't update automatically. As far as I've searched for previously downloaded version, the package.json says version "1.0.1". So I had to manually download the latest version (2.0.2 I think). It should update the client automatically.

Kuře

**Comment by tomashanacek** [comment] 2015-05-11 08:10
duplicate of #193

**Closed by tomashanacek** 2015-05-11 08:10 UTC
Labels: duplicate
