### ISSUE TITLE
Failed to export pages

### ISSUE THREAD

**Issue by ciaoben** [avocode/avocode#518] opened 2015-11-07 17:39 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.4
```
Error: Sketchtool failed to export pages (F5B42155-47C0-4D4B-B47A-1DD04B02DEC1)
    at /Users/ben/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/ben/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment] 2015-11-09 18:37
Hi, it would be great if you could send us the sketch file to team@avocode.com and we'll investigate what happened closely and try to export it for you. It seems that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround.

So far we've been able to reproduce this problem with documents that contained:

- huge canvas background layer used to emulate a different canvas background color
- huge grid layers used to create a custom grid
- generally any huge layer, huge in this context usually means >10000px in width or height

Removing such layers would make the Sketchtool work.

*We are also working on a new major release of Sketch extension* for some time. It fixes a lot of bugs and doesn't use Sketchtool anymore so it does not have this problem. We will let you know when the new version is released.

**Comment by rychlis** [comment] 2015-11-16 14:04
I am closing this issue as it's duplicate of #513. Please follow #513 for more updates

**Closed by rychlis** 2015-11-16 14:04 UTC
Labels: onGitlab, sketchExtension
