### ISSUE TITLE
Error syncing artboards to avocode 

### ISSUE THREAD

**Issue by BenTremper** [avocode/avocode#493] opened 2015-10-26 21:17 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/bentremper/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment] 2015-10-26 21:23
Thanks for the report. Duplicate of #472

**Closed by jankuca** 2015-10-26 21:23 UTC

**Comment by BenTremper** [comment] 2015-10-26 21:28
Thanks.
I can't sync via sketch 3 after the new sketch update they pushed today.
Any idea when this might be resolved?
Thanks


*Ben Tremper Design*
Interaction Design / Visual design

1301 Yellow Pine Ave, Unit B
Boulder, CO 80304
www.bentremper.com

O: (720) 583-2503
M: (720) 346-3882

**Comment by jankuca** [comment] 2015-10-26 21:40
We are looking at the issue as we speak. We'll keep you posted.

**Comment by urikelman** [comment] 2015-10-26 21:41
Much appreciated.
____

Uri Kelman
Director, User Experience & Design | Swagbucks

o. 310-362-7900 | m. 661-713-9387 |
uri@swagbucks.com
100 N Sepulveda Blvd., 8th Floor, El Segundo, CA 90245
www.swagbucks.com <http://www.swagbucks.com/team/kovi.k>/refer/urikelman

**Comment by BenTremper** [comment] 2015-10-26 21:49
Thanks!

**Comment by marekhrabe** [comment] 2015-10-26 23:13
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/

**Comment by BenTremper** [comment] 2015-10-26 23:20
Sweet. Works great. Thanks!
B

*Ben Tremper Design*
Interaction Design / Visual design

1301 Yellow Pine Ave, Unit B
Boulder, CO 80304
www.bentremper.com

O: (720) 583-2503
M: (720) 346-3882

**Comment by BenTremper** [comment] 2015-10-27 01:19
Hi Uri,
Another question couple questions.

1. Seems to be an issue syncing the web app now. My projects just spin and
spin, no sync occurring.

2. Also, experiencing a glitch where in various weights of a font are not
appearing in Avocode. If I have light and regular, both appear as 300
weight, there's no notion of different weights.

Thanks!
Ben


*Ben Tremper Design*
Interaction Design / Visual design

1301 Yellow Pine Ave, Unit B
Boulder, CO 80304
www.bentremper.com

O: (720) 583-2503
M: (720) 346-3882
