### ISSUE TITLE
Symbols in pages imported from Sketch are read by Avocode as images

### ISSUE THREAD

**Issue by rfcorriveau** [avocode/avocode#1052] opened 2016-08-18 13:45 UTC
Sorry, I know the problem is known, but the solution propose in another issue is no longer working for us since the last Sketch update with the new resizing properties. Now when I detach my symbol I lost the resizing for my symbol, so my mockup become a mess. I don't want to do the work over and over again. We are rethinking our use of Avocode since giving images is the same thing (and there is another tool who can fix that).

(follow up for https://github.com/avocode/avocode/issues/845)

**Comment by petrbrzek** [comment] 2016-08-28 17:47
@rfcorriveau We have a working solution for symbols. It will be included in next release. I'm closing this issue because it's a duplicate of #845.

**Closed by petrbrzek** 2016-08-28 17:47 UTC
