### ISSUE TITLE
XD file saved on Dropbox sync failed error

### ISSUE THREAD

**Issue by dimastrapchev** [avocode/avocode#1897] opened 2018-02-22 10:23 UTC
---
* **Version**: 2.19.2
* **Sketch plugin version**: 48.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 274952
---
```
No stack trace available
```

When trying to add any Adobe XD file saved in Dropbox folder to Avocode the "Sync Failed" error appears. All works fine when file is saved outside of the Dropbox.

**Comment by bolekkerous** [comment] 2018-02-22 13:42
Hey, @dimastrapchev -
thanks for the report.

We've already seen one report regarding XD and Dropbox, however we're still unable to reproduce the issue on our end.

Would you be able to upload a video of the process in which you can reproduce the problem?

And could you also share with us any problematic XD file where you can reproduce the problem?

Perhaps also the version of your XD would be helpful - thanks a lot!

**Comment by dimastrapchev** [comment] 2018-02-22 14:14
Hi,
While recording a screen capture for you I tried saving now to other dropbox folder and it worked.
The issue is only with the folder that has # in its name. My folder is called Website #198 #21
Not sure how it will react to other non-standard characters.
Hope that defines the parameters for reproduction.
Also attaching the XD file which I used to reproduce the error and versions of XD and Avocode.
Let me know if you would need any more information.
Cheers,
Dima

**Comment by bolekkerous** [comment] 2018-02-22 14:16
Hey, Dima - 
great, we can now reproduce the problem with "#" in the folder name.

We'll take a look at that and hopefully fix it soon. :)

**Comment by dimastrapchev** [comment] 2018-02-22 14:18
Great! Looking forward :)

**Comment by vojtatranta** [comment] 2018-03-08 10:39
`2.21.0` released

**Comment by dimastrapchev** [comment] 2018-03-08 10:52
It doesn’t seem to solve the issue when the hash sign is present the folder name containing XD files I want to export.

**Comment by jakubzitny** [comment] 2018-03-08 10:53
Really @dimastrapchev, sorry to hear that? I would swear I tried it really.. let me try to reproduce it again.

**Comment by jakubzitny** [comment] 2018-03-08 10:56
Oh, sorry, it actually did not get included in the 2.21.0 release. Will definitely be in the next one, we're really sorry. I will reopen this, and let you know once it's out.

**Comment by dimastrapchev** [comment] 2018-03-08 11:07
No problem! Thanks!
Still looking forward :)

**Comment by jakubzitny** [comment] 2018-04-04 15:03
2.22.0 is released, the problem should be fixed in it. Finally 😉

**Closed as completed by jakubzitny** 2018-04-04 15:03 UTC
Labels: bug, willBeFixed, xd
