### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xekushuna** [avocode/avocode#306] opened 2015-06-18 08:59 UTC
Crash while logging in with credentials.
-----

```
TypeError: Cannot read property 'headers' of undefined
  at Request._callback (/Users/gabrielizebhigie/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/auth/lib/utils/api.js:1:808)
  at self.callback (/Users/gabrielizebhigie/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/auth/node_modules/request/request.js:354:22)
  at emitOne (events.js:77:13)
  at Request.emit (events.js:166:7)
  at Request.onRequestError (/Users/gabrielizebhigie/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/auth/node_modules/request/request.js:1011:8)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketErrorListener (_http_client.js:254:9)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

**Comment by petrbrzek** [comment] 2015-06-18 10:36
Duplicate of #305. Closing.

**Closed by petrbrzek** 2015-06-18 10:36 UTC
