### ISSUE TITLE
Awful performance on 2.5.3 version

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#730] opened 2016-02-09 20:19 UTC
We are keeping all our designs on avocode, updated to the latest version and now it is unusable, because of performance issues.

**Comment by vojtatranta** [comment] 2016-02-16 13:01
Thank you for your report.
Do you mean performance when you inspect design, or in manager. Or overall speed?

**Comment by VaclovasV** [comment] 2016-02-16 13:29
@vojtatranta it is lagging everywhere. My pc is with i7 processor, 8gb ram and ssd disk, so I'm pretty sure, hardware is ok. Maybe, it is because we have lots of projects in avocode? Performance decreased after UI update.

**Comment by vojtatranta** [comment] 2016-02-16 13:34
OK, I get it.
Hardware is absolutely not a trouble. But you talk about "decreased performance after UI update". As far as I know the only UI update was about Project Manager. So it might be caused by that. But it is quite strange that app lags even if you are not doing anything in Project Manager.
Do you have like thousands of designs in Project Manager?

**Comment by VaclovasV** [comment] 2016-02-16 13:36
@vojtatranta - 32 projects in total

**Comment by vojtatranta** [comment] 2016-02-16 13:36
I presume that you run Windows on your PC.

**Comment by VaclovasV** [comment] 2016-02-16 13:36
@vojtatranta  - yes

**Comment by vojtatranta** [comment] 2016-02-16 13:43
Well. We talked about a possibility that new Project Manager might be causing all this, but it does not seem to us as possible since PM just shows stuff, not really doing anything. Downloaders and Syncers are the same, they were not changed.

However some users experience problem with syncing designs which are downloaded again and again. So Avocode might be trying to download design everytime you open it.
You might want to try tips posted here: https://github.com/avocode/avocode/issues/705

**Comment by connor-bean** [comment] 2016-06-14 14:47
This should be fixed with the 64-bit Windows update we are working on. Closing this case as we are tracking it in Zendesk and for 2.8

**Closed by connor-bean** 2016-06-14 14:47 UTC
