### ISSUE TITLE
On delete design

### ISSUE THREAD

**Issue by antigp** [avocode/avocode#486] opened 2015-10-26 10:26 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: 34378
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
  at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
  at o.handleServerAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:980)
  at e._emitItemUploadProgress (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:10424)
  at Immediate._onImmediate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/uploader.js:1:8697)
  at processImmediate [as _immediateCallback] (timers.js:369:17)
  at EventEmitter.ipc.sendSync (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at Object.RemoteMemberFunction [as showMessageBox] (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at window.confirm (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/lib/override.js:130:20)
  at requestConfirmation (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:1280)
  at t._deleteGroup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:13790)
  at t._handleAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:16245)
  at Object.ID_12 (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/stores/project.js:1:305)
  a
```

**Comment by jankuca** [comment] 2015-10-26 21:28
Thank you. This is a duplicate of #461 however, I'm closing this to keep only a single issue for the same bug. We are working on a fix which should be included in the next release.

**Closed by jankuca** 2015-10-26 21:28 UTC
