### ISSUE TITLE
The designs haven't been uploaded

### ISSUE THREAD

**Issue by insomniaOk** [avocode/avocode#1389] opened 2017-04-12 13:49 UTC
* **Version**: 2.13.5

* **Web/Desktop**:Desktop

* **Platform**: Linux

The designs haven't been uploaded (screenshot http://joxi.ru/RmzY7jOSogkKrO )

**Comment by bolekkerous** [comment] 2017-04-12 14:35
Hey, @insomniaOk -
there was an issue with processing today, but it should be already fixed.

When you try to reupload these files again, do they still fail?

**Comment by bolekkerous** [comment] 2017-05-10 15:08
This problem might be also caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:08 UTC
