### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by aienn** [avocode/avocode#456] opened 2015-09-28 16:40 UTC
Happens while exporting a project with Sketch Exporter in newest Sketch Beta.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/anton/Library/Containers/com.bohemiancoding.sketch3.beta/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment] 2015-09-29 14:30
Hi sorry we don't support Sketch 3.4 beta yet as there were some big changes, we're working on it though

this is duplicate of #437 so I am closing this issue, thanks for the report

**Closed by rychlis** 2015-09-29 14:30 UTC
Labels: duplicate

**Comment by pierrelucgagnon** [comment] 2015-10-07 14:09
Hi, i'm having the same issue but with Sketch 3.3.3

Sketch Exporter 2.1.1 running in Sketch 3.3.3
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/plgagnon/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by tomrantala** [comment] 2015-10-26 16:55
Hi @rychlis when there is coming fix for this? :) Cheers!
