### ISSUE TITLE
Error syincing design via photoshop extension 

### ISSUE THREAD

**Issue by waituk** [avocode/avocode#400] opened 2015-08-21 14:06 UTC
It happened when simply clicking on the sync tab on photoshop plugin. It got stuck at 100%  and then showed the error occured warning.

-----
App v.2.3.2-ea60620
Source UID: 42776
```
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:345:17)
```

**Comment by rychlis** [comment] 2015-10-23 14:10
sorry for the late response. Did this error really happen in Photoshop? It seems like an error report in the Avocode App. Can you reproduce it in the latest avocode 2.4.3?

**Comment by rychlis** [comment] 2016-01-26 13:11
I am closing this issue as it's a duplicate of #447. Thanks for your report.

**Closed by rychlis** 2016-01-26 13:11 UTC
Labels: needsMoreInfo

**Comment by petrbrzek** [comment] 2016-02-05 23:55
This error should be now fixed with the latest Avocode 2.5.3. Please try it and let us know.
