### ISSUE TITLE
Can't upload PSD layout

### ISSUE THREAD

**Issue by SilencerWeb** [avocode/avocode#1425] opened 2017-05-07 08:15 UTC
* **Version**: 2.13.6

 
* **Web/Desktop**: Desktop

 
* **Platform**:  Windows

I can't upload my layout, I tried 3 times, but I couldn't... I reloaded Avocode, reloaded my computer but nothing.... Maybe it's something with this layout, I don't know but I could to upload other layouts but this one I can upload no way 

**P.S. Oops, sorry, I tried for the fourth time and I could =)**

**Comment by vojtatranta** [comment] 2017-05-07 08:28
Uf, it worked!

Where did it stuck by the way? At start or at the processing?

**Comment by SilencerWeb** [comment] 2017-05-07 10:11
At the processing =) on 93% =)

**Comment by bolekkerous** [comment] 2017-05-10 15:09
This problem is caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:09 UTC
Labels: duplicate

**Comment by SilencerWeb** [comment] 2017-05-10 18:21
Oh, thank you for your message. Goodluck in your working on your very comfortable and useful app.

<div>-------- Original message --------</div><div>From: Bolek <notifications@github.com> </div><div>Date:10/05/2017  20:09  (GMT+05:00) </div><div>To: avocode/avocode <avocode@noreply.github.com> </div><div>Cc: SilencerWeb <Silencer.Web@mail.ru>,Author <author@noreply.github.com> </div><div>Subject: Re: [avocode/avocode] Can't upload PSD layout (#1425) </div><div>
</div>This problem is caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374
