### ISSUE TITLE
ctrl + z in rename image

### ISSUE THREAD

**Issue by edDimensi** [avocode/avocode#888] opened 2016-05-28 22:46 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 176342
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:170:20)
  at HTMLDocument.handler (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:251:29)
  at C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Dimen\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:185:27)

```

**Comment by jankuca** [comment] 2016-05-29 10:13
Hi, sorry about this, this is a known bug which is getting fixed in the next public release which will be out in the coming weeks.

Duplicate of #566, we are tracking the progress there which is why I'm closing this one.

**Closed by jankuca** 2016-05-29 10:13 UTC
