### ISSUE TITLE
export using Avocode plugin

### ISSUE THREAD

**Issue by Lieneke** [avocode/avocode#568] opened 2015-12-14 09:35 UTC
I installed a new plugin for Avocode and ran sync to Avocode > new design

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (9AC38BB5-A4E8-4B45-A402-13DF895FD1B6)
    at /Users/lienekekoenen/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/lienekekoenen/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by marekhrabe** [comment] 2015-12-14 11:10
By "new plugin", do you mean our [prerelease version](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md)? If not, I can recommend you trying it, because it removed highly unstable usage of Sketchtool export and proved to be pretty stable among our testers. Let me know how it goes with the new plugin

**Comment by rychlis** [comment] 2016-01-26 12:57
As this is a duplicate of #513 I am closing this one. Also [check out Sketch extension beta](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md) which is not affected by this issue

**Closed by rychlis** 2016-01-26 12:57 UTC
