### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ruddy22** [avocode/avocode#776] opened 2016-03-03 10:36 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 152045
```
TypeError: Cannot read property 'bounds' of undefined
  at Object.getBoundsForLayers (/home/ruddy22/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/document.js:1:724)
  at exportRule (/home/ruddy22/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/export.js:1:5697)
  at t._instantExport (/home/ruddy22/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11420)
  at /home/ruddy22/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11353
  at /home/ruddy22/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2159
  at CallbacksRegistry.module.exports.CallbacksRegistry.apply (/home/ruddy22/Downloads/Avocode-linux-x64/resources/atom.asar/common/api/lib/callbacks-registry.js:35:42)
  at EventEmitter.<anonymous> (/home/ruddy22/Downloads/Avocode-linux-x64/resources/atom.asar/renderer/api/lib/remote.js:146:30)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

**Comment by jakubzitny** [comment] 2016-03-03 12:22
Hi, thank you for the report. We know about this issue and we will try to fix it in coming releases.

This is duplicate of #564, I will close this issue. Let's continue the discussion there. I you have any more info or details on how to reproduce this, please let us know in #564.

**Closed by jakubzitny** 2016-03-03 12:22 UTC
Labels: bug, duplicate, linux, onGitlab
