### ISSUE TITLE
Disallow Illustrator SVG Export or indicate there is no support

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#333] opened 2015-07-02 15:40 UTC
When I exported my image as a SVG, Avocode has made a svg file with an image inside. The SVG is not a vector file. But, when I double-clicked on the layer(Smart Object Thumbnail) in photoshop , the image is opening in Illustrator.

**Comment by rychlis** [comment] 2015-07-02 15:49
Illustrator support is a duplicate of #81 which has been moved to uservoice: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support

I think it should be considered a bug that we even allow SVG export of Illustrator smart objects, there should be at least some indication that would inform user that we don't support Illustrator properly. I will keep this issue open until there is some indication

**Comment by connor-bean** [comment] 2016-06-14 14:38
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 14:38 UTC

**Comment by polikin** [comment] 2016-06-14 14:45
I tried to export my SVG, but the SVG option is disable. But, when I double-clicked on the layer(Smart Object Thumbnail) in photoshop , the image is opening in Illustrator.

http://g.recordit.co/3tsXssc48j.gif
