### ISSUE TITLE
Incorrect display of psd template in the mode "inspect"

### ISSUE THREAD

**Issue by asylbek23** [avocode/avocode#1919] opened 2018-03-03 16:50 UTC
Incorrect display of psd template in the mode "inspect", but in the 'comment' mode everything displayd is well. I also have installed version 2.17.1 there is displayed everything is well. Unfortunately Avocode itselfes installed a last version and appeared this problems.
---
* **Version**: 2.20.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 283479
---
```
No stack trace available
```

**Comment by vojtatranta** [comment] 2018-03-05 08:35
Hi @Asylbek23 could you provide a screenshot and the source PSD/Sketch files?

Thanks

**Comment by jakubzitny** [comment] 2018-03-05 09:27
Hi @Asylbek23, this is the third time we are asking you to provide some details about the incorrect display. We changed our rendering engine in past few versions and we would be happy to fix it, but we need to know where is the problem exactly. Can you provide us with minimal PSD that has problems? Or send us a public link to Avocode with names of some layers that are rendered incorrectly, please?

I will close this issue with respect to your previous one #1911.

**Closed as completed by jakubzitny** 2018-03-05 09:27 UTC
Labels: bug, duplicate, rendering

**Comment by asylbek23** [comment] 2018-03-05 15:23
This is link for psd template
https://drive.google.com/open?id=1LrtEaCOLTaqO_4_1O5HPYfRed3A_ckOi
The problem is incorrect display psd templates in the mode "INSPECT".
Do you need any more details for you?

2018-03-05 15:27 GMT+06:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment] 2018-03-05 16:06
Hi @Asylbek23, thanks a lot for the file. Yes I was inspecting this exact file previously for you and I couldn't find serious mistakes in the rendering.

Now I looked closer and I can see that some layers have slight differences. First I can see is that in the footer, in Twitter section, some texts have should be little bit lighter. Second thing is the effect in `Lorem ipsum` layers, the opacity starts very slightly a bit earlier than in COMMENT. Are these the things you're worried about? Or can you see some other problems?

If you do, please send me the names of layers (you can check these in `Layers` panel in bottom left part of the app).

If it's "just" the two problems I mentioned, I will send it to our rendering team to investigate and we'll try to improve it.

**Comment by asylbek23** [comment] 2018-03-05 16:14
This is not an isolated case.The problem is incorrect image display. That
is problem annoys me. That's it. Thank you for help me.

2018-03-05 22:06 GMT+06:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment] 2018-03-05 16:43
Yes, it is many different cases. We'd like to locate and fix as many of them as possible. So regarding this particular design, we're going to look and try to fix the mentioned two rendering cases. If you have any other (on other designs maybe), please do let us know, always with a specific link and a **layer** where you see a problem. We'll then have a look and of course fix it.

**Comment by asylbek23** [comment] 2018-03-06 01:37
Once again the problem is not in "psd" file, problem in Avocode last
versions. Because past versions worked well. For example version 2.17.1.
Here is another example:
https://drive.google.com/open?id=1WL8FyI2iLBvknCXIW20Pu2pQ8tK2fu7h
Please fix this bug. Because program is not free. Thank you!

2018-03-05 22:44 GMT+06:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment] 2018-03-07 09:10
Yes, the problem is in Avocode, but it is related to some specifics in the PSD file. As I already said, we have a new rendering engine since 2.18, which is much faster and generally better. There are few small things that still need to be addressed though and we need this kind of help from our users 😉 

We've investigated the two things I mentioned earlier and one of them (the wrong opacity in Twitter part of your footer) is actually correctly rendered, but it's wrong in 'COMMENT' mode. This is a problem in the PSD file itself, that packaged preview of the whole file does not have correct opacities all the time. So instead we're displaying the same as Photoshop. The second problem is gradient stop in collapsed text, we know about it, but so far we had more serious bugs for fixing.
