### ISSUE TITLE
Windows: Invisible layers' positions are wrong

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#66] opened 2014-10-12 22:07 UTC
I have a website grid which is invisible in my PSD, but at the center of my viewport.
When I open Avocode and toggle the grid to be visible there, it appears at the top left corner instead of being centered.

**Comment by rychlis** [comment] 2015-07-28 13:09
This should be fixed since February, can you still reproduce the issue?

**Comment by VPenkov** [comment] 2015-07-28 13:12
Those PSDs in my account are not working at all now. Is there any way I can get them back? They are stuck at "Processing"

![image](https://cloud.githubusercontent.com/assets/1693651/8932084/6d660356-3543-11e5-8f78-bf5d71fa8541.png)

**Comment by rychlis** [comment] 2015-07-28 13:24
Both designs were not set as processed, I've fixed that. I'm not sure how did that happen (and it's another issue) but it's probably related to the fact that they are over 9 months old.

Also it's possible that you will need to re-sync the design with latest Photoshop Extension to fix the issue. I'll try to find the PSD you sent us before

**Comment by connor-bean** [comment] 2016-06-14 14:26
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 14:26 UTC
Labels: bug
