### ISSUE TITLE
Wrong color into code and color picker

### ISSUE THREAD

**Issue by mrlss** [avocode/avocode#496] opened 2015-10-27 12:52 UTC
Hello, here an example of inconsistency of colors between color picker and code window. I hope that can help you. This is a PSD document.
![539056781](https://cloud.githubusercontent.com/assets/9496295/10758447/144fa06a-7cba-11e5-902d-41bfe4e0f882.jpg)

**Comment by vojtatranta** [comment] 2015-10-27 14:43
Hi, thank you for your report.
We tried to reproduce this bug, but it seems alright on our installations.
Could you please send this PSD to [team@avocode.com](mailto:team@avocode.com), so that we could investigate it more closely? Thanks.

**Comment by mrlss** [comment] 2015-10-27 14:56
Thanks for the reply. Unfortunetly, i cant send to you this design, because
this is commercial site and its confidential information. I think that bug
appear because of color scheme used for design - DELL U2713H
(C6F0K4An07RL).icm. Hope that can help. Thanks.

2015-10-27 16:43 GMT+02:00 vojtatranta <notifications@github.com>:

**Comment by vojtatranta** [comment] 2015-10-27 15:10
That is unfortunate.
Do you know the current settings of color scheme of this particular PSD?
Or perhaps you could send us just part of the PSD with this button.

**Comment by mrlss** [comment] 2015-10-27 16:16
I'll send to you guys a part of design to email provided by you, please
check, hope that helps you to find a solution.

2015-10-27 17:10 GMT+02:00 vojtatranta <notifications@github.com>:

**Comment by vojtatranta** [comment] 2015-10-27 16:32
Great.
We looked at it and the PSD was saved in wrong format (for DELL U2713H) which caused this issue.
The right color seems to be one which gives you color picker.
We added this issue to our TODO list.
Thank you.

**Comment by connor-bean** [comment] 2016-06-14 14:41
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 14:41 UTC
Labels: bug, onGitlab
