### ISSUE TITLE
Download process Error: channel closed

### ISSUE THREAD

**Issue by Mumin0v** [avocode/avocode#388] opened 2015-08-12 13:20 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.1-9839e14
Source UID: 22458
```
Error: channel closed
    at ChildProcess.target.send (child_process.js:396:26)
    at Task.module.exports.Task.send (/Applications/Avocode.app/Contents/Resources/app.asar/src/task.js:125:27)
    at e._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6156)
    at e._addRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4171)
    at e.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2016)
    at e.downloadFiles (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7718)
    at t.module.exports.t._createImageRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1938)
    at t.module.exports.t.downloadImages (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1150)
    at e._downloadRevisionImages (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13768)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:12583
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6877
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7463
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
    at FSReqWrap.oncomplete (fs.js:77:15)
```

**Comment by rychlis** [comment] 2015-08-12 13:24
Looks like issue #340, this means that the downloader process (that downloads design data) crashed for some reason. Can you reproduce the error again or was it a one-time occurence?

**Comment by Mumin0v** [comment] 2015-08-12 13:31
only once

**Comment by rychlis** [comment] 2015-10-23 14:01
We will fix it in the next release, sorry for the delay

**Comment by connor-bean** [comment] 2016-06-14 14:39
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 14:39 UTC
Labels: bug, inprogress, onGitlab
