### ISSUE TITLE
PSD failed to process after 20 minutes "Processing 30%"

### ISSUE THREAD

**Issue by mcfinley** [avocode/avocode#1438] opened 2017-05-18 04:37 UTC
**Version**:  2.14.0
**Web/Desktop**: Desktop
**Platform**:  Ubuntu 16.04

PSD file failed to process after 20 minutes of "Processing 30%" with a red preview and "What's wrong" button.

Causing problem PSD (40mb):
https://drive.google.com/open?id=0ByA2zSuzfnhTOUtEbjBfUDNZV2M

**Comment by mcfinley** [comment] 2017-05-18 08:02
When psd is "Processing 30%" and got opened in comment mode then switched to inspect, it shows "Processing 65%". After the fail the same inspect mode says "Upload failed". idk if itd help but just in case

**Comment by bolekkerous** [comment] 2017-05-18 11:20
Hey, @mcfinley -
this looks like a problem caused by using huge bitmap images in the design (usually stock images with huge resolutions) or also by large complexity of the design. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat.

I've already uploaded the design for you and you can use this link to assign the design to your team: https://manager.avocode.com/view/fde17c115f1c43c981d7d317f5e14f8a/assign/

Please let me know once you assign the design to your project and I'll delete the link from this issue.

Since it's a duplicate issue of #1374, I'll close this one. 

Best regards,
Bolek, Avocode Team

**Closed by bolekkerous** 2017-05-18 11:20 UTC
