### ISSUE TITLE
the program does not start

### ISSUE THREAD

**Issue by StasZnaydyonov** [avocode/avocode#2105] opened 2018-07-31 23:16 UTC
---
* **Version**: 3.2.0
* **Web/Desktop**: Desktop
* **Platform**: win32
---
```
{}
```

**Comment by jakubzitny** [comment] 2018-08-01 11:04
Hi @StasZnaydyonov, thanks for reporting this. When did this start happening? And when exactly during the app start do you get this error? How did you install Avocode?

Can you try our web app at [http://app.avocode.com](app.avocode.com) to see if that works for you?

**Comment by jakubzitny** [comment] 2018-08-02 10:41
Hi again @StasZnaydyonov, can you please try using this beta build to see if the problems go away? https://we.tl/zBDDAwCmdQ

We're trying to find the root cause of this behaviour but we're not really able to reproduce it properly. The build should definitely help, we'll be happy if you use it and give us a feedback.

**Comment by jakubzitny** [comment] 2018-08-16 08:44
Updated testing build: https://we.tl/xDf8dHBpKI.

**Comment by jakubzitny** [comment] 2018-08-23 11:26
Did you have a chance to try out any of the builds we've sent @StasZnaydyonov, please?

**Comment by jakubzitny** [comment] 2018-09-07 10:02
Closing with respect to #2119 and #2076.

**Closed as completed by jakubzitny** 2018-09-07 10:02 UTC
Labels: bug, duplicate, waitingForUser, needsMoreInfo, electronRelated
