### ISSUE TITLE
Can't open a PSD

### ISSUE THREAD

**Issue by niafreu** [avocode/avocode#1508] opened 2017-07-06 20:23 UTC
IMPORTANT: Please try to describe how did it happen.
I just opened it and it doesn't open it, just this error message.
-----
App v. `2.14.5`
Avocode UID: 159899
```
Error: Files over size limit are not supported. (500 MB)
    at Object.normalizeError (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:16896)
    at Object.normalizeResponse (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:16734)
    at t.normalizeResponse (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1993723)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1989784
    at Request._callback (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1992564)
    at Request.self.callback (/opt/Avocode/resources/app.asar/node_modules/request/request.js:186:22)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/Avocode/resources/app.asar/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/Avocode/resources/app.asar/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jakubzitny** [comment] 2017-07-06 21:26
Hi @niafreu, thanks for reporting this. We already have a fix for this in our development branch and it will be included in next release of Avocode.

This is the same as #1500, the problem is the size of your file. We do not support upload of 500+MB PSDs into Avocode. If you want to upload the file, please download our PS plugin, or send the PSD to team@avocode.com so our support team can upload it for you.

**Comment by jakubzitny** [comment] 2017-07-12 17:36
Hi there, we fixed how we handle this problem in latest Avocode `2.14.6` so I'll close this issue. If you still have problems with uploading large PSDs, please use our PS plugin or send the file to team@avocode.com so our support guys can upload it for you.

**Closed by jakubzitny** 2017-07-12 17:36 UTC
Labels: regression, willBeFixed
