### ISSUE TITLE
Avocode 2.4.5 installer failing

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#521] opened 2015-11-12 19:06 UTC
![image](https://cloud.githubusercontent.com/assets/1693651/11128213/16fefc6a-8981-11e5-9308-e8029a74daa6.png)

I had a fresh Windows reinstall yesterday. My 2.4.3 Avocode is working but the new one isn't. Don't know where I can view the setup log.

**Comment by VPenkov** [comment] 2015-11-12 19:12
After some digging, it looks like it actually installed to
C:\Users\MyUserName\AppData\Local\avocode\app-2.4.5

The 2.4.4 and 2.4.3 versions are there as well. So the install probably fails at its end.

**Comment by petrbrzek** [comment] 2015-11-12 20:14
I'm not able to reproduce the issue. Does this also happen if you uninstall Avocode and then install it again?

**Comment by VPenkov** [comment] 2015-11-12 20:19
Yes. While we're at it, you should add a confirmation dialog to the uninstall wizard.
It actually does manage to install itself but shows an error and fails to create any shortcuts.

I tried re-downloading the package and got the same result.

**Comment by mark-reason** [comment] 2015-11-13 09:06
I had the same issue, had the error but has installed.

**Comment by spa** [comment] 2015-11-13 16:12
Same issue: received the install error, and found that it actually did install into C:\Users\MyUserName\AppData\Local\avocode\app-2.4.5

**Comment by rychlis** [comment] 2015-11-13 16:39
Hi the log file should be located in the C:\Users\MyUserName\AppData\Local\avocode\SquirrelSetup.log

The problem is that every launch of Avocode will overwrite this log file so we need you to launch the installer again and send us the log after it fails if you can.

It's probably related to https://github.com/Squirrel/Squirrel.Windows/issues/322 which is fixed but we are not using the new version yet

**Comment by VPenkov** [comment] 2015-11-13 16:43
I'm getting no such file.
I used to have it but then you had me uninstall Avocode. I did have a look though, and it had some old stuff there.

I tried to create it manually, but that didn't help.

**Comment by rychlis** [comment] 2015-11-13 16:46
Do you have Group Policy restrictions enabled on your machine by any chance? See the last paragraph [Enterprise environments and Group Policy](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/troubleshooting.md#enterprise-environments-and-group-policy)

Try running Setup.exe from %LocalAppData%\SquirrelTemp like in the troubleshooting guide

**Comment by VPenkov** [comment] 2015-11-13 16:48
Yeah, there's no setup.exe there but look what I found
http://pastebin.com/Tz5wDwM1

**Comment by rychlis** [comment] 2015-11-13 16:54
>--- (Inner Exception #0) System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

ok it seems like your system went out of memory based on the log. How much free memory do you have? 

Anyways here is a link to a zip version of avocode without installer: manager.avocode.com/download/avocode-app/windows-zip/

**Comment by VPenkov** [comment] 2015-11-13 16:55
I've got 8 gigs and I'm nowhere near running out of memory.

**Comment by rychlis** [comment] 2015-11-13 17:06
Ok it's probably this issue: https://github.com/Squirrel/Squirrel.Windows/issues/309

Seems like it's a problem in `NuGet` library used by Squirrel.Windows library we use. You can use the zip link until they or we find a fix

@mark-reason @spa could you also look into %LocalAppData%\SquirrelTemp\ if there is a squirell log to confirm this is the same issue? If it's not there it might also be in %LocalAppData%\avocode\

**Comment by spa** [comment] 2015-11-13 17:18
Looks my log is similar: http://pastebin.com/jvHMpd1K

**Comment by VPenkov** [comment] 2015-11-16 14:27
When can we expect a fix?

I don't reckon we'd get an update notification inside Avocode, correct? It doesn't run through update.exe anymore.

**Comment by rychlis** [comment] 2015-11-19 13:10
@VPenkov update.exe is not needed for update notifications, in-app update notifications are implemented universally for all platforms so they will work even with the zip version.

I am not sure when to expect a fix, we will at least add a zip link to the download page for now. We are not able to reproduce this on our windows machines so it's hard to fix for us at the moment :(

According to the [Squirell](https://github.com/Squirrel/Squirrel.Windows/issues/309) issue they are going to replace the buggy NuGet implementation with a different one which is the best solution but there is no ETA on that.

Based on the Squilrell issue the problem happens when there is a big file archive like our `resources/app.asar`. The weird thing is that in 2.4.5 this file is actually *smaller* than in 2.4.3 and it seems that people didn't bump into this issue with 2.4.3. We'll definetely try to investigate this further

**Comment by VPenkov** [comment] 2015-11-19 13:49
Yep, 2.4.3 didn't have this. I'm inclined to provide remote desktop access to investigate the issue. Hit me up at vergil@moongrab.com (and use an @avocode.com mail if you do so) if you could make use of that.

**Comment by rychlis** [comment] 2015-11-19 13:53
Actually I was looking into wrong folder and the 2.4.5 windows asar is in fact larger than in 2.4.3. That's weird because on linux/osx the asar is a lot smaller in 2.4.5. There is probably a build process problem on windows, we'll try to fix it

**Comment by MazheM** [comment] 2015-11-20 19:05
I have the same error on install, but i can run Avocode.exe from folder and its runs.

**Comment by martynas-m** [comment] 2015-12-17 07:46
the same there, error on install, but still can find and run it from AppData\local and run it.

**Comment by mvaldas9** [comment] 2016-01-04 09:07
error on install, can find and run avocode from Appdata\...

**Comment by rychlis** [comment] 2016-01-26 10:30
This error should be now fixed with the latest Avocode 2.5.2. Sorry it took so long!

**Closed by rychlis** 2016-01-26 10:30 UTC
Labels: bug, windows
