### ISSUE TITLE
Document failed to load

### ISSUE THREAD

**Issue by sunshinetainted** [avocode/avocode#2155] opened 2018-09-21 10:15 UTC
---
* **Version**: 3.5.1
* **Sketch plugin version**: 51.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 412469
---
```
Error: Remote octopus link missing
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3074269)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3073276)
    at tryCatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:116:21)
    at n (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070732)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3070871
    at Promise (<anonymous>)
    at e.<anonymous> (file:///Applications/Avocode.app/Contents/Resources/app.asar/
```

**Comment by jakubzitny** [comment] 2018-09-21 10:35
Hi @sunshinetainted, thanks for reporting this problem. Can you please send us the link the the project or design where this is happening? We'll investigate the problem.

In the meantime you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by jakubzitny** [comment] 2018-09-21 10:36
This is a duplicate of #2153. I'll close this, but please do send us the details.

**Closed as completed by jakubzitny** 2018-09-21 10:36 UTC
Labels: bug, duplicate, waitingForUser

**Comment by sunshinetainted** [comment] 2018-09-21 10:43
Hi, here is the link to the project: https://app.avocode.com/projects/694558/

The problem was resolved upon restarting the app.

**Comment by jakubzitny** [comment] 2018-09-21 10:46
I see, that was probably a race condition when server was still processing the design. Thanks.
