### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Lykhoyda** [avocode/avocode#237] opened 2015-05-06 08:13 UTC
Describe your problem here…

-----

```
TypeError: Cannot read property 'x' of null
  at r (/home/antony/Desktop/Avocode/resources/app/node_modules/slice-tool/lib/slice-tool.js:1:565)
  at b.module.exports.b._mousemoveDrag (/home/antony/Desktop/Avocode/resources/app/node_modules/slice-tool/lib/slice-tool.js:10:127)
  at /home/antony/Desktop/Avocode/resources/app/node_modules/slice-tool/lib/slice-tool.js:1:148
  at c.module.exports.Emitter.emit (/home/antony/Desktop/Avocode/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at c.mousewheel (/home/antony/Desktop/Avocode/resources/app/node_modules/avocode/lib/stage.js:23:423)
  at HTMLCanvasElement.<anonymous> (/home/antony/Desktop/Avocode/resources/app/node_modules/avocode/lib/stage.js:1:324)

```

**Comment by petrbrzek** [comment] 2015-05-06 17:42
Duplicate of #235.

**Closed by petrbrzek** 2015-05-06 17:42 UTC
Labels: bug
