### ISSUE TITLE
Inspector shows color hex values that don't exist in the Sketch artboard

### ISSUE THREAD

**Issue by beelmanaire** [avocode/avocode#1714] opened 2017-11-01 14:16 UTC
* **Version**: 2.16.1

* **Web/Desktop**: Publisher uses desktop, QA use web

* **Platform/Browser**: OS X 10.12.5 and Chrome 61.0.3163.1

In an artboard I have text with a yellow hex value of #F8E44B and pink hex value of #FD266C in the same block, but Avocode is showing hex values of ##f7e97d, ##f2df55, #f7ea7d, and #e1275b - None of which are in the artboard.

In troubleshooting, I deleted the artboard from Avocode, quit Avocode, quit Sketch, and then re-synced the artboard only to arrive at the same result.

The text in this instance has no text styles from the style library applied.

**Comment by vojtatranta** [comment] 2017-11-01 14:20
hi @beelmanaire can you send us the sketch file at team@avocode.com

**Comment by beelmanaire** [comment] 2017-11-01 14:28
@vojtatranta Sent, thank you.

**Comment by vojtatranta** [comment] 2017-11-01 14:52
Tracking internally as: 4414

**Comment by beelmanaire** [comment] 2017-11-06 16:07
Checking in to see if there have been any insights made in reviewing my issue. Thanks in advance.

**Comment by jakubzitny** [comment] 2017-11-13 12:30
Hi @beelmanaire, we'll need a while to fix this issue. We're currently using `sketchtool` for getting the info about artboards and layers. This particular issue is caused by `sketchtool` returning us wrong colors in some (edge) cases.

We're preparing a new version where you'll be able to do drag and drop Sketch files into Avocode and this issue will be fixed there. We'll let you know here once it's ready, please give us several weeks.

You can also join our [Avocode Community on Slack](https://community.avocode.com) to have a beta version earlier.

**Comment by jakubzitny** [comment] 2017-11-13 12:38
Actually we have this issue already in #1376 so I am going to close this thread and continue the conversation there.

**Closed by jakubzitny** 2017-11-13 12:38 UTC
Labels: bug, onGitlab, sketchPlugin

**Comment by beelmanaire** [comment] 2017-11-13 17:49
Thanks for the update @jakubzitny - We hope a solution is found as the team loved using Avocode while we were testing it for our workflow, but can't make the move until this is sorted out. Thanks again.
