### ISSUE TITLE
No frames around images

### ISSUE THREAD

**Issue by sakralbar** [avocode/avocode#1481] opened 2017-06-16 16:04 UTC
* **Version**: 2.14.4
* **Web/Desktop**: Desktop
* **Platform**:  Debian stretch

Hello.
The problem in screenshot below.
![issue](https://user-images.githubusercontent.com/11180735/27234456-ce3b982a-52c5-11e7-9479-d3b513b69518.jpg)

And here the link to problem psd: https://yadi.sk/d/r1RK-jVo3KCFMa

**Comment by glutaminefree** [comment] 2017-06-22 09:49
Man, it's disgusting.

**Comment by vojtatranta** [comment] 2017-06-26 16:17
I assume this is a clipping mask?

**Comment by sakralbar** [comment] 2017-06-28 13:53
Maybe. I'm not familiar with Photoshop. I can only give a link to download psd with problem in Avocode)

**Comment by jankuca** [comment] 2017-06-28 14:23
I examined the PSD and it is a layer clipped by a mask which has a stroke on it. This is a known bug which will get fixed in the coming months.

**The stroke/border is correctly rendered when exported.** This is only a problem with the design displayed in Avocode, not when it is exported.

![screen shot 2017-06-28 at 16 23 10](https://user-images.githubusercontent.com/367262/27642114-1a37a4ba-5c1e-11e7-8aa8-95c8fe602e74.png)

**Comment by jankuca** [comment] 2017-06-28 14:25
Duplicate of #462. You can track further progress there.

**Closed by jankuca** 2017-06-28 14:25 UTC
