### ISSUE TITLE
Feature Request: Command + Scroll-wheel for zoom on designs in acocode web app

### ISSUE THREAD

**Issue by JayCarney** [avocode/avocode#1321] opened 2017-03-14 01:41 UTC
All other shortcuts seem the same as the desktop app (didn't actually notice I was using it at one point, had the desktop app and the web app open at the same time), just missing the easy zoom-in zoom-out from the scroll-wheel + command, makes getting around a design much slower without it.

**Comment by vojtatranta** [comment] 2017-03-14 08:14
@JayCarney noooo, how could you not notice that you are no in the desktop app. The web app is soo much faster :( :-D

Commnad + scroll should work on the web. I just tried it and it runs OK.

**Comment by bolekkerous** [comment] 2017-03-14 08:59
@JayCarney if it still does't work for you, could you please tell us which OS and browser are you using?

Thanks!

**Comment by JayCarney** [comment] 2017-03-14 23:24
Just double checked; Command + scroll ins't working for me in Chrome, Safari, or Firefox.

Shift + scroll is moving horizontally though.

Mac OS: Sierra 10.12
Chrome: 56.0.2924.87 (64-bit)
Safari: 10.0 (12602.1.50.0.10)
Firefox: 52.0 (64-bit)

Not sure if this will help, but this is the contents of the event object passed to a generic keydown listener on my machine in Chrome, figured the keycodes etc might help rule out some possible causes

```javascript
{
altKey:false,
bubbles:true,
cancelBubble:false,
cancelable:true,
charCode:0,
code:"MetaLeft",
composed:true,
ctrlKey:false,
currentTarget:null,
defaultPrevented:false,
detail:0,
eventPhase:0,
isComposing:false,
isTrusted:true,
key:"Meta",
keyCode:91,
location:1,
metaKey:true,
path:Array[6],
repeat:false,
returnValue:true,
shiftKey:false,
sourceCapabilities:InputDeviceCapabilities,
srcElement:body,
target:body,
timeStamp:252400.91500000004,
type:"keydown",
view:Window,
which:91,
__proto__: KeyboardEvent
}
```

**Comment by bolekkerous** [comment] 2017-03-15 16:32
You're right, we managed to find the problem - we'll close the issue as soon as the problem is fixed. 

Thanks a lot for your report, it's very helpful. :)

**Comment by vojtatranta** [comment] 2017-03-20 11:06
We will release `2.13.1` on Wednesday and this feature will be there.

**Comment by JayCarney** [comment] 2017-03-22 00:01
Awesome, love your work

**Comment by JayCarney** [comment] 2017-03-22 00:02
wrong button

**Comment by vojtatranta** [comment] 2017-03-22 17:39
deployed https://app.avocode.com/

**Closed by vojtatranta** 2017-03-22 17:39 UTC
Labels: willBeFixed
