### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by Zabavsky** [avocode/avocode#1371] opened 2017-04-07 10:13 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.3`
Avocode UID: 28514
```
TypeError: Cannot read property 'id' of undefined
    at p (https://js.intercomcdn.com/frame.918f1c1f.js:1:29279)
    at c (https://js.intercomcdn.com/frame.918f1c1f.js:5:18433)
    at https://js.intercomcdn.com/frame.918f1c1f.js:5:18734
    at Array.map (native)
    at https://js.intercomcdn.com/frame.918f1c1f.js:5:18711
    at https://js.intercomcdn.com/frame.918f1c1f.js:2:22777
    at https://js.intercomcdn.com/frame.918f1c1f.js:2:22213
    at p (https://js.intercomcdn.com/frame.918f1c1f.js:2:22982)
    at https://js.intercomcdn.com/frame.918f1c1f.js:2:22941
    at Array.map (native)
    at p (https://js.intercomcdn.com/frame.918f1c1f.js:2:22916)
    at Array.<anonymous> (https://js.intercomcdn.com/frame.918f1c1f.js:18:2915)
    at l (https://js.intercomcdn.com/frame.918f1c1f.js:9:18573)
    at https://js.intercomcdn.com/frame.918f1c1f.js:18:893
    at https://js.intercomcdn.com/frame.918f1c1f.js:17:24811
    at https://js.intercomcdn.com/frame.918f1c1f.js:18:215
    at https://js.intercomcdn.com/frame.918f1c1f.js:17:23283
    at https://js.intercomcdn.com/frame.918f1c1f.js:17:31832
    at https://js.intercomcdn.com/frame.918f1c1f.js:29:14875
    at onUserPresent (https://js.intercomcdn.com/frame.918f1c1f.js:5:16720)
    at HTMLDocument.l (https://js.intercomcdn.com/frame.918f1c1f.js:18:3944)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by bolekkerous** [comment] 2017-04-10 10:53
Hey,
thanks for the report.

Do you remember how the error happened? What did you do exactly before this error popped-up?

Thanks!

**Comment by petrbrzek** [comment] 2017-04-11 13:41
Duplicate of #1338

**Closed by petrbrzek** 2017-04-11 13:41 UTC
