### ISSUE TITLE
Apple Color Emoji problem in sketch

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1643] opened 2017-09-27 11:24 UTC
* **Version**: 2.15.2
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 68767
---

```
Error: Command failed: "/Applications/Sketch Beta.app/Contents/Resources/sketchtool/bin/sketchtool" dump --overwriting --use-id-for-name --formats="png" "/Users/pavelminkevich/Desktop/Дизайны/Bulletin/input/27-09-2017/bulletin_menu_details_26sept_.sketch" > "/var/folders/f0/r50dzsr56wd8wwp__fxb27sr0000gn/T/sketch-avocode-full-dump.1506511419171.json"
2017-09-27 14:23:40.209 sketchtool[2950:120155] -[ECCommandLineEngine outputError:format:]: unrecognized selector sent to instance 0x7fe358c15980
Command threw exception

(ECCommandLineDomain:5)


    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by jakubzitny** [comment] 2017-09-27 12:47
Hi @Pavlo-Minkievych, thanks again for your report. This is a weird error that should not be happening and we're not really sure how to reproduce it. Could you please send us the design to team@avocode.com if it's possible? Also, what version of Sketch Beta are you using? Is it the latest 47? I tried it and it seems to be working, there might be some problems in other beta versions though.

**Comment by jakubzitny** [comment] 2017-09-27 13:46
Hi @Pavlo-Minkievych, I found where the problem is. You are using `Apple Color Emoji` font for emojis which causes problems with exporting the data from Sketch.

The problem in the file you sent us is only in one layer with name `😀 😃 😄 😁 😆 😅 😂`. The layer is on `Page 1` on Artboard `Add emoji` under `Group 3 Copy` -> `Group 2`. If you remove this layer or change the font for emojis to e.g. `Arial`, the emojis should look the same and it should work correctly.


I will reach out to the Sketch.app team to help us with resolving this issue more thoroughly, because it's a problem in `sketchtool`. Thanks for cooperation.

**Closed** 2018-02-02 16:16 UTC
Labels: bug, sketchPlugin
