### ISSUE TITLE
Ubuntu 14 error

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#453] opened 2015-09-23 12:42 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.2-d618096
Source UID: 29596
```
Error: channel closed
  at ChildProcess.target.send (child_process.js:396:26)
  at Task.module.exports.Task.send (/home/asd/_Avocode/resources/app.asar/src/task.js:125:27)
  at e._send (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6156)
  at e._addRequest (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4171)
  at e.downloadFiles (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2016)
  at e.downloadFiles (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7718)
  at t.module.exports.t.downloadThumbnails (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1032)
  at e._downloadThumbnails (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:15353)
  at /home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:14936
  at /home/asd/_Avocode/resources/app.asar/node_modules/async/lib/async.js:246:17
  at /home/asd/_Avocode/resources/app.asar/node_modules/async/lib/async.js:122:13
  at _each (/home/asd/_Avocode/resources/app.asar/node_modules/async/lib/async.js:46:13)
  at async.each (/home/asd/_Avocode/resources/app.asar/node_modules/async/lib/async.js:121:9)
  at _asyncMap (/home/asd/_Avocode/resources/app.asar/node_modules/async/lib/async.js:245:13)
  at Object.map (/home/asd/_Avocode/resources/app.asar/node_modules/async/lib/async.js:216:23)
  at e._downloadThumbnailsInGroups (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:14989)
  at e._syncProjects (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:9504)
  at e._onUserData (/home/asd/_Avocode/resources/app.asar/node_modules/@avocode/co
```

**Comment by rychlis** [comment] 2015-10-23 15:01
Thanks for the report, this is duplicate of #388

**Closed by rychlis** 2015-10-23 15:01 UTC
