### ISSUE TITLE
The design failed processing and cannot be opened...

### ISSUE THREAD

**Issue by shitpoet** [avocode/avocode#1323] opened 2017-03-15 05:49 UTC
* avocode-app-linux-2.12.6: 

* native:

* linux: 

Fresh install of Avocode.

After uploading this psd - https://drive.google.com/drive/folders/0B6-DjrCemVsoZVZlbDh4NFNiWHc
received this error when tried to open it:
"The design failed processing and cannot be opened..."

**Comment by bolekkerous** [comment] 2017-03-15 16:45
Hey, @shitpoet -
could you hit us up at team@avocode.com from your Avocode account e-mail?

We can help you upload the design there.

**Comment by shitpoet** [comment] 2017-03-20 05:36
hi, thank you, but i do not need help with uploading that psd. i just want to help you improve your app by reporting bugs.

now i updated avocode to 2.13 and i experience the same problem with another psd - https://www.dropbox.com/sh/idlzla3h4z21w0e/AACn-5w668Jasv9pGtgNzowoa?dl=0&preview=VSLP2K17_Desktop_1920px.psd

i tried to upload it several thimes in 2.12.6 linux 64 bit and in 2.13.0 linux 64 bit

strangely enough, the mobile version of the psd is ok - https://www.dropbox.com/sh/idlzla3h4z21w0e/AACn-5w668Jasv9pGtgNzowoa?dl=0&preview=VSLP2K17_Mobile_640px.psd

**Comment by bolekkerous** [comment] 2017-05-10 15:10
This problem is probably caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:10 UTC
Labels: duplicate
