### ISSUE TITLE
I got this error trying to open a layout

### ISSUE THREAD

**Issue by joaogouveia** [avocode/avocode#223] opened 2015-04-29 22:36 UTC
Describe your problem here…

-----

```
TypeError: Cannot read property 'imageName' of undefined
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:5:14
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at g.module.exports.g._getImagesToLoad (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:5:135)
  at new g (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:1:431)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:29:411
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

**Comment by tomashanacek** [comment] 2015-04-30 10:24
Duplicate of #221

**Closed by tomashanacek** 2015-04-30 10:24 UTC
