### ISSUE TITLE
Object of undefined

### ISSUE THREAD

**Issue by nikbeznosikov** [avocode/avocode#1161] opened 2016-10-11 11:45 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.9.1
Source UID: 86969
```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/home/user/Programms/Avocode-linux-x64/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/home/user/Programms/Avocode-linux-x64/resources/electron.asar/browser/rpc-server.js:305:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/home/user/Programms/Avocode-linux-x64/resources/electron.asar/browser/api/web-contents.js:165:13)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/home/user/Programms/Avocode-linux-x64/resources/electron.asar/renderer/api/remote.js:176:13)
    at remoteMemberFunction (/home/user/Programms/Avocode-linux-x64/resources/electron.asar/renderer/api/remote.js:110:18)
    at t.terminate (file:///home/user/Programms/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:20:4304)
    at
```

**Comment by vojtatranta** [comment] 2016-10-11 12:26
Dear @nikbeznosikov,
be sure that this bug makes us angry much more than you can possibly imagine. Even more, than you are now.

I absolutely understand your mood.

Let me explain.

This bug has been with us for a half of year now and we were not able to fix it.

First of all, it pops up with irregularly so we cannot reproduce it.

Second, this is not a bug in our code base. As you can see according to the stack trace, this error raises in Electron code base which is Avocode built on.

And there is a lots of issues referencing this issues and so far it was not fixed by Github's Electron team.
Take a look here: https://github.com/electron/electron/issues/7351

As you can see I proposed a solution that would silent this error but I don't think it will be accepted because it fixes nothing.

Until then we are not quite able to do anything with this unless we would make the whole app slow and laggish by moving downloading of assets back to render process. As you know, this would make other users angry and would not help anyone.

Thank you for your understanding.

**Comment by petrbrzek** [comment] 2016-10-11 13:03
@nikbeznosikov you are using old version of the app, please update to the latest. Also I'm closing the issue as it's a duplicate.

**Closed by petrbrzek** 2016-10-11 13:03 UTC

**Comment by nikbeznosikov** [comment] 2016-10-11 13:28
Guys, thank you for your answers. In fact, I probably joking than angry. A good program you have just hung a little unsuccessfully)
