### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by Danny-weebo** [avocode/avocode#1340] opened 2017-03-23 11:33 UTC
every time when I clicked on + Upload design and picked a file or dragged it into the project's folder its showing this error.

-----
App v. `2.13.1`
Avocode UID: 20414
```
TypeError: toISOString is not a function
    at String.toJSON (<anonymous>)
    at Object.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/core-js/modules/_ctx.js:18:15)
    at JSON.stringify (<anonymous>)
    at stringify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/json-stringify-safe/stringify.js:5:15)
    at Raven._makeRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1559:22)
    at Raven._sendProcessedPayload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1485:56)
    at Raven._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1442:14)
    at Raven._processException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1290:14)
    at Raven._handleStackInfo (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1196:14)
    at Raven.captureException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:350:18)
    at e.captureException (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:15444)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:7:23221
```

**Comment by vojtatranta** [comment] 2017-03-26 18:26
I tried to reproduce it on monday but with completely no luck at all.

We will go deeper into this further on.

**Comment by vojtatranta** [comment] 2017-03-28 13:42
This is also a duplicate of #1332

**Closed by vojtatranta** 2017-03-28 13:42 UTC
