### ISSUE TITLE
Log In issues

### ISSUE THREAD

**Issue by ibrahimtaguri** [avocode/avocode#929] opened 2016-06-16 17:58 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: null
```
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:79:11)
    at Object.urlParse [as parse] (url.js:73:5)
    at t._normalizeUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:378)
    at t._addItemWithUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:20:29852)
    at t._handleAction (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:20:27282)
    at Object.ID_2 (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:20:25041)
    at Dispatcher._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
    at Dispatcher.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
    at e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:21:8327)
    at t.e.dispatch (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:2:20643)
    at t.addItemWithUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:15:23134)
    at e.openUri (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:14:17277)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:27666
    at Array.forEach (native)
    at t._openInitialUris (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:27600)
    at Immediate._onImmediate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:24755)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by jakubzitny** [comment] 2016-06-16 19:03
Hi @ibrahimtaguri, thanks for the report. This is the same as #924 so I will close this thread. The problem is happening after clicking on "Open in Avocode" app in our web manager. Logging into the app manually and opening a design directly from the app should work correctly.

This will be fixed in `2.8.1`.

**Closed by jakubzitny** 2016-06-16 19:03 UTC
Labels: 2.8.0, bug, duplicate, willBeFixed
