### ISSUE TITLE
Sketch export fail

### ISSUE THREAD

**Issue by launchsequence** [avocode/avocode#515] opened 2015-11-04 16:25 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.4
```
Error: Sketchtool failed to export pages (9868CAE0-1531-4552-8D1A-86849592EA6C)
    at /Users/ef/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/ef/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by launchsequence** [comment] 2015-11-04 16:26
synched sketch file as new design

**Comment by petrbrzek** [comment] 2015-11-05 00:22
Thanks for reporting the issue. It's a duplicate of #513 so I will close this one.

**Closed by petrbrzek** 2015-11-05 00:22 UTC
Labels: bug, sketchExtension
