### ISSUE TITLE
Syncing from sketch works but project stays empty

### ISSUE THREAD

**Issue by JorindeReijnierse** [avocode/avocode#791] opened 2016-03-10 15:50 UTC
We're using sketch plugin 3.3 (on your website its called 2.7 but when you download you get 3.3) When we try to sync a project everything works fine and this screens shows as usually:

![2016-03-10_13-09-25](https://cloud.githubusercontent.com/assets/10044471/13675002/f56910d8-e6df-11e5-878a-23259c1e43fa.png)

But the project folder stays empty. We've tried creating a new project and moving artboards to a new file and then sync. But it still stays empty. This happened on multiple computers (all newest version of plugin in sketch) There's  no error message in avocode.. 

![2016-03-10_13-12-13](https://cloud.githubusercontent.com/assets/10044471/13675025/12ff1e26-e6e0-11e5-99d1-79dc6c1919d5.png)

**Comment by jakubzitny** [comment] 2016-03-15 15:23
Hi, thank you for the report. Sorry we're getting back to you this late.

First of all, I just want to clarify that version `2.7` is the version of Avocode release, while the Sketch plugin's current version is `3.3`.

You attached a screenshot of Sketch plugin version `3.1`, can you please make sure you are really using `3.3`? We looked into the database and all designs are correctly uploaded. Can you please confirm that you are still not able to see the designs at [manager.avocode.com](https://manager.avocode.com)? Can you see the designs in the Avocode app?

Please send the problematic link to team@avocode.com (the web manager link where you're having problem seeing uploaded designs) and we might be able to investigate it more.

**Comment by JohnnyBushy** [comment] 2016-03-18 17:28
Hello! Our team has the same troubles last weeks. It gets really annoying and breaks all our team collaboration processes, guys :(
We are using sketch 3.6, avocode sketch extension 3.3 and avocode app 2.6.0.

**Comment by bolekkerous** [comment] 2016-03-18 17:31
Hello Johhny!
Could you please hit us up at team@avocode.com?

Thanks!

**Comment by Katalonian** [comment] 2016-03-30 13:41
Have an exact same problem and that's very annoying. I already e-mailed support.

**Comment by Katalonian** [comment] 2016-03-30 14:05
Seems to be found a temporary solution. 

Create a new file and copy-paste artboards. The problem can be caused by groups/elements which are not inside the artboard.

**Comment by bolekkerous** [comment] 2016-03-30 14:28
This was a bug in older plugin version where the design was successfully synced to Avocode, however not assigned to a project. This bug is already fixed in the latest version of Sketch plugin. If you are using the latest version, it is probably happening because the design was initially synced with older version.

I've replied to your e-mail with a link which should fix the problem.

Please let us know if you encounter this problem with a brand new design, which was never synced to Avocode before. It shouldn't happen anymore though.

**Closed by bolekkerous** 2016-03-30 14:28 UTC
Labels: sketchPlugin, underReview
