### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by stevebrown** [avocode/avocode#393] opened 2015-08-19 23:20 UTC
IMPORTANT: Please try to describe how did it happen.
- Sync to Avocode
- Sync finished with an error in the web view
- Tried to resync to Avocode
- Error in Sketch
- Pressed send error to Avocode...
-----
Sketch Exporter 2.1.1 running in Sketch 3.3.3
```
Error: API: Could not confirm revision 15d1f3a61cea4921aa82f8d931ab3e6b
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/exporter.js:1:5975
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/async/lib/async.js:522:46
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/async/lib/async.js:251:17
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/async/lib/async.js:148:21
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/async/lib/async.js:248:21
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/async/lib/async.js:612:34
    at /Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/async/lib/async.js:513:25
    at Request._callback (/Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/api.js:1:1032)
    at self.callback (/Users/steve/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/node_modules/request/request.js:197:22)
    at Request.Even
```

**Comment by marekhrabe** [comment] 2015-10-23 14:29
Does this happen repeatedly for you? I'm asking because this problem might happen randomly on poor internet connection. We try try to make every http request three times and when it fails for the third time, we cannot continue further with sync. 

Try to sync the file again, it should go through. Let us know about that

**Comment by stevebrown** [comment] 2015-10-23 15:32
I haven't had any issues in "high bandwidth" environments. When I submitted the issue, I was working in our Costa Rica office, which has lower bandwidth at times. So the issue may be as you describe.

**Comment by rychlis** [comment] 2016-01-26 13:59
I am closing this as it was caused by networking issues and the networking errors handling was improved in newer version of Sketch Extension

**Closed by rychlis** 2016-01-26 13:59 UTC
Labels: sketchExtension, waitingForUser
