### ISSUE TITLE
Cannot sync Sketch file through Avocode plugin

### ISSUE THREAD

**Issue by danielgeri** [avocode/avocode#1180] opened 2016-10-31 22:13 UTC
I have a sketch file that is ~200mb. I continue getting a `failed to sync` message. Not exactly sure what is going on. Plugin version 3.9. Sketch version 40.3.

**Comment by danielgeri** [comment] 2016-10-31 22:14
![screen shot 2016-10-31 at 3 08 41 pm](https://cloud.githubusercontent.com/assets/720183/19873536/bd64fe44-9f7c-11e6-88dd-509e3a73a85f.png)

**Comment by bolekkerous** [comment] 2016-11-01 08:23
Hello!
Could you please send us the problematic file to team@avocode.com?

It may be connected to the size of the design, however we'd need to take a proper look at the design to tell you more about why it is happening.

Best regards,
Bolek, Avocode Team

**Comment by danielgeri** [comment] 2016-11-01 19:29
it seems to be working now. Perhaps a connection issue?

**Comment by bolekkerous** [comment] 2016-11-03 09:59
We're happy to hear it works now. It shouldn't be caused by network issues though.

We found out that this could be caused by having Sketch page named as blank, specifically " ". So make sure to name the page somehow.

If you ever encounter any issues, please create a new issue, I'm going to close this one.

**Closed by bolekkerous** 2016-11-03 09:59 UTC
Labels: needsMoreInfo, sketchPlugin
