### ISSUE TITLE
Can't access Avocode

### ISSUE THREAD

**Issue by Lorenacar** [avocode/avocode#1205] opened 2016-12-01 16:50 UTC
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.11.1`

As soon as I run Avocode I receive the message "Avocode has crashed. Please report..." The options are 'Report'/''Restart'/'Quit' and then it closes. Nothing happens. I tried uninstalling/installing and it's always the same. :(

**Comment by vojtatranta** [comment] 2016-12-12 09:56
What OS do you run?

It seems that you use Windows, right?

**Comment by vojtatranta** [comment] 2016-12-12 13:23
@Lorenacar that is pitty. You cannot event send us the stack trace by clicking "report", right?

**Comment by vojtatranta** [comment] 2016-12-21 12:58
This is a duplicate of #1220 I mention there a possible fix for this issue, could you please try it? I am closing this issue as a duplicate.

**Closed** 2016-12-21 12:58 UTC
Labels: bug, duplicate, windows

**Comment by vojtatranta** [comment] 2017-01-01 13:28
`2.12.1` should fix this, could you please try updating Avocode?
