### ISSUE TITLE
Dragging file to avocode window.

### ISSUE THREAD

**Issue by MichalCerny** [avocode/avocode#1145] opened 2016-10-04 11:41 UTC
---

App v. `2.11.0`
Source UID: 13132

```
Invariant Violation: Cannot call hover while not dragging.
    at Object.invariant [as default] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:116:25)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDrop (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:540:18)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:286:29)
```

**Comment by jakubzitny** [comment] 2016-10-04 13:08
Hi @MichalCerny, thanks for reporting this. We've already seen this problem, but we're not able to reproduce it. Can you give us more details on how did it happen? Did restarting the app help, were you able to upload a file afterwards?

I'm looking into it in more detail, I'll try reproducing it on Ubuntu.

**Comment by petrbrzek** [comment] 2016-10-08 15:57
@MichalCerny We are unable to reproduce this issue. Can you help us with it?

**Comment by MichalCerny** [comment] 2016-10-10 18:56
Sorry guys, didn't recieve message from github. It happend when I drag downloaded PSD from chrome bottom bar directly to avocode.

**Comment by MichalCerny** [comment] 2016-10-10 20:35
I reproduce it again and now know where is the problem. I'm using hazelapp and have rule => if there is any new PSD in Downloads folder move it to ~/Documents/PSD/; so when I download PSD in chrome, hazel moves it from downloads but in chrome download bar is still remains link to this file thats no longer exist.

**Reproduce**
Download PSD in chrome, keep it in downloads history, move/remove it from downloads folder than drag that file from chrome download history to avocode => 💥🔥

**Comment by jakubzitny** [comment] 2016-10-10 20:53
Awesome @MichalCerny, we love you ❤️.

I can reproduce it now, the fix should be ready for next release 😉.

**Comment by connor-bean** [comment] 2016-12-21 08:42
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-12-21 08:42 UTC
Labels: bug, onGitlab, willBeFixed
