### ISSUE TITLE
processing error

### ISSUE THREAD

**Issue by garnaga** [avocode/avocode#1317] opened 2017-03-10 13:37 UTC
![screen shot 2017-03-10 at 3 35 15 pm](https://cloud.githubusercontent.com/assets/9252457/23797196/47fa9222-05a7-11e7-8618-97b450ea9c1c.png)

**Comment by bolekkerous** [comment] 2017-03-10 13:48
Hey, @garnaga -
could you please provide a little bit more information about the issue?

Were you trying to upload Sketch or Photoshop design?

**Comment by garnaga** [comment] 2017-03-10 13:50
It was Photoshop design

**Comment by bolekkerous** [comment] 2017-03-10 13:51
I see. Could you please send us the problematic PSD file to team@avocode.com, so we can investigate properly?

**Comment by connor-bean** [comment] 2017-03-15 09:56
I see. Could you please send us the problematic PSD file to team@avocode.com, so we can investigate properly?

**Comment by bolekkerous** [comment] 2017-05-10 15:10
This problem is probably caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:10 UTC
Labels: duplicate
