### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jardicc** [avocode/avocode#927] opened 2016-06-16 12:16 UTC
IMPORTANT: Please try to describe how did it happen. I don't have time for description.

-----
App v.2.8.0
Source UID: 17594
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at RangeError (native)
    at e.exports.e.drawImage (file:///C:/Users/bereza/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:5280)
    at file:///C:/Users/bereza/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:3236
    at List.__iterate (C:\Users\bereza\AppData\Local\avocode\app-2.8.0\resources\app.asar\node_modules\immutable\dist\immutable.js:2208:13)
    at List.forEach (C:\Users\bereza\AppData\Local\avocode\app-2.8.0\resources\app.asar\node_modules\immutable\dist\immutable.js:4383:19)
    at e.exports.e.createSprites (file:///C:/Users/bereza/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:2834)
    at file:///C:/Users/bereza/AppData/Local/avocode/app-2.8.0/resources/app.asar/dist/avocode.min.js:24:3164
    at List.__iterate (C:\Users\bereza\AppData\Local\avocode\app-2.8.0\resources\app.asar\n
```

**Comment by jakubzitny** [comment] 2016-06-16 13:35
Hi @jardicc, thanks for reporting this. We already know about this problem under Windows and we will be releasing new 64-bit version of Avocode today or tomorrow. It should fix this problem.

This issue is duplicate of #915 so I will close this one and let's continue the discussion there.

**Closed by jakubzitny** 2016-06-16 13:35 UTC
Labels: 2.8.0, windows

**Comment by vojtatranta** [comment] 2016-06-16 22:28
Hi @jardicc here's link for 64bit version of Avocode that should fix those memory problems: https://manager.avocode.com/download/avocode-app/windows-x64/
