### ISSUE TITLE
Rotated or flipped objects bounding box is wrong

### ISSUE THREAD

**Issue by squadnik** [avocode/avocode#505] opened 2015-10-29 10:23 UTC
Hello,
I've noticed that Avocode exports assets (icons) with original position/rotate parameter despite the fact I've rotated or flipped object in Sketch.

Best, Tomek

**Comment by squadnik** [comment] 2015-11-10 12:28
Hi, any plans to fix this issue?

**Comment by marekhrabe** [comment] 2015-11-10 13:38
Hi, sorry to respond late. Can you please share us the file on team@avocode.com? It can contain just the one layer that makes problems.

**Comment by rychlis** [comment] 2015-11-16 12:46
Thanks for the file, we can reproduce the issue now, Improtant note: this only applies to the SVG export.

**Comment by connor-bean** [comment] 2016-06-14 15:16
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by umesh-velir** [comment] 2016-10-28 17:15
This is still happening. I am on 2.11.1.

Thanks in advance for looking into it!

**Comment by Stenvdb** [comment] 2017-01-30 12:40
@rychlis I'm also experiencing issues with rotated objects. Using latest version (2.12.4) See the screenshot in attachment, it is not showing the correct bounding box, this is what's getting exported as well (it crops part of the image and doesn't apply the rotation).

![screen shot 2017-01-30 at 13 34 59](https://cloud.githubusercontent.com/assets/362222/22423333/6c2c80c6-e6f1-11e6-887b-674dfd7d10f0.png)

**Comment by rychlis** [comment] 2017-01-30 12:56
OK I am reopening the issue. We fixed the export before but it seems there is a regression there now

**Comment by rychlis** [comment] 2017-01-30 16:24
@Stenvdb could you please send us a sketch file with that layer to team@avocode.com? The selection bounding box is wrong (will be fixed), but I was not able to reproduce the bad cropping issues when exporting any layer.

**Comment by Stenvdb** [comment] 2017-01-30 16:33
Hi, my colleague Inge will send it to you tomorow.

Cheers,
Sten

**Comment by Stenvdb** [comment] 2017-01-31 08:26
—
Inge Lemahieu
Designer @ Glue
www.glue.be

T: +32 (0)9 336 78 08

DOK Noord 4E 205
9000 Gent, België

**Comment by maximpetov** [comment] 2017-07-27 08:53
2.14.7
Wrong export into SVG for rotated object.

[Sketch file
](https://www.dropbox.com/s/oxkl84xjlgq0j2h/camera.sketch?dl=0)
[Exported SVG file](https://www.dropbox.com/s/vlffsbb5sskzx26/icon-camera.svg?dl=0)

**Comment by jakubzitny** [comment] 2017-07-27 09:18
Hi guys. Thanks for the file @maximpetov. Soon, we'll be releasing new rendering in Avocode with a bunch of new features, including fixed rotation. It should be ready in upcoming months, of course we'll update you about the release here.

**Comment by DenisKarakchiev** [comment] 2017-08-30 14:20
Have the same issue. Also the color is wrong. 
![image](https://user-images.githubusercontent.com/25384957/29877059-29165840-8da7-11e7-8039-847a8ec6584c.png) - how it suppose to look.
![image](https://user-images.githubusercontent.com/25384957/29877074-3c5fbfd6-8da7-11e7-8d85-6476adec71cf.png)
- How looks after export (svg).
Also after transform layer to symbol in sketch (which is helps sometimes), export is fails.

**Comment by bolekkerous** [comment] 2018-02-07 15:48
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team

**Closed by bolekkerous** 2018-02-07 15:48 UTC
Labels: bug, onGitlab, rendering, willBeFixed
