### ISSUE TITLE
Incorrect shortcut tooltip

### ISSUE THREAD

**Issue by iryan2** [avocode/avocode#212] opened 2015-04-21 04:05 UTC
If you hover over the hand tool, the tooltip indicates that the shortcut is 'S'. However, that's the shortcut for the splice tool. The shortcut for the hand tool is 'H', please correct the tooltip messaging.

Thanks!

**Comment by VPenkov** [comment] 2015-04-21 14:31
Already reported https://github.com/avocode/avocode/issues/180

**Comment by tomashanacek** [comment] 2015-04-27 14:36
Duplicate of #180

**Closed by tomashanacek** 2015-04-27 14:36 UTC
