### ISSUE TITLE
Incorrect open PSD

### ISSUE THREAD

**Issue by stdex** [avocode/avocode#876] opened 2016-05-20 14:50 UTC
![image](https://cloud.githubusercontent.com/assets/4608879/15431562/1f140c0c-1eb3-11e6-9b87-29260b492b6d.png)
![image](https://cloud.githubusercontent.com/assets/4608879/15431576/3a52b234-1eb3-11e6-9b58-cf1b44bca949.png)

**Comment by stdex** [comment] 2016-05-22 10:31
![image](https://cloud.githubusercontent.com/assets/4608879/15453513/502c7a4e-2021-11e6-825f-4ead6ba2d939.png)

When I open this PSD, Avocode are missing layers.
2.6.0 Windows/Ubuntu

**Comment by connor-bean** [comment] 2016-05-23 07:58
Hello -

Thanks for the screenshots and we're sorry for any inconvenience.

This bug usually happens with clipping mask layers that are hidden in the PSD file.

You can read more and watch the progress in this github issue:
https://github.com/avocode/avocode/issues/780

Let me know of any other questions.

Thanks,
Connor, Avocode Support

**Comment by stdex** [comment] 2016-05-26 17:20
[popups.zip](https://github.com/avocode/avocode/files/284933/popups.zip)
Attach PSD.

**Comment by bolekkerous** [comment] 2017-02-13 12:56
This is a duplicate of #780 - I'll close this issue and you can follow the progress there.

**Closed by bolekkerous** 2017-02-13 12:56 UTC
Labels: bug, windows
