### ISSUE TITLE
Seeing only white screens

### ISSUE THREAD

**Issue by artsheeps** [avocode/avocode#981] opened 2016-07-20 12:30 UTC
<img width="1679" alt="screen shot 2016-07-20 at 14 28 27" src="https://cloud.githubusercontent.com/assets/7701850/16986346/479ec164-4e86-11e6-9be4-53acf82ebe9e.png">

The layers are all there and also the code seems fine, but I only get displayed white screens in the preview.

**Comment by whoiskjl** [comment] 2016-07-20 17:57
I'm getting the same problem

**Comment by whoiskjl** [comment] 2016-07-20 18:04
All of the previous sketches are working fine and showing up; I asked one of the graphic designers to generate some test images, none of them are showing up

**Comment by b-s-v** [comment] 2016-07-20 18:09
+1

**Comment by bolekkerous** [comment] 2016-07-20 18:14
Thanks for the reports!

It looks like it's caused by the new Sketch update. We're already looking into it and we'll be hopefully soon releasing fixed plugin update.

For the time being, older versions of Sketch should work just fine.

**Comment by miguelnavarro89** [comment] 2016-07-20 18:40
Hello, it's the same in my case, and it is due to Avocode does not recognise Sketch's symbol properly when they have overrides.

Hope this will be fixed soon!

**Comment by bolekkerous** [comment] 2016-07-20 19:05
We've just released Sketch plugin 3.8 update, which supports Sketch 39.

The plugin should auto-update, otherwise you can download it here:
https://github.com/avocode/avocode/blob/master/sketch-plugin.md

I'm going to close this issue, if you have any problems with the new version, feel free to create a new issue for it.

Hope it helps!
Best regards,
Bolek, Avocode Team

**Closed by bolekkerous** 2016-07-20 19:05 UTC
Labels: bug, onGitlab, sketchPlugin
