### ISSUE TITLE
problem with avocode

### ISSUE THREAD

**Issue by telpisgeo** [avocode/avocode#576] opened 2015-12-22 16:09 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (A90F78D6-3598-4C47-AA0F-396BB7DE35BA)
    at /Users/telpis/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/telpis/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by vojtatranta** [comment] 2015-12-29 12:22
Thank you for your report.
I see that you are using older version of Avocode Sketch Extension, you may try to use version 3B, more info here: https://github.com/avocode/avocode/issues/568

**Comment by rychlis** [comment] 2016-01-26 12:56
As this is a duplicate of #513 I am closing this one. [Check out Sketch extension beta](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md) which is not affected by this issue

**Closed by rychlis** 2016-01-26 12:56 UTC
Labels: bug, sketchExtension
