### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by akai2211** [avocode/avocode#2089] opened 2018-07-13 10:46 UTC
Settings "App prefereances->Code->Change code setings of:" are not saved.
---
* **Version**: 3.2.0-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 372106
---
```
No stack trace available
```

**Comment by jakubzitny** [comment] 2018-07-17 08:35
Hi @g-laptev, thanks for reporting this problem. We'll look into it and get back to you.

**Comment by bolekkerous** [comment] 2018-07-17 08:47
Hey @g-laptev ,
a question - what exactly were you trying to change in the app preferences? Did you want to set up a default code language for your project? 

If so, it is not the right place to change that - App Preferences only modify how the language template behaves ONCE it is already set to be used in the project.

If you want to change the default language of a project, just open your project settings and there you can go into advanced settings and change the default language.

**Comment by jakubzitny** [comment] 2018-07-20 12:38
Hey @g-laptev ,
a question - what exactly were you trying to change in the app preferences? Did you want to set up a default code language for your project?

If so, it is not the right place to change that - App Preferences only modify how the language template behaves ONCE it is already set to be used in the project.

If you want to change the default language of a project, just open your project settings and there you can go into advanced settings and change the default language.

**Comment by akai2211** [comment] 2018-07-20 13:40
css to sass by default in all projects

**Comment by bolekkerous** [comment] 2018-07-20 13:45
I see, well it is not possible to set up a default language for all projects at the moment, but it is possible to set it up on the project level while you are creating the project (or in your project settings).

The language settings in App Preferences are specifying how the language behaves, but it does not set it to default for the whole app.

I'll close this issue then since it's not a bug, and we'll try to figure out a better way so it is not confusing as such.

**Closed as completed by bolekkerous** 2018-07-20 13:45 UTC
Labels: underReview, waitingForUser

**Comment by akai2211** [comment] 2018-07-20 13:54
So I can change px to rem and hex to rgba by default and css to sass does not. 
Somewhere here, logic is lost.

**Comment by bolekkerous** [comment] 2018-07-20 14:00
You can change CSS to Sass for Web platform projects and then any new project created with Web will be set as default to Sass as seen on the screenshot below. Does that solve what you were trying to do? 

<img width="535" alt="screenshot 2018-07-20 15 59 29" src="https://user-images.githubusercontent.com/16084852/43006452-0c2f66ca-8c36-11e8-9c64-c45c5618611e.png">

**Comment by akai2211** [comment] 2018-07-20 14:02
yes, thanks.
