### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hornabar** [avocode/avocode#1273] opened 2017-01-30 13:18 UTC
IMPORTANT: Please try to describe how did it happen.
While switching between tabs 
-----
App v. `2.12.4`
Avocode UID: 58320
```
Error: No such module: atom_common_app
    at Error (native)
    at process.atomBinding (/opt/Avocode-linux-x64/resources/electron.asar/common/init.js:10:14)
    at Object.<anonymous> (/opt/Avocode-linux-x64/resources/electron.asar/browser/api/app.js:3:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.get (/opt/Avocode-linux-x64/resources/electron.asar/browser/api/exports/electron.js:11:14)
    at stringify (/opt/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/node_modules/json-stringify-safe/stringify.js:5:15)
    at Object._makeRequest (/opt/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:1495:22)
    at Object._sendProcessedPayload (/opt/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:1431:56)
    at Object._send (/opt/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:1388:14)
    at Object.captureMessage (/opt/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:406:14)
    at Object.captureException (/opt/Avocode-linux-x64/resources/app.asar/node_modules/raven-js/src/raven.js:329:25)
    at e.captureException (file:///opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:30:28213)
    at file:///opt/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:41:4134
```

**Comment by vojtatranta** [comment] 2017-01-31 16:35
this is duplicate of #1244 it will be tracked there

**Closed by vojtatranta** 2017-01-31 16:35 UTC
Labels: duplicate
