### ISSUE TITLE
If a folder has effects on it - every layer will inherit those effects

### ISSUE THREAD

**Issue by Slavitski** [avocode/avocode#433] opened 2015-09-10 13:56 UTC
If a folder in PSD has style effects on it (Border, shadow, etc.) the Avocode app will give those effects to every layer within that folder.

For example, design:
![design](https://cloud.githubusercontent.com/assets/9825263/9790091/c8459456-57dc-11e5-96ea-331413f48594.png)

Avocode:
![avocode](https://cloud.githubusercontent.com/assets/9825263/9790099/ce9f15e8-57dc-11e5-985a-276a063ac720.png)

**Comment by rychlis** [comment] 2015-10-23 14:50
Thanks for the report, this is duplicate of #227 

Unfortunately this needs some more work to render effects but we are getting there

**Closed by rychlis** 2015-10-23 14:50 UTC
