### ISSUE TITLE
Shit app

### ISSUE THREAD

**Issue by dominiksefl** [avocode/avocode#545] opened 2015-11-29 20:31 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.2
```
Error: Sketchtool failed to export pages (D175E28A-669E-4010-BF0A-D5D71ED3A907)
    at /Users/dominiksefl/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/dominiksefl/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment] 2015-11-30 21:06
Thanks for the report. Would you be willing to share the file in question with us at team@avocode.com? It would help us figure out what exactly was the issue in this case.

**Comment by rychlis** [comment] 2015-12-02 13:35
Hi,

it means that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround. So far we've been able to reproduce this problem with documents that contained:
- huge canvas background layer used to emulate a different canvas background color 
- huge grid layers used to create a custom grid
- generally any huge layer, huge in this context usually means >10000px in width or height

Removing such layers would make the Sketchtool work.

We are also working on a new major release of Sketch extension for some time. It fixes a lot of bugs and doesn't use Sketchtool anymore so it does not have this problem. There is a public beta you can try out, see this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

I am closing this issue as it's a duplicate of https://github.com/avocode/avocode/issues/513

**Closed by rychlis** 2015-12-02 13:35 UTC

**Comment by dominiksefl** [comment] 2015-12-02 13:45
Hi,
Synchronization between Sketch and Avocode is terrible. I do not get what I pay for, if it is not working. I need a reliable application to work.

PS: Where are you from? Who do I write?

Thank you for understanding.

**Comment by rychlis** [comment] 2015-12-02 13:59
Even with the new beta extension? Could you try it [here](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md) please?

Me and @jankuca are both members of the Avocode team. You can give us an email in Czech to team@avocode.com if you want
