### ISSUE TITLE
The mounting areas are transparent in avocode

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#1634] opened 2017-09-19 07:12 UTC
* **Version**: 2.15.3
* **Web/Desktop**:  Desktop / win10

The mounting areas are transparent in avocode but in the photoshop of the white background

Demo bug:
![image](https://user-images.githubusercontent.com/4661784/30579821-e7be658c-9d22-11e7-8e65-c424d9a649f2.png)
Preview:
![image](https://user-images.githubusercontent.com/4661784/30579832-fb244934-9d22-11e7-9cbd-9d7dbceceb5e.png)
pub. link: https://app.avocode.com/view/f567398367d64cb9a4c691c72b5c90bb/13924899/comments/

**Comment by bolekkerous** [comment] 2017-09-19 11:03
Hey - 
this looks like an issue caused by using Photoshop artboards in the PSD. Sorry for the confusion - we actually do not support Photoshop Artboards at the moment.

We would suggest you (or your designer) to either ungroup the artboard that the design is wrapped in or make a few smaller files containing just one of the artboards (ungrouped though) if there is more artboards in the design. Check the image below to see how to export multiple artboards into separate files:
​
![Photoshop](https://downloads.intercomcdn.com/i/o/31982669/7979f913eee7cc51165db8dc/export_artboards.png)

Make sure to NOT preserve artboards in the last step of the process.
​
If you want us to support Photoshop Artboards, please upvote it on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

**Comment by jakubzitny** [comment] 2018-02-07 11:41
Photoshop artboards are coming in Avocode 2.19.0, closing wrt #374.

**Closed by jakubzitny** 2018-02-07 11:41 UTC
