### ISSUE TITLE
Vector Smart Objects (from Illustrator) don't export as actual vector.

### ISSUE THREAD

**Issue by timkelty** [avocode/avocode#112] opened 2015-01-30 16:04 UTC
They will export as SVG, but the contents are just a base64 encoded png inside.

This was the main feature I was hoping for switching from Adobe Extract.
Seems like this is very common for designers using vector from AI.

Would love to see this implemented!

**Comment by timkelty** [comment] 2015-01-30 16:12
Also, (AFAIK) there isn't a good way to convert those to PS vector paths, so the whole process is really cumbersome.

**Comment by tomashanacek** [comment] 2015-02-01 09:17
Duplicate of #81, moved to user voice https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support

**Closed by tomashanacek** 2015-02-01 09:17 UTC
Labels: duplicate, enhancement
