### ISSUE TITLE
The shadow of a parent group is applied to child group

### ISSUE THREAD

**Issue by rodnem** [avocode/avocode#768] opened 2016-02-26 16:58 UTC
It seems that the #433 is not really solved.
![shadow-test](https://cloud.githubusercontent.com/assets/6350513/13359021/66ea3346-dcb2-11e5-9ea1-3d6376542281.png)

I don't know if other effects do the same

**Comment by rodnem** [comment] 2016-02-26 17:00
If have :
Sketch 3.5.2
Plugin beta Avocode Sync 3.2
Avocode 2.6 mac

**Comment by rychlis** [comment] 2016-03-01 13:10
#433 was not solved, only marked as duplicate of #227

This is also a duplicate of #227 so I am closing it, we're now working on rendering improvements that should fix the issue. I'll post and update in #227

**Closed by rychlis** 2016-03-01 13:10 UTC

**Comment by rychlis** [comment] 2016-03-01 13:12
I've borrowed your screnshot for the #227 issue, thanks for the report :)
