### ISSUE TITLE
Error upload design

### ISSUE THREAD

**Issue by pulpaluk** [avocode/avocode#1474] opened 2017-06-12 07:49 UTC
* **Version**: 2.14.2

* **Web/Desktop**: Desktop

* **Platform**: Windows 7 Professional, 64bit, Service Pack 1

Hi!
I need help with upload design. When I upload PSD so show: "This design failed processing and cannot be opened. You can try to upload a new revision or delete the design."

What can be cause, please?

Thank you,
Lukáš Půlpán

**Comment by bolekkerous** [comment] 2017-06-12 13:47
Hey, @pulpaluk  -
this looks like a problem caused by using huge bitmap images in the design (usually stock images with huge resolutions) or also by large complexity of the design. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or through the in-app chat.

Since it's a duplicate issue of #1374, I'll close this one.

Best regards,
Bolek, Avocode Team

**Closed by bolekkerous** 2017-06-12 13:47 UTC
Labels: duplicate
