### ISSUE TITLE
Serious issues with Photoshop files

### ISSUE THREAD

**Issue by Eugene-Musika-cpamatica** [avocode/avocode#1308] opened 2017-03-05 15:41 UTC
When I download PS templates to Avocode they looks different. Many times layers with transparency was looking either absolutely transparent or absolutely opaque. Also have some other strange issues. Even can't describe the problem they just looks broken in Avocode but they are OK in Photoshop.
Examples:
1. How it should be:
![image](https://cloud.githubusercontent.com/assets/25586635/23588829/dd0fb8b8-01cb-11e7-9320-8df0aa6135c8.png)
How it is in Avocode: 
![image](https://cloud.githubusercontent.com/assets/25586635/23588841/0ee7b43a-01cc-11e7-82c1-ce36d5b31424.png)

2. How it should be: 
![image](https://cloud.githubusercontent.com/assets/25586635/23588849/4501b070-01cc-11e7-874c-b0994a2fc662.png)
How it is in Avocode: 
![image](https://cloud.githubusercontent.com/assets/25586635/23588860/660d40b8-01cc-11e7-9841-19837cbf41ed.png)

Some links to those PS files I've pinned to this issue. Hoping for quick answer.
[File 1](https://manager.avocode.com/view/2e2dc7f7a3e443c0953bb71be598248c/8532899/comments/), [File 2](https://manager.avocode.com/view/2d3c63c3969a45c882ea79fbfff08892/8530959/comments/), [File 3](https://manager.avocode.com/view/87c96a20b09c43d0b620f300cd8812c3/8524949/comments/)

**Comment by bolekkerous** [comment] 2017-03-06 10:42
Hey, could you please send us the problematic PSD's, so we can investigate properly? You can send it to our e-mail team@avocode.com

I'm afraid we're not able to tell what's wrong just from the links.

Thanks and sorry for the inconvenience.

**Comment by Eugene-Musika-cpamatica** [comment] 2017-03-06 11:08
Have sent few of those files

**Comment by bolekkerous** [comment] 2017-03-06 13:36
Hey, Eugene -
thanks for the files. 

As for the first file, the problem there is caused by using Photoshop artboards in the design. Unfortunately, we do not support Photoshop artboards yet, so using it causes that. If you ungroup the unboard and reupload the file, there should be no issues.

If you want us to support Photoshop artboards, please upvote it here:
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

As for the second file you've sent us - that looks like a bug - when you upload the file through Photoshop, it's displayed incorrectly. However, if you upload the file by drag and dropping it into Avocode, it works correctly.

I'll forward this bug to our dev team, so they can fix it - in the meanwhile, please upload the file by drag and dropping it into Avocode.

**Comment by bolekkerous** [comment] 2018-02-07 11:52
Artboards and everything related to them + the other issue should be both fixed with the 2.19 update which should be released shortly. The second issue is fixed if you upload it directly through drag and drop. The PS plugin will be soon replaced by a new Photoshop plugin that uses the same upload process as drag and dropping.

Please let us know if you encounter any problems even after 2.19.

**Closed by bolekkerous** 2018-02-07 11:52 UTC
Labels: bug, onGitlab, photoshopPlugin
