### ISSUE TITLE
Can't save the slice as a jpg

### ISSUE THREAD

**Issue by deaddale** [avocode/avocode#565] opened 2015-12-13 09:13 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 86129
```
TypeError: Cannot read property 'bounds' of undefined
  at Object.getBoundsForLayers (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/document.js:1:724)
  at exportRule (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/export.js:1:5697)
  at t._instantExport (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11420)
  at t._register (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:12487)
  at Object.ID_15 (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:459)
  at o._invokeCallback (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:198:24)
  at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:174:14)
  at o.handleViewAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at o.module.exports.instantExport [as onExport] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/actions/export.js:1:1651)
  at o.module.exports.o.onConfirm (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4563)
  at o.module.exports.o.onSave (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:4067)
  at o.onSave (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/instant-export-dialog.js:1:239)
  at HTMLButtonElement.<anonymous> (/Applications/Avocode.app/Contents/Resourc
```

**Comment by jankuca** [comment] 2015-12-13 23:37
Thanks for the report! We are going to take a look at this, I added the issue to our internal ticket system.

It is a duplicate of #564 which is why I'm going to close this report; you can follow the status there, thanks again.

**Closed by jankuca** 2015-12-13 23:37 UTC
