### ISSUE TITLE
Avacode has gone bad

### ISSUE THREAD

**Issue by mypum** [avocode/avocode#330] opened 2015-07-02 08:03 UTC
Describe your problem here…

-----

```
TypeError: boolean is not a function
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:11098
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/export.js:1:4967
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by rychlis** [comment] 2015-07-08 15:10
When did this error happen? Can you reproduce the issoe on the latest version 2.3.0?

**Comment by rychlis** [comment] 2015-07-29 10:14
I'm closing this issue as you didn't provide any information and we were not able to reproduce the problem. I will of course re-open this if you respond

**Closed by rychlis** 2015-07-29 10:14 UTC
