### ISSUE TITLE
Error when opening PSD

### ISSUE THREAD

**Issue by joska** [avocode/avocode#256] opened 2015-05-18 13:26 UTC
Describe your problem here…

-----

```
TypeError: Cannot read property 'originalBounds' of undefined
  at new b (/Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/document.js:4:159)
  at /Applications/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:29:398
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

**Comment by petrbrzek** [comment] 2015-05-19 20:08
Duplicate of #231. This is going to be fixed in upcoming release.

**Closed by petrbrzek** 2015-05-19 20:08 UTC
