### ISSUE TITLE
bug in avocode

### ISSUE THREAD

**Issue by agalar** [avocode/avocode#1204] opened 2016-11-29 11:33 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 83673
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Users/mac/Desktop/Avocode.app/Contents/Resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.findDOMNode (/Users/mac/Desktop/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/findDOMNode.js:45:205)
    at t.a._focusElement (file:///Users/mac/Desktop/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:8:25008)
    at Immediate.<anonymous> (file:///Users/mac/Desktop/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:8:26731)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by vojtatranta** [comment] 2016-12-09 12:16
This is a duplicate of #1207  and it will be tracked there.

**Closed by vojtatranta** 2016-12-09 12:16 UTC
