### ISSUE TITLE
Avocode works a bit buggy today )

### ISSUE THREAD

**Issue by ekurennyy** [avocode/avocode#1023] opened 2016-08-06 11:19 UTC
IMPORTANT: Please try to describe how did it happen.
I just opened one view from project and tried to export group of layers (image) and every time I had the error.

Hm... now I see that whole program (avacode) works buggy. Closing tabs gives me additional left panel at the middle of the screen... yay! Looks interesting... )

-----
App v.2.9.1
Source UID: 58396
```
TypeError: Cannot read property 'componentWillReceiveProps' of null
    at ReactCompositeComponentWrapper.updateComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:457:15)
    at ReactCompositeComponentWrapper.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.receiveComponent (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent._updateChildren (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactMultiChild.js:351:31)
    at ReactDOMCompone
```

**Comment by ekurennyy** [comment] 2016-08-06 11:20
All is good now (after restarting the app). Will be in touch.

**Comment by vojtatranta** [comment] 2016-08-08 13:05
@ekurennyy Hi,
sorry for that. This is hard for us to debug. We cannot reproduce it. Seems you have not done any unusual steps in the app, right?

**Comment by jakubzitny** [comment] 2016-08-22 11:09
Hi @ekurennyy, thanks again for the report. I'll close this issue for now. It is related to bug that's already mentioned in #1058. We're working on a fix.

**Closed by jakubzitny** 2016-08-22 11:09 UTC
Labels: bug
