### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by pablobarcia** [avocode/avocode#472] opened 2015-10-14 12:58 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.3.3
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/pablobarcia/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by marekhrabe** [comment] 2015-10-23 12:36
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will notice you when the new version is released.

**Comment by urikelman** [comment] 2015-10-26 21:29
Anyway to release a hotfix today just to address the export issue? I have developers waiting for files and need to be uploaded today.

**Comment by marekhrabe** [comment] 2015-10-26 23:15
Hi @urikelman, hotfix has just been released. Please try it: https://manager.avocode.com/downloads/

**Comment by urikelman** [comment] 2015-10-26 23:18
Thank you. Vu was helping be out directly. Thank you so much to you and your team for such a quick turnaround. Amazing!
____

Uri Kelman
Director, User Experience & Design | Swagbucks

o. 310-362-7900 | m. 661-713-9387 |
uri@swagbucks.com
100 N Sepulveda Blvd., 8th Floor, El Segundo, CA 90245
www.swagbucks.com <http://www.swagbucks.com/team/kovi.k>/refer/urikelman

**Comment by liodub** [comment] 2015-10-27 10:11
sketch 3.4 and avocode sketch plug in 212
Dowloaded the fix, clean install of the plugin, still getting the crash wile trying to sync

problem appears to be with font:
single art board with just a shape on it seems to works. 
single art board with text, sketch crashes.

Please advise. Lost work time narrowing down the issue. Im under lot if pressure to deliverer those design to the dev team. Thanks in advance for your help.

**Comment by rychlis** [comment] 2015-10-27 14:37
There was an issue in 2.1.2 that would result in upload of bad artboards data (which cannot be opened in the app sequentially) which is now fixed with 2.1.3. You will unfortunately need to resync such designs.

@liodub does the Sketch app completely close or just the extension? That's probably a different issue, please report it as new issue or contact us at team@avocode.com with the sketch file (we will try to sync it for you as fast as possible)

**Closed by rychlis** 2015-10-27 14:37 UTC
Labels: bug, sketchExtension

**Comment by rychlis** [comment] 2015-10-27 14:52
@liodub I've created a new issue for the crashing problem #497 . We think we can reproduce that problem and it's indeed caused by some types of text layer. We're investigating it further, thanks for your report

**Comment by pierrelucgagnon** [comment] 2015-10-27 16:27
Hi, having the same issue here. Sketch 3.4 and plugin 2.1.3. Sketch is crashing when trying to sync to Avocode. I've tried to go back to sketch 3.3.3 t sync but I can't open my document anymore in this version (with latest changes i've done) because it's saved in new version. Now i'm stuck, developers are waiting for design, tight schedule, hope you will find a fix very fast. Registered user.

**Comment by rychlis** [comment] 2015-10-27 16:29
@pierrelucgagnon please follow the issue #497, this issue is a different one. You have these options at the moment:
1. Remove all layers with text lists and sync with Sketch 3.4 (probably best if you don't have much layers of this type)
2. Use Sketch 3.3.3 with the latest version of extension (not a possibility for you i guess :( )
3. Wait for us to release a fixed version of the extension which should work fine even with Sketch 3.4, hopefully this will be released soon

**Comment by pierrelucgagnon** [comment] 2015-10-27 16:30
There is no text list in my document. I guess I'm stuck waiting for update now

**Comment by liodub** [comment] 2015-10-27 16:45
Aside from the bullet point issue it look from here that some fonts make
the sync crash while some other don't.

I've made a quick dummy file with single page and one artboard with a text
box. Text in Museo Sans, sync ok. Change the font to Helvetica light and
crash again.

Change the text box to a bullet point list and then it will crash, whether
its in Helvetica or Museo.

The only way around so far seems to find a font that doesn't make the
upload crash and avoid bullet point formatting. Painful.

**Comment by pierrelucgagnon** [comment] 2015-10-27 16:50
@rychlis no text list in my document, is this the good issue? I can provide crash infos if required

**Comment by liodub** [comment] 2015-10-27 16:55
i think this has issue has been closed and moved to another one:
https://github.com/avocode/avocode/issues/497

Try a different font, it worked for me.

**Comment by pierrelucgagnon** [comment] 2015-10-27 17:00
my document contain 31 artworks, been working on this document for several month.. I'm using a specific font that matches my client's branding. A change of font is not an option here. I'd rather find another software that actually work.

**Comment by pierrelucgagnon** [comment] 2015-10-27 17:02
lesson learned, should not update software when working on a tight schedule ;)

**Comment by liodub** [comment] 2015-10-27 17:10
I feel you pain, i was exactly in the same dead end.
Luckily i had a backup of the sketch file so I've been able to revert to
sketch 3.3.3 and with the latest version plugin it worked. Font and bullet
list no problem.

any recent copy of your file on dropbox, time machine, wetransfer, mail
attachement or something like that? Anyway good luck...

**Comment by pierrelucgagnon** [comment] 2015-10-27 17:18
thanks for your help, I'm currently looking to an option in the finder to locate older version of this document (see https://medium.com/sketch-app-sources/how-to-recover-50-go-or-even-more-by-deleting-sketch-caches-files-e5829dba20e1#.o82oip3vy)

Otherwise I've tried to copy/paste from sketch 3.4 to sketch 3.3.3, it didn't work as the older version think i'm pasting PDF element. Tried SVG as well.. no luck. Last option will be to recreate everything since i've moved to Sketch 3.4, using both software to locate elements and position in every artboard. Or ask my developper to use png file and try their best to match the styles, until they fix this problem.

**Comment by liodub** [comment] 2015-10-27 18:18
wow! thanks for pointing my way to this article.
i was going nuts with "start disk being full" thing. 390GB revision folder!
Made my day, thanks ;) Good luck digging in the versions.. L

**Comment by pierrelucgagnon** [comment] 2015-10-27 19:20
Finally figured to recreate the work I lost this morning. Now having a "Arguments to path.resolve must be strings" error when trying to sync. Anyone from Avocode reading this? I'm about to cancel my membership.. such a waste of time today to make this work

**Comment by rychlis** [comment] 2015-10-27 19:58
@pierrelucgagnon is it possible for you to share the sketch document that failed on Sketch 3.3.3 with 2.1.3 plugin installed with us at team@avocode.com? We will try to sync it for you and fix the problem. I am very sorry for the issues.

The problem with "Arguments to path.resolve must be strings" error is that it can have multiple causes and it was most probably caused by a different thing then the original report by pablo. It would be great if you could report the issue with full stack trace when it happens again to github using the report button, thanks!
