### ISSUE TITLE
Unexpected Error after Sync is complete.  File is attached.

### ISSUE THREAD

**Issue by mochabcha** [avocode/avocode#563] opened 2015-12-11 21:46 UTC
IMPORTANT: Please try to describe how did it happen.

I clicked Sync to Avocode and after it was finished it gave me an unexpected error.  I really have no clue how it was generated.  Apparently something in the file is causing an error.  The whole process seems to have completed, then the error is triggered.

Here's the file.  
https://drive.google.com/file/d/0B_x0w7hahgJHZHNQTlpfWGJ4Wnc/view?usp=sharing

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (6F41469E-CDB0-4F15-B0D4-B6CC6E982532)
    at /Users/mochabcha/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/mochabcha/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by mochabcha** [comment] 2015-12-11 22:01
and please don't recommend the newest beta Sketch Plugin that doesn't allow you to select which project you're syncing to.  Vojtatranta already suggested that and I have 13 projects in my account.  I have to be able to select the project I want.

**Comment by mochabcha** [comment] 2015-12-11 22:09
I deleted the tokens and reinstalled the plugin and it has successfully gone through.  I will be glad though when uploading via the manager starts working.  These plugin errors are an adventure.

**Comment by jankuca** [comment] 2015-12-13 23:45
Hello, good to hear it finally started working; sorry for the inconvenience. We are trying to do our best with the new Sketch plugin to provide better experience and will take your feedback into account.

**Comment by rychlis** [comment] 2016-01-26 12:56
As this is a duplicate of #513 I am closing this one. [Check out Sketch extension beta](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md) which is not affected by this issue

**Closed by rychlis** 2016-01-26 12:56 UTC
Labels: sketchExtension, sketchExtensionBeta
