### ISSUE TITLE
Design open crash for large resolution designs on Windows

### ISSUE THREAD

**Issue by glivera** [avocode/avocode#143] opened 2015-02-17 14:32 UTC
When this layer is present in the layout
https://www.dropbox.com/s/mrzeemacdbmz7qv/test.psd?dl=0
happening infinite loading
http://screencast.com/t/7KM7Vzra7zjw

**Comment by rychlis** [comment] 2015-02-20 11:18
thanks for the report. We've released Avocode 1.1.0 today with improved document loading, it should fix the issue or at least show where does it get stuck in the loading process.

Let me know if it loads fine for you in the new release, there was no issue with this psd at least for me.

**Comment by glivera** [comment] 2015-02-20 13:10
http://screencast.com/t/KVgKivp98CZf
https://www.dropbox.com/s/1k9i2nptpds87s3/forex_strij.psd?dl=0

-- 
Best Regards,
Andrey Boyko

Kharkov, Ukraine
E-mail: work@glivera.com
Skype: glivera_28
Tel: +380675748294
Portfolio:
https://www.odesk.com/o/profiles/users/_~018e9133831d393d6d/
<https://www.odesk.com/users/html5-xhtml-css-css3-Developer-Smarty-Zend-Framework-Ruby-Rails_~~3857c463d2c2df53?sid=49002&tot=1&pos=0>
http://www.weblancer.net/users/glivera/portfolio/

HTML5 / XHTML layout of any complexity

2015-02-20 13:18 GMT+02:00 Tomáš Rychlik <notifications@github.com>:

**Comment by rychlis** [comment] 2015-02-20 14:08
We can reproduce the crash for this PSD, on Windows only. It might be a memory issue because the design is really large. We'll investigate this further, thanks for the report

**Comment by rychlis** [comment] 2015-02-20 14:56
Crash happens on Avocode 1.0.0 as well so it's not a 1.1.0-only regression. Does avocode crash on any other designs of yours?

**Comment by pospi** [comment] 2015-03-16 00:15
We get the same sorts of crashes as these when dealing with large Sketch files with multiple pages and artboards. The crash seems to be related to the overall size of the file rather than the complexity of individual pages within the document - breaking the pages of those designs up into separate files is often a good workaround for the problem.

**Comment by rychlis** [comment] 2016-06-14 21:51
We just created a x64 build of Avocode which should fix this issue. You can try it out: https://media.avocode.com/download/avocode-app/2.8.0/avocode-app-windows-x64-2.8.0.exe

Note that this requires a 64bit Windows. We will soon make this the default version of Avocode

**Comment by rychlis** [comment] 2016-07-01 08:20
x64 is the default windows version since 2.8.1, finally closing the issue!

**Closed by rychlis** 2016-07-01 08:20 UTC
Labels: bug, windows
