### ISSUE TITLE
Unable to select text with cursor in 2.0.0

### ISSUE THREAD

**Issue by stevebrown** [avocode/avocode#204] opened 2015-04-16 14:45 UTC
Can select some text in the layout view, but other text will not select. I can select the text in the layer list.
In the referenced image, my cursor is trying to select the text "Awards" below the selected icon but the icon is always selected and not the text. Only the text "Home" is directly selectable in this layout. All other text must be selected in the layer list.

![screen](https://cloud.githubusercontent.com/assets/403014/7183433/ab0fb6e6-e414-11e4-8071-d58c7dbb06f3.png)

**Comment by petrbrzek** [comment] 2015-04-16 21:35
Weird. Is that happening in all designs?

**Comment by stevebrown** [comment] 2015-04-17 00:49
It is happening in most designs. It seems like geometry is usually selectable.  Text is mostly not directly selectable.

You might be able to see the designs and any issues by looking at the Veux Labs account.

**Comment by stevebrown** [comment] 2015-04-17 14:04
One thing I could do is send the Sketch file that is causing the issue shown in the screen shot so you can if you can reproduce the issue.

**Comment by petrbrzek** [comment] 2015-04-17 14:04
Awesome, send it to petr@avocode.com. Thanks

**Comment by petrbrzek** [comment] 2015-04-28 20:14
Should be fixed now. Try the new version 2.1.0 and let us know. 

Reopen, if the problem is still occurrs.

**Closed by petrbrzek** 2015-04-28 20:14 UTC
Labels: bug, underReview
