### ISSUE TITLE
Problem with layers

### ISSUE THREAD

**Issue by polkom21** [avocode/avocode#2152] opened 2018-09-18 15:42 UTC
I have a problem with layers. If I have a groups all layers inside group I don't know what layer is where

![image](https://user-images.githubusercontent.com/3143164/45699179-d6880a00-bb69-11e8-8830-2adce701bd6c.png)

When I select this layers and have export I receive bad image. 

![image](https://user-images.githubusercontent.com/3143164/45699288-fae3e680-bb69-11e8-9f44-8d7d14d2c0cb.png)

In export from photoshop all it's ok.

---
* **Version**: 3.5.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 414143
---
```
No stack trace available
```

**Comment by jakubzitny** [comment] 2018-09-21 06:05
Hi, thanks for reporting this. Regarding the layer padding, we'll investigate it. For the export, you can select the layers by dragging mouse on the design and the layers should select accordingly. The export should then be ok.

Can you please send us a link to your design so I can check it?

**Comment by jakubzitny** [comment] 2018-09-22 23:36
Hi, thanks for reporting this. Regarding the layer padding, we'll investigate it. For the export, you can select the layers by dragging mouse on the design and the layers should select accordingly. The export should then be ok.

Can you please send us a link to your design so I can check it?

**Comment by jankuca** [comment] 2018-09-24 13:45
The "padding" is caused by a limit in the layer list which does not indent by more than 4 levels. I understand your perception that this is a bug – we should reconsider this limit as it is not so uncommon to have 4+ levels of layer nesting in larger designs.

Regarding the export result. Is it possible that there are hidden layers within the exported group layer? We've ran into an issue of hidden nested layers being incorrectly included in previews and exports and are working on a fix for this. As a workaround, you can select the individual layers you want included in the export.

**Closed as completed** 2018-11-30 13:01 UTC
Labels: waitingForUser
