### ISSUE TITLE
Unexpected token var when opening projects

### ISSUE THREAD

**Issue by chapati23** [avocode/avocode#1616] opened 2017-09-12 17:08 UTC
* **Version**: 2.15.1-we46b290

* **Web/Desktop**: Web

* **Platform**: macosx 10.12.6
* **Browser**: chrome 60.0.3112.113

* **Avocode UID**: 181867
---

```
SyntaxError: Unexpected token var
```

**Comment by jakubzitny** [comment] 2017-09-13 08:00
Hi @chapati23, thanks for reporting this. We already know about it and we'll try to fix it as soon as possible 😉 Any further info on this would help - how many times did it happen? Is it only when opening a project?

**Comment by chapati23** [comment] 2017-09-13 14:23
yep, only when opening projects

**Comment by jakubzitny** [comment] 2017-09-28 21:38
Hi @chapati23, are you using Ghostery or a similar ad/track-blocking plugins in your browers?

**Comment by chapati23** [comment] 2017-09-29 06:28
I’m using Ghostery indeed

**Comment by jakubzitny** [comment] 2017-10-20 14:51
Hi guys, @chapati23, @zatziky, @crh225, is this still happening? We're trying to reproduce it and we're not able to do so with Chrome on both macOS and Windows. We've seen that this is happening mostly on Windows, but it's not happening to us. We have Ghostery `7.3.3.7` and Chrome 51.

**Comment by chapati23** [comment] 2017-10-20 15:09
hi @jakubzitny, hasn't happened in a while for me

**Comment by jakubzitny** [comment] 2017-10-20 15:14
Allright, thanks for the info. We think this was caused by Ghostery itself and we believe it might have been already fixed. I will close this then and re-open if we see it again 🙂

**Closed by jakubzitny** 2017-10-20 15:14 UTC
Labels: needsMoreInfo, underReview, waitingForUser

**Comment by crh225** [comment] 2017-10-20 16:10
Still hapening


* **Version**: 2.16.1-web


* **Web/Desktop**: Web

* **Platform**: windows 6.1
* **Browser**: chrome 61.0.3163.100

* **Avocode UID**: 121241
---



```
SyntaxError: Unexpected token var
```

**Comment by crh225** [comment] 2017-10-20 16:11
also broke in * **Browser**: chrome 62.0.3202.62

**Comment by jakubzitny** [comment] 2017-10-20 16:11
Do you have the latest version of Ghostery @crh225?

**Comment by crh225** [comment] 2017-10-20 16:11
I have 7.3.3.7

**Comment by jakubzitny** [comment] 2017-10-20 16:15
Do you have any details on your Ghostery configuration? Do you have any advanced settings there?

**Comment by crh225** [comment] 2017-10-20 16:23
@jakubzitny I have the default settings. 

![image](https://user-images.githubusercontent.com/19475195/31831418-11c24a14-b589-11e7-875d-f4f62b7f7832.png)

**Comment by jakubzitny** [comment] 2017-10-20 17:32
Thanks for the info @crh225. It might actually be related to some other plugin as well. Upgrading Windows might help too.

I am sorry that this is still happening to you, we'd like to help but without being able to reproduce it, there is not much we can do. Even more if it's related to another 3rd or 4th-party plugin.
