### ISSUE TITLE
bug with new sketch 3.4 version

### ISSUE THREAD

**Issue by no-karma-no-cry** [avocode/avocode#488] opened 2015-10-26 16:08 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/john/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment] 2015-10-26 20:45
Duplicate of #472. Thanks for your report though!

**Closed by jankuca** 2015-10-26 20:45 UTC

**Comment by marekhrabe** [comment] 2015-10-26 23:13
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/
