### ISSUE TITLE
Avocode Plugin Upload Error

### ISSUE THREAD

**Issue by urikelman** [avocode/avocode#492] opened 2015-10-26 21:02 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/uri.k/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment] 2015-10-26 21:23
Thanks for the report. Duplicate of #472

**Closed by jankuca** 2015-10-26 21:23 UTC

**Comment by marekhrabe** [comment] 2015-10-26 23:13
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/
