### ISSUE TITLE
Markers don`t show up.

### ISSUE THREAD

**Issue by AlexeyMihaylov** [avocode/avocode#334] opened 2015-07-03 11:05 UTC
Hi,

I think, the screenshot will describe the problem better than any words: 

http://i.piccy.info/i9/aa1744be67e60130b70ee63687f4ca51/1435921489/181501/926201/shot.png

P.S.: I can send the PSD if you need :dart:

**Comment by rychlis** [comment] 2015-07-08 16:53
Thanks for the report, we can reproduce the issue and will fix it in the next release 2.4.0

**Comment by rychlis** [comment] 2015-08-10 22:08
This should be fixed since 2.4.0 release. Let me know if you still experience the issue

**Closed by rychlis** 2015-08-10 22:08 UTC
Labels: bug
