### ISSUE TITLE
Bug report in Avocode

### ISSUE THREAD

**Issue by nomijoy** [avocode/avocode#414] opened 2015-08-30 08:51 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.2-d618096
Source UID: 103327
```
Error: channel closed
    at ChildProcess.target.send (child_process.js:396:26)
    at Task.module.exports.Task.send (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/src/task.js:125:27)
    at e._send (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:6156)
    at e._addRequest (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:4171)
    at e.downloadFiles (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/downloader.js:1:2016)
    at e.downloadFiles (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:7718)
    at t.module.exports.t._createImageRequest (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1938)
    at t.module.exports.t.downloadImages (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-downloader.js:1:1150)
    at e._downloadRevisionImages (/Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:13768)
    at /Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:12583
    at /Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:766
    at /Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:6877
    at /Users/NomiJoyShikma/Downloads/Avocode-4.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/api.js:1:
```

**Comment by rychlis** [comment] 2015-10-23 14:27
Sorry for the late reply. This is duplicate of #388 which is in progress of fixing now

**Closed by rychlis** 2015-10-23 14:27 UTC
