### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yaronshlomo** [avocode/avocode#2031] opened 2018-05-21 07:24 UTC
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 276607
---
```
Error: EACCES: permission denied, open '/home/yarons/.avocode/userdata/276607/project_thumbnails/59e8629d08784098abbecea8fab60f4e-s=410x673-preview.webp'
```

**Comment by jakubzitny** [comment] 2018-05-21 08:05
Duplicate of #2032.

**Closed as completed by jakubzitny** 2018-05-21 08:05 UTC
Labels: bug, duplicate, linux
