### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dragin96** [avocode/avocode#2011] opened 2018-05-04 08:07 UTC
---
* **Version**: 2.25.2-web.1
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 66.0.3359.139
* **Avocode UID**: 13268
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:57694)
    at ri (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:809495)
    at d3 (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:2863440)
    at Vi (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:845381)
    at Array.GXA (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:7721908)
    at UwA (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:5178163)
    at scA (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:4261809)
    at HsA (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:7193845)
    at GlA (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avocode-web.min.js:1:4609034)
    at GlA (https://cdn.app.avocode.com/dist/v-88bd61e/js/2.avoco
```

**Comment by jakubzitny** [comment] 2018-05-13 09:03
Duplicate of #1985 and #1875.

**Closed as completed by jakubzitny** 2018-05-13 09:03 UTC
Labels: bug, duplicate, rendering
