### ISSUE TITLE
I cant upload a design at all.. 

### ISSUE THREAD

**Issue by xyzeto** [avocode/avocode#1561] opened 2017-07-31 02:56 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 68922
```
TypeError: o.replace is not a function
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:599078)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597707
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2067:62)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597682)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:595019
```

**Comment by xyzeto** [comment] 2017-07-31 02:58
I selected one artboard and it didnt work. Just came up with error message.

**Comment by jakubzitny** [comment] 2017-07-31 07:40
Hi @xyzeto, this is a duplicate of #1545, #1546 and #1555. We have some problems with installing the latest plugin to Sketch for some users and this is a result of that. Please install the latest version from [this link](https://upx.cz/iYd), double click to install and everything should work.

Let me know if you have any more problems, please 😉

**Closed by jakubzitny** 2017-07-31 07:40 UTC

**Comment by jakubzitny** [comment] 2017-07-31 08:06
Also, I have a question for you that might help us prevent this in the future. Where is your Sketch plugins folder located, please? If it is something else than `~/Library/Application Support/com.bohemiancoding.sketch3/Plugins` would you share it with me, please? Is it somewhere inside `Containers` sandbox? Did you originally install Sketch app via Mac App Store, please?
