### ISSUE TITLE
UI bugs on Avocode 2.9.1

### ISSUE THREAD

**Issue by limiterCore** [avocode/avocode#1060] opened 2016-08-24 06:17 UTC
Hi, I'm trying to describe problems:

1. Sort always resets to 'category'. I switch it to 'name', but in some time (sometimes seconds, sometimes minutes) it resets back to 'category' (OSX)
2. Link to 'all projects' when I'm inside some project sometimes doesn't work. (OSX Ubuntu 16.04). I need to open new 'project manager' tab to solve this.
3. Search inside project (CMD + F) works with bugs: (OSX)

sometimes it searches not inside a project in spite of 'SEARCH IN' checker is set to current project. 
If I type something in search field, than backspace it, and than type again - nothing happens.

**Comment by blcarson** [comment] 2016-08-24 07:27
Layers panel keeps un-hiding itself when you switch back to a mockup from another tab.

**Comment by petrbrzek** [comment] 2016-08-28 17:23
> Sort always resets to 'category'. I switch it to 'name', but in some time (sometimes seconds, sometimes minutes) it resets back to 'category' (OSX)

I'm unable to reproduce it. @limiterCore can you try it in 2.10.0 and let me know if it's still happening?

> Link to 'all projects' when I'm inside some project sometimes doesn't work. (OSX Ubuntu 16.04). I need to open new 'project manager' tab to solve this.
Search inside project (CMD + F) works with bugs: (OSX)

Those two should be fixed.

> Layers panel keeps un-hiding itself when you switch back to a mockup from another tab.

This should be fixed as well in 2.10.0.

**Comment by petrbrzek** [comment] 2016-08-28 17:24
I'm closing this issue now. Do not hesitate to let me know if something goes wrong.

**Closed by petrbrzek** 2016-08-28 17:24 UTC
