### ISSUE TITLE
Problem creating screenshot

### ISSUE THREAD

**Issue by davidheyman** [avocode/avocode#325] opened 2015-06-30 20:33 UTC
Describe your problem here…

-----

```
TypeError: undefined is not a function
    at _makeDocumentScreenshot (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2278)
    at wrapper (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/lodash/index.js:3602:19)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2097
    at CallbacksRegistry.module.exports.CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/atom.asar/common/api/lib/callbacks-registry.js:35:42)
    at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:146:30)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by petrbrzek** [comment] 2015-07-01 16:56
Duplicate of #300. Will be fixed in 2.3.0.

**Closed by petrbrzek** 2015-07-01 16:56 UTC
