### ISSUE TITLE
Avocode App crashes on Ubuntu

### ISSUE THREAD

**Issue by TIIUNDER** [avocode/avocode#2225] opened 2018-10-24 14:46 UTC
At the first start on Ubuntu 16.04 Avocode crashes. Clicking the "restart" button restarts it and after that it works. 

---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: linux
---
```
{ preventDefault: [Function: preventDefault],
  sender:
   WebContents {
     webContents: [Circular],
     history:
      [ 'file:///opt/Avocode/resources/app.asar/desktop-index.html?appDataDirname=%2Fhome%2Fthunder%2F.avocode' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Array],
        'did-navigate': [Function],
        destroyed: [Function],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        crashed: [F
```
---
```
["app-finished-launching","app-crash-reporter-starting","app-crash-reporter-started","appready","appopenlisteners-replacing","appopenlisteners-replaced","appsplash-creating","appsplash-created","createwindow-starting","createwindow-browser-window-preparing","createwindow-browser-window-prepared","createwindow-crash-listener","createwindow-state-manage","createwindow-load-url","createwindow-dom-ready-listener","createwindow-finishing","ipc--calling-methog--setTitle","mainwindow-dom-ready","mainwindow-destroying-splash","mainwindow-showing","mainwindow-shown","mainwindow-maximizing","mainwindow-opening-init-urls","mainwindow-opening-init-files","mainwindow-initializing-menu-bar"]
```

**Comment by crashmajstr** [comment] 2018-10-25 07:37
Hello @TIIUNDER ,
thank you for reaching out. Does this happen every time you first start Avocode or it was only once?
Thanks for letting me know!

**Comment by TIIUNDER** [comment] 2018-10-25 08:10
@crashmajstr No, it's happening every time. Also closing and and opening it again crashes it. Only using the restart button after the first crash is working.

**Comment by crashmajstr** [comment] 2018-10-25 08:55
Hi, thank you, we noticed that some of our user ~3 reported this problem as well, but we can't reproduce it on our end. So we'll try to investigate it more on our end. One thing you can try is to delete your ~.avocode folder, maybe it'll help. Otherwise, please use the web app it should work ok. Thank you! 

Closing with respect to #2109 #2146

**Closed as completed by crashmajstr** 2018-10-25 08:55 UTC
Labels: bug, linux
