### ISSUE TITLE
Uploading and Processing

### ISSUE THREAD

**Issue by k25neo** [avocode/avocode#1375] opened 2017-04-11 09:13 UTC
2.13.4

no updates available

* **Version**: 2.13.4

* **Web/Desktop**: Desktop

* **Platform**: Win 10, 

while uploading and processing...
![avacode_2_13_4](https://cloud.githubusercontent.com/assets/21263926/24901614/14f52346-1ec1-11e7-8eb4-d7d8c2ee72f3.PNG)

**Comment by bolekkerous** [comment] 2017-04-11 09:17
Hey,
thanks for the report and sorry for the inconvenience.

Did you upload these two files together? If you try to upload the 768_main.psd alone, does it work?

**Comment by bolekkerous** [comment] 2017-05-10 15:06
This problem is caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374 

As for the problem with infinite waiting in the "finished" state, that should be fixed in the upcoming version.

**Closed by bolekkerous** 2017-05-10 15:06 UTC
