### ISSUE TITLE
Crush

### ISSUE THREAD

**Issue by yarikgoldvarg** [avocode/avocode#2107] opened 2018-08-01 15:02 UTC
---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
---
```
{}
```

**Comment by jakubzitny** [comment] 2018-08-01 15:45
Hi @StasZnaydyonov, thanks for reporting this. We've seen similar app crash in #2105 but we're not able to reproduce it. When did this start happening? And when exactly during the app start do you get this error?

Can you try our web app at http://app.avocode.com to see if that works for you for now?

**Comment by jakubzitny** [comment] 2018-08-02 10:47
Hi again @yarikgoldvarg, can you please try using this beta build to see if the problems go away? https://we.tl/R64ZldyRqh

We're trying to find the root cause of this behaviour but we're not really able to reproduce it properly. The build should definitely help, we'll be happy if you use it and give us a feedback.

**Comment by jakubzitny** [comment] 2018-08-06 08:53
Closing with respect to #2105. Let's continue the discussion over there.

**Closed as completed by jakubzitny** 2018-08-06 08:53 UTC
Labels: bug, waitingForUser, needsMoreInfo, electronRelated
