### ISSUE TITLE
tab moving error

### ISSUE THREAD

**Issue by salexpro** [avocode/avocode#1457] opened 2017-05-30 21:09 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.1`
Avocode UID: 30893
```
Invariant Violation: Cannot call hover after drop.
    at Object.invariant [as default] (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:117:25)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:74:36)
    at HTML5Backend.handleTopDragOver (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:480:18)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment] 2017-06-06 10:09
You are drag'n'dropping over top bar of avocode, right?

That's what cause this, just drag'n'drop over right left or bottom edge and everything should be OK.
Or use upload button in the menu / in the Manager

This is known issue. duplicate of #1249

**Closed by connor-bean** 2017-06-06 10:09 UTC
Labels: duplicate

**Comment by salexpro** [comment] 2017-06-06 11:54
it's just drag'n'drop tab from 2nd to 1st place
