### ISSUE TITLE
Missing export rule

### ISSUE THREAD

**Issue by renemaas** [avocode/avocode#114] opened 2015-02-02 07:39 UTC
Please add the possibility to export images 2 times larger not only 1x, 0.5x and 0.25x.

**Comment by tomashanacek** [comment] 2015-02-03 20:04
Duplicate of #59 , moved to user voice http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6988511-export-images-for-retina-screens

**Closed by tomashanacek** 2015-02-03 20:04 UTC
Labels: duplicate
