### ISSUE TITLE
Failed to upload two designs

### ISSUE THREAD

**Issue by srdjanjovanovic** [avocode/avocode#1353] opened 2017-03-28 10:46 UTC
* **Version**: 2.13.1

* **Web/Desktop**: Desktop

* **Platform**: Windows 10

Just uploaded 2 designs - (355Mb and 408Mb), and it showed What's wrong? button with red background.

**Comment by vojtatranta** [comment] 2017-03-28 10:59
@srdjanjovanovic this means that design or designs failed to parse on our side. There may be many reasons.

We could upload them for you or you may try again one by one.

You can also send us these designs at team@avocode.com

**Comment by bolekkerous** [comment] 2017-03-28 11:02
Yes - with that size, it might be possible that some parts of the design are too large to be processed on our side. We would need to see the actual files to know what exactly causes the problem.

If you can send us the designs to team@avocode.com, we should be able to upload these files through Photoshop plugin for you. Or if you have access to Photoshop yourself, you can download our Photoshop plugin and upload it through that.

**Comment by bolekkerous** [comment] 2017-05-10 15:13
This problem is caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:13 UTC
Labels: duplicate
