### ISSUE TITLE
Extracting error !IMPORTANT

### ISSUE THREAD

**Issue by moomot** [avocode/avocode#597] opened 2016-01-15 22:57 UTC
IMPORTANT: Please try to describe how did it happen.
I made merged export of shapes. And this error occurred.
-----
App v.2.4.5
Source UID: 143025
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/src/window-event-handler.js:170:20)
  at HTMLDocument.handler (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/src/space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/src/command-registry.js:251:29)
  at /home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/home/kiko/Downloads/Avocode-linux-x64/resources/app.asar/src/window-event-handler.js:184:27)

```

**Comment by jankuca** [comment] 2016-01-16 14:56
Hello, thanks for the report. It's possible this happened after you used ctrl+a to select the contents of the export rule name input. This is a long-running bug coming from the codebase of Atom upon which Avocode is built. **Please select the contents using the mouse cursor for now.** We are working on removing the Atom codebase from our app and have this done with the next major release.

**Comment by rychlis** [comment] 2016-01-26 13:14
I am closing this issue as it's a duplicate of #566

**Closed by rychlis** 2016-01-26 13:14 UTC
Labels: atomRelated, bug, duplicate, linux, windows
