### ISSUE TITLE
Windows installer not doing anything

### ISSUE THREAD

**Issue by retep007** [avocode/avocode#386] opened 2015-08-11 19:15 UTC
Instalation just flashes and nothing happens.  Please fix as soon as possible.

**Comment by rychlis** [comment] 2015-08-12 13:57
Hey, here is the app without installer that should work by unzipping manually:
https://s3.amazonaws.com/avocode-media/download/avocode-app/2.4.1/windows-no-installer.zip

We are going to investigate what could be broken on Windows 10

**Comment by retep007** [comment] 2015-08-13 08:21
Thank you, anyway installation of atom was successful, maybe problem with your specific plugins.

**Comment by rychlis** [comment] 2015-09-18 11:56
Sorry for the late update, we could not reproduce such error on Windows 10, it seems to be an issue specific to some installation. Could you look into `%localappdata%` directory (just copy it to location bar in file explorer) if there is a folder named `avocode` and send us the `SquirrelSetup.log` file inside?

Also here is the Avocode 2.4.2 in case you anyone needs it without installer: [2.4.2 windows-no-installer.zip](http://mediacdn.avocode.com/download/avocode-app/2.4.2/windows-no-installer.zip)

**Comment by retep007** [comment] 2015-09-18 12:01
Windows 10 som sa už bohužial zbavil (z mojho pohladu nastastie). Avsak verzia bez instalacie fungovala perfektne.

**Comment by kkoepke** [comment] 2015-10-23 08:41
Can we have the Version 2.4.3 without Installer too? Maybe you can publish every new version with and without installer as long as it is not fixed?

**Comment by rychlis** [comment] 2015-10-23 08:56
@kkoepke could you please also look into `%localappdata%` directory (just copy it to location bar in file explorer) if there is a folder named avocode and send us the `SquirrelSetup.log` file inside? You can send it to team@avocode.com

Here is a version without installer: https://s3.amazonaws.com/avocode-media/download/avocode-app/2.4.3/windows-no-installer-rc2.zip

We will add installer-less version of the App to our download page

**Comment by kkoepke** [comment] 2015-10-23 09:01
Hmm ok, the 2.4.3 installer worked fine this time for me. Im gonna send you the 2.4.2 log if you still need it.

**Comment by rychlis** [comment] 2015-10-23 13:59
OK I am closing this issue for now. I will reopen if anyone encounter the issue again.

Also note that the installer will not do anything at all if you already have the latest version installed, maybe that was the case?

**Closed by rychlis** 2015-10-23 13:59 UTC
Labels: hardToReproduce, needsMoreInfo, windows
