### ISSUE TITLE
Error uploading PSD

### ISSUE THREAD

**Issue by tomleo** [avocode/avocode#436] opened 2015-09-14 14:58 UTC
STR:
1. Add PSD file
2. Got an error message with a prompt to retry
3. Got a prompt to submit this issue on github

-----
App v.2.4.2-d618096
Source UID: 95195
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
    at invariant (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
    at o.Dispatcher.dispatch (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
    at o.handleViewAction (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
    at t.module.exports.t.setDocument (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/active-document.js:1:1668)
    at t._fireNoActiveViewEvents (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:24433)
    at t._fireNoActiveViewEvents (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:999)
    at atom-workspace.<anonymous> (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:8427)
    at atom-workspace.handler (/home/tom/Downloads/Avocode/resources/app.asar/src/space-pen-extensions.js:110:34)
    at atom-workspace.jQuery.event.dispatch (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at atom-workspace.elemData.handle (/home/tom/Downloads/Avocode/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/tom/Downloads/Avocode/resources/app.asar/src/command-registry.js:251:29)
    at CommandRegistry.handleCommandEvent (/home/tom/Downloads/Avocode/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/home/tom/Downloads/Avocode/resources/app.asar/src/command-registry.js:166:19)
    at 
```

**Comment by jankuca** [comment] 2015-09-16 20:03
Thanks for reporting. Duplicate of #421

**Closed by jankuca** 2015-09-16 20:03 UTC
