### ISSUE TITLE
Preview generation failed

### ISSUE THREAD

**Issue by stdex** [avocode/avocode#588] opened 2016-01-09 11:40 UTC
This: https://github.com/aiopio/shoppsd/tree/master/PSD

**Comment by jankuca** [comment] 2016-01-11 23:23
Hello, thanks for reaching out to us. What does "does not open" mean in your case?

I can open the documents in question just fine with Avocode.

![screen shot 2016-01-12 at 12 22 08 am](https://cloud.githubusercontent.com/assets/367262/12249828/9a8bb81e-b8c2-11e5-987a-9a42386a0ddb.png)

![screen shot 2016-01-12 at 12 22 10 am](https://cloud.githubusercontent.com/assets/367262/12249829/9d2f8bfe-b8c2-11e5-8084-9ac212bfe738.png)

![screen shot 2016-01-12 at 12 22 14 am](https://cloud.githubusercontent.com/assets/367262/12249831/a0b70266-b8c2-11e5-81b3-3743f1e33ff8.png)

**Comment by stdex** [comment] 2016-01-12 07:56
![image](https://cloud.githubusercontent.com/assets/4608879/12257854/00999f38-b91b-11e5-8844-ded7d55bc70d.png)
![image](https://cloud.githubusercontent.com/assets/4608879/12257856/032041e4-b91b-11e5-8dbe-cadacf4816b6.png)
![image](https://cloud.githubusercontent.com/assets/4608879/12257860/1174fb9a-b91b-11e5-9c0a-135a931fe14b.png)
![image](https://cloud.githubusercontent.com/assets/4608879/12257880/27323ba0-b91b-11e5-945f-3c0eb442e5ea.png)

**Comment by jankuca** [comment] 2016-01-12 15:02
OK, I see. The issue is that preview generation failed but are you able to open the design by clicking the "Save and Open" button in the app sidebar?

**Comment by stdex** [comment] 2016-01-12 15:04
@jankuca, yes it is. open with "Save and Open" work correctly.

**Comment by jankuca** [comment] 2016-01-12 15:19
Following the "Learn more" links presents an article about resolving the preview issue on linux. It is however quite strange the preview is not presented on the website either. Let us get back to you when we investigate this.

**Comment by stdex** [comment] 2016-01-12 15:30
@jankuca, imagemagick installed on my computer, it's problem reproduced only with this PSD files.
![image](https://cloud.githubusercontent.com/assets/4608879/12267705/79216424-b95a-11e5-89ef-2571083008d3.png)
![image](https://cloud.githubusercontent.com/assets/4608879/12267717/8d700732-b95a-11e5-9a6a-b999b66a2ace.png)

**Comment by rychlis** [comment] 2016-01-26 14:12
imagemagick is unable to create a preview image for these PSDs for some reason. This happens to a really small amount of PSDs, we are definetely going to add a fallback method to extract previews in the future

**Comment by connor-bean** [comment] 2016-06-14 15:18
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 15:18 UTC
Labels: bug
