### ISSUE TITLE
Failed to execute 'shaderSource' 

### ISSUE THREAD

**Issue by mldk-tech** [avocode/avocode#2103] opened 2018-07-30 10:10 UTC
---
* **Version**: 3.3.1-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 67.0.3396.99
* **Avocode UID**: 380818
---
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at _glShaderSource (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:616436)
    at Af (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:719774)
    at Gs (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:1212051)
    at NM (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:1610548)
    at https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:4614751
    at Array.PeA (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:4616947)
    at Array.TeA (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:4684058)
    at dynCall_iiiii (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:7187827)
    at dynCall_iiiii_72 (eval at <anonymous> (https://cdn.app.avocode.com/dist/v-44c9695/js/2.avocode-web.min.js:1:552850), <anonymous>:4:12)
 
```

**Comment by jakubzitny** [comment] 2018-07-30 10:51
Hi @DavidKohav, thanks for reporting this problem. It seems that our rendering engine has issues with WebGL in some specific cases. We're already tracking a similar problem in #1875, so I am going to close this.

However, could you please give us more hints on when is this happening? Is it when you're opening a design or when exporting something? Does it happen to all designs or only with one specific design?

In the meantime can you please try our [desktop](http://avocode.com/download) version to see if you have similar problems in it?

Thanks

**Closed as completed by jakubzitny** 2018-07-30 10:51 UTC
Labels: bug, duplicate, rendering

**Comment by mldk-tech** [comment] 2018-07-30 11:26
Is it when you're opening a design or when exporting something? 
:: opening a design
Does it happen to all designs or only with one specific design?
:: one specific design.

**Comment by jakubzitny** [comment] 2018-07-30 11:27
Can you please share the design with us @DavidKohav? Either the public/private link you can copy in project manager, or you can send the file to team@avocode.com.

**Comment by mldk-tech** [comment] 2018-07-30 11:38
https://app.avocode.com/projects/641555

**Comment by connor-bean** [comment] 2018-07-30 12:20
Hey,
this may mean that your GPU does not work well together with Electron (framework which our desktop app is built on). We are already working on an improvement that should probably resolve this issue, however it will take a while. 

So in the meanwhile, I would suggest using the web app at https://app.avocode.com/ for exporting images.

Alternatively if you disable the Monroe engine in the desktop App preferences, and then close and reopen the design, it should help. Please see the screenshot below - the highlighted checkbox must be checked:

<img width="565" alt="avocode_2_19_0" src="https://user-images.githubusercontent.com/17878371/43396982-a3eea6ae-9403-11e8-8582-1b3733f79ede.png">

Once you disable the Monroe Engine, does it work or do you receive an error again?

**Comment by connor-bean** [comment] 2018-07-30 12:23
It's possible that it's a webGL problem. Does your Chrome browser have WebGL enabled? You can test it here: https://get.webgl.org/

Can you also try in Firefox? Please let us know the result!

**Comment by jakubzitny** [comment] 2018-07-30 12:45
We've looked at it and it works for us correctly. This issue is very likely to be caused by not enough resources on Windows. If the desktop Avocode app has similar problems then the only recommendation is to tell the designer to split the design to multiple smaller files.

You can also use our [Photoshop to Sketch](https://avocode.com/convert-psd-to-sketch) converter to convert the design to Sketch artboards which are automatically separated in Avocode 😉
