### ISSUE TITLE
Problem to report:

### ISSUE THREAD

**Issue by nmcobalt** [avocode/avocode#2190] opened 2018-10-15 09:52 UTC
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 432463
---
```
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at Object._renderTickCanvas (file:///C:/Users/n.mavromatis.LD/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3479115)
    at Object._updateTickCanvas (file:///C:/Users/n.mavromatis.LD/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478771)
    at Object.componentWillUpdate (file:///C:/Users/n.mavromatis.LD/AppData/Local/avocode/app-3.5.5/resources/app.asar/dist/avocode.min.js:1:3478523)
    at ReactCompositeComponentWrapper._performComponentUpdate (C:\Users\n.mavromatis.LD\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:714:14)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\n.mavromatis.LD\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:645:12)
    at ReactCompositeCom
```

**Comment by vojtatranta** [comment] 2018-10-15 09:53
Hi @nmcobalt ,
we know about this bug and it will be fixed today in `3.5.6`.

This issue is duplicate of #2183

**Closed as completed by vojtatranta** 2018-10-15 09:53 UTC
