### ISSUE TITLE
Uploading an artboard to an existing project results in an error

### ISSUE THREAD

**Issue by Vashiru** [avocode/avocode#1468] opened 2017-06-07 14:02 UTC
IMPORTANT: Please try to describe how did it happen.
I tried to upload an artboard to an existing project.

-----
App v. `2.14.3-community-beta.1`
Avocode UID: 21082
```
RangeError: Invalid string length
    at Socket.onChildStdout (child_process.js:279:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

**Comment by jakubzitny** [comment] 2017-06-07 14:06
Hi @Vashiru, thanks for testing the community beta version. This has probably happened to you more than once, right? Was it the same artboard and project or different ones? Was the project empty?

I'll look into it, it's clearly a bug.

**Comment by Vashiru** [comment] 2017-06-07 14:07
Hmm, seems like it might not have to do with uploading an artboard, just running it for a few minutes seems to trigger it. I'll try running it again for a few minutes to confirm.

**Comment by Vashiru** [comment] 2017-06-07 14:14
Yeah got it:

1. Open avocode
2. Open sketch
3. Select an artboard and press "upload selected artboard"
4. The project picker in Avocode will show up
5. Just wait for about a minute, the error will repeatedly keep showing up

Note if you do press upload, it will start importing the file and prepare to upload but will still throw the error mentioned above.

**Comment by jakubzitny** [comment] 2017-06-08 08:43
Thanks a lot for the info. Would you be willing to send us the sketch file to team@avocode.com? We have several crazy looking sketch files for testing, but I was not able to reproduce this particular error.

**Comment by Vashiru** [comment] 2017-06-08 09:28
@jakubzitny Coming right up through WeTransfer. I'll reference the issue number to look for :)

**Comment by connor-bean** [comment] 2017-06-08 09:48
@Vashiru - we received it and i passed it along to @jakubzitny. We'll follow up here when we have more info

**Comment by jakubzitny** [comment] 2017-06-08 17:02
I've fixed your problem @Vashiru in the latest community build. Can you please try it and let me know if it works, please? You can download it from https://upx.cz/itf.

Uploading artboards should work, all symbols within will be sync automatically. Since your particular file is quite big, I have problems syncing all artboards at once, but separate artboards and this `Invalid string length` should be fixed.

**Comment by Vashiru** [comment] 2017-06-08 20:25
Hmm, it works, but it has created 3 new designs in Avocode, rather than update the ones already existing. Is that because it's the new way of uploading vs the plugin?

**Comment by jakubzitny** [comment] 2017-06-09 08:12
Hi, yeah, it's because of that. If you have empty project, sync some artboards, then make changes and sync again, it will update the artboards - they will be synced as a new revision of the existing ones. It does not work with the old ones though. We'll try to improve this scenario as well.

I will close this issue as it is already fixed, but feel free to let us know about any problems with Avocode or ideas how to improve it. Here or in the [Avocode Community](https://community.avocode.com) Slack channel.

**Closed by jakubzitny** 2017-06-09 08:12 UTC
Labels: bug, sketchPluginBeta
