### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by galkinrost** [avocode/avocode#487] opened 2015-10-26 11:30 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/galkinrost/Library/Containers/com.bohemiancoding.sketch3.beta/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by squadnik** [comment] 2015-10-26 15:46
The same here.
This error appears right after exporting artboards and during "uloading layers".
The error appeared right after today's Sketch update.
![error](https://cloud.githubusercontent.com/assets/15327259/10733924/21b614c8-7c01-11e5-9218-9e17afae1944.jpg)

**Comment by jankuca** [comment] 2015-10-26 20:47
Duplicate of #472. Thanks for your reports guys!

**Closed by jankuca** 2015-10-26 20:47 UTC

**Comment by marekhrabe** [comment] 2015-10-26 23:13
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/

**Comment by squadnik** [comment] 2015-10-27 08:25
Great!
Thanks for ultrafast reaction!

2015-10-27 0:13 GMT+01:00 Marek Hrabe <notifications@github.com>:
