### ISSUE TITLE
Please help, i can't open a large file.

### ISSUE THREAD

**Issue by CuongSky** [avocode/avocode#582] opened 2015-12-28 11:04 UTC
Hello team,
Please help me to fix this issue or guide me how to solve it.
We have a heavy file on Avocode (104MB) and i just can open it only 1 time, after watching and scrolling, the file was closed automatically. After that i tried many times (more than 7 times), i can't still open it again.
This is screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/3079135/12017692/c1ce6c1e-ad8c-11e5-8059-f1c9d51b2db9.png)

Thank you.
Best regards,
Cuong Vu

**Comment by vojtatranta** [comment] 2015-12-29 12:15
Thank you for your report.
Can you please share with us this problematic psd at team@avocode.com?

**Comment by rychlis** [comment] 2016-01-26 14:13
Unfortunately there seems to be a rendering issue on Windows which can cause larger designs to crash when rendered. It might help to try it with the latest version of Avocode 2.5.2 if you have an active account, we've updated internal chromium browser a few times which should improve the performance a bit.

Probably a duplicate of #143 but let me know if you can reproduce the issue with Avocode 2.5.2

**Comment by rychlis** [comment] 2016-02-17 16:28
I am closing the issue due to no activity. We'll definetely re-open the issue if you can still reproduce it with latest Avocode

**Closed by rychlis** 2016-02-17 16:28 UTC
Labels: bug, waitingForUser

**Comment by rychlis** [comment] 2016-06-14 21:53
We just created a x64 build of Avocode which should fix this issue. You can try it out: https://media.avocode.com/download/avocode-app/2.8.0/avocode-app-windows-x64-2.8.0.exe

Note that this requires a 64bit Windows. We will soon make this the default version of Avocode
