### ISSUE TITLE
PSDs does not upload at all

### ISSUE THREAD

**Issue by eightmethods** [avocode/avocode#380] opened 2015-08-10 09:35 UTC
Using the Avocode Mac app, I upload my PSD files. Usually it only goes up to 1%-3% and then an error occurs. I only managed to upload one PSD file out of the hundreds I have. Would love some help on this issue. Planning to purchase a subscription after the trial period, but hopefully these kind of errors will be fixed.

**Comment by rychlis** [comment] 2015-08-10 10:09
I am very sorry for the inconvenience, our storage service provider (AWS S3) is currently experiencing issues unfortunately. They are working on resolving the issue which should not take long hopefully.

I'll give you a status update when the issue is resolved. BTW, the outage is affecting a lot of other US services as well

**Comment by rychlis** [comment] 2015-08-10 11:04
The AWS issue should be resolved now, sorry for the inconvenience

**Closed by rychlis** 2015-08-10 11:04 UTC
