### ISSUE TITLE
SVG exports are really base64 png's

### ISSUE THREAD

**Issue by scottwio** [avocode/avocode#186] opened 2015-03-26 18:33 UTC
When I try to export a smart object as an SVG in actually produces a svg file with a image element which has base64 png attached to it on the xlink:href= tag. Is this expected behavior can avocode not produce real svg elements?

**Comment by Rad1calDreamer** [comment] 2015-03-31 07:14
+1

**Comment by paulburgess** [comment] 2015-04-07 10:25
+1 - I was really confused by this and was asking the designers if they had rasterised the vector elements as the SVGs weren't really scalable - but seeing this I guess Avocode just doesn't produce them

**Comment by tomashanacek** [comment] 2015-04-09 15:05
Duplicate of #81, moved to user voice https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support

**Closed by tomashanacek** 2015-04-09 15:05 UTC
Labels: duplicate
