### ISSUE TITLE
Invalid structure of layers leads to unpredictable consequences

### ISSUE THREAD

**Issue by unrealhero18** [avocode/avocode#1800] opened 2018-01-04 16:36 UTC
- design from Sketch;
- when layout's assets has invalid nesting after that place the next elements don't appear (only white space);
- avocode: http://joxi.ru/5mddv7BFkg7Gqm - invalid nesting;
- disign: http://joxi.ru/LmGa5EnCeGEWvA - this button inside mask layer;
- trigger: http://joxi.ru/v29LXWGu3JMBxm - error was appear after click on this layer (it's probably a border with gradient);
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 139720
---
```
TypeError: Cannot read property 'toJS' of undefined
    at a (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1385883)
    at Object.s [as convertColor] (file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1386024)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:115378
    at /opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/opt/Avocode/resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List 
```

**Comment by jakubzitny** [comment] 2018-01-05 10:02
Hi @unrealhero18, thanks for thorough report. We're already tracking this problem in #1760, it's caused by some gradients in the design. It will be fixed in Avocode 2.18.0 in upcoming week or two.

**Closed as completed by jakubzitny** 2018-01-05 10:02 UTC
Labels: bug, duplicate
