### ISSUE TITLE
I was trying to make separate export, and error occured when i started to rename layer

### ISSUE THREAD

**Issue by ak1987** [avocode/avocode#580] opened 2015-12-26 16:30 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 31382
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/src/window-event-handler.js:170:20)
  at HTMLDocument.handler (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/src/space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/src/command-registry.js:251:29)
  at /home/ak/Downloads/Avocode-linux-x64/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/home/ak/Downloads/Avocode-linux-x64/resources/app.asar/src/window-event-handler.js:184:27)

```

**Comment by vojtatranta** [comment] 2015-12-29 12:18
Thank you for your report.
It seems that you problem is just on Linux and it is connected to Atom.
Can you please tell what were you trying to do? Thanks.

**Comment by ak1987** [comment] 2015-12-29 15:09
I selected several layers (5-7 icons) and was going to separate export selected icons. When i was trying to set name for exporting icon, application threw error alert, but it was still working

**Comment by vojtatranta** [comment] 2015-12-29 15:13
Alright I put it into our internal issue tracker, so that we could take a look more closely, thanks.

**Comment by rychlis** [comment] 2016-01-26 12:52
This is actually duplicate of #566 and will happen on windows as well, i am closing this one to keep just one issue.

**Closed by rychlis** 2016-01-26 12:52 UTC
Labels: atomRelated, bug
