### ISSUE TITLE
aa

### ISSUE THREAD

**Issue by yossi-halfin** [avocode/avocode#1004] opened 2016-07-31 14:41 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 76403
```
TypeError: Cannot read property 'get' of null
    at Function.e.fromProject (file:///Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:14:15313)
    at e.createUploadTargetFromProject (file:///Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:14:2823)
    at Constructor._createUploadTarget (file:///Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:34:16653)
    at Constructor._handleUploadNewDesign (file:///Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:34:16835)
    at Constructor._handleUploadNewDesign (file:///Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:34:31537)
    at Object.invokeGuardedCallback (/Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:99:7)
    at executeDispatchesAndRelease (/Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/yossih/Downloads/Avocode-darwin-x64/Avocode.app/Conten
```

**Comment by connor-bean** [comment] 2016-08-01 10:41
Hey @yossi-halfin -

Can you describe more in detail what happened and what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by petrbrzek** [comment] 2016-08-05 12:13
Duplicate of #944.

**Closed by petrbrzek** 2016-08-05 12:13 UTC
Labels: willBeFixed
