### ISSUE TITLE
Sketch Plugin Black Screen

### ISSUE THREAD

**Issue by Dang-Dango** [avocode/avocode#1333] opened 2017-03-20 08:54 UTC
<img width="750" alt="zrzut ekranu 2017-03-20 o 09 48 50" src="https://cloud.githubusercontent.com/assets/26539132/24093218/0ae5031e-0d53-11e7-8ddd-a2a9733f117c.png">
<img width="759" alt="zrzut ekranu 2017-03-20 o 09 53 30" src="https://cloud.githubusercontent.com/assets/26539132/24093230/1a909daa-0d53-11e7-9a0f-b733fe3b3e55.png">

* **Version**: 
Avocode plugin 42.0.0

* **Native/Web**:
Native

* **Platform**: 
Mac/Sketch

**Comment by Vashiru** [comment] 2017-03-20 13:39
Looks like the same issue as I had. As a workaround for now:

1. Open Sketch
2. Go to Plugins -> Manage plugins -> In the bottom left corner press the gear icon -> Show plugins folder
3. Delete avocode-token.json
4. Restart Sketch
5. Next time you start Avocode plugin it will ask you to sign in again, once you do Avocode will work as intended.

**Comment by connor-bean** [comment] 2017-03-21 10:53
Thanks for the comment @Vashiru. 

@Dang-Dango - did this workaround work for you too>

**Comment by Dang-Dango** [comment] 2017-03-21 11:20
Deleting the .json file works like a charm. Thanks for the reply.

**Comment by Vashiru** [comment] 2017-03-21 11:34
This issue does keep returning for me though, so I wouldn't close it right now

**Comment by 1854** [comment] 2017-04-11 19:24
Im stuck on loading screen, am using sketch 43.1, followed steps above, i see sketch-panels.log but avocode-token.json is not in the plugins folder, am using sketch-plugin-mac-42.0.0 (made the switch from invision yesterday)

**Comment by bolekkerous** [comment] 2017-04-12 08:59
This might be a DNS problem, @1854 .

There are 3 possible things that you could try:

1. Try opening up https://sourcelocalhost.com:33162 in browser while the plugin screen is loading (it's where the plugin lives), maybe it will work in the browser if the error is isolated to Sketch.
2. Try Google DNS if possible
3. Add the DNS entry 127.0.0.1 sourcelocalhost.com to /etc/hosts manually

Here's an article explaining more about the host file:
http://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want

Please let us know the result.

**Comment by connor-bean** [comment] 2017-06-15 11:46
Hey this is now fixed in 2.14.3 with the new plugin. Please update your app

**Closed by connor-bean** 2017-06-15 11:46 UTC
Labels: sketchPlugin
