### ISSUE TITLE
To many bugs in 2.8.0(1) so I need to fallback to previous version

### ISSUE THREAD

**Issue by limiterCore** [avocode/avocode#931] opened 2016-06-17 09:26 UTC
There are to much bugs to work properly. I can write it down later, but now I really need to fallback, please.

**Comment by vojtatranta** [comment] 2016-06-17 09:31
Are you running Windows, Linux or Mac?

Can you be more specific about the bugs? Because our bug reporter is practically empty with `2.8.1`

**Comment by connor-bean** [comment] 2016-06-17 09:32
Hey, @limiterCore -

Here are the download links for 2.6:

Linux 32bit:
https://avocode-media.s3.amazonaws.com/download/avocode-app/2.6.0/avocode-app-linux-ia32-2.6.0.zip

Linux 64bit:
https://avocode-media.s3.amazonaws.com/download/avocode-app/2.6.0/avocode-app-linux-2.6.0.zip

Mac:
https://avocode-media.s3.amazonaws.com/download/avocode-app/2.6.0/avocode-app-mac-2.6.0.zip

Windows:
https://avocode-media.s3.amazonaws.com/download/avocode-app/2.6.0/avocode-app-windows-2.6.0.exe

**Comment by limiterCore** [comment] 2016-06-17 09:48
Thank you, @connor-bean.

@vojtatranta, bugs are on my Linux notebook. I'll send you full situation as I get some free time. Thank you.

**Comment by jakubzitny** [comment] 2016-06-17 10:56
Thanks @limiterCore, feel free to report the problems when you have time. We already have some tips for fixes and improvements and our team is working on most of them already. It will take some time to solve everything, we'll let you know when it's better ;)

#913 should be fixed already, please tell us if it's not for you.

#899 looks allright on our side, I think there was a problem with processing of the design. Please send us your PSD on which it happened if you can.

**Comment by connor-bean** [comment] 2016-06-17 14:08
Hey, @limiterCore - 

Could you send us an email to team@avocode.com? I have something I want to ask you offline. Feel free to mention this ticket number in your email. 

Thanks!
Connor, Avocode Support

**Comment by limiterCore** [comment] 2016-06-19 16:47
I'll try to describe the problems I had with 2.8.1 on Ubuntu (all problems with selecting and exporting of layers)

1. Sometimes the layer is selecting over the size of mockup
2. In this case the layer is exporting with white fields
3. Sometimes the layer is exporting with blank pixels. (Without screenshot, can not repeat (and it's good :))

![screenshot from 2016-06-19 21-44-03](https://cloud.githubusercontent.com/assets/2869059/16178636/5ef5855a-3667-11e6-8348-30e9f77cae75.png)
![screenshot from 2016-06-19 21-44-19](https://cloud.githubusercontent.com/assets/2869059/16178637/5ef5fe72-3667-11e6-9445-517e98e88e39.png)

**Comment by jankuca** [comment] 2016-06-19 21:52
The problem number 3 and possibly also no. 2 looks like a duplicate of #919.

I am not sure what you mean by the problem no. 1. Can you elaborate a bit?

**Comment by limiterCore** [comment] 2016-06-20 05:39
Yeah, @jankuca , you're right. About 1. - I'll try to repeat the situation.

**Comment by limiterCore** [comment] 2016-06-20 06:53
And one more problem - 2.8.1 can not open mockup (but 2.6.0 could). I've send dropbox link to the mockup.

**Comment by petrbrzek** [comment] 2016-06-27 20:59
@limiterCore Can you please try it in 2.8.2 and let us know? Thanks a lot.

**Comment by connor-bean** [comment] 2016-07-07 13:37
Hey @limiterCore 

Did downloading the newest version solve this?

Thanks!
Connor, Avocode Support

**Comment by limiterCore** [comment] 2016-07-12 06:51
Problems with opening some mockups were gone. Tested a lot.
Problems with exporting layers under testing, for now it's ok. Thx.

**Comment by connor-bean** [comment] 2016-07-12 12:33
Hey @limiterCore 

Thanks for letting me know. I am going to close this ticket. Please reopen if the issue happens again.

Have an awesome week!
Connor, Avocode Support

**Closed by connor-bean** 2016-07-12 12:33 UTC
Labels: needsMoreInfo, waitingForUser
