### ISSUE TITLE
Avocode unable to launch on Debian

### ISSUE THREAD

**Issue by Demak** [avocode/avocode#218] opened 2015-04-27 10:50 UTC
Hello, Avocode is not starting on my Debian Linux pc at all. When i try to launch it from nautilus, it's silently failing, if I am trying to launch it from terminal, bash is unable to launch it:
bash: /media/LStorage/download/Avocode/avocode: cannot execute binary file
This is probably caused by insufficient system requirements or wrong architecture, but I have not found any info about Avocode's requirements. Is it 64 bit only?
My system info:
Linux 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u1 i686 GNU/Linux
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

**Comment by tomashanacek** [comment] 2015-04-28 16:09
Hi, we only build a 64bit binaries for Linux.

duplicate of
http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7645281-32bit-linux-build

**Closed by tomashanacek** 2015-04-28 16:09 UTC

**Comment by Demak** [comment] 2015-04-29 05:43
Yes, now I have noticed this written under dowload button, sorry. Please consider putting same notice on dowload page for someone like me.
I have intalled Avocode on Windows VM.

**Comment by rychlis** [comment] 2015-11-10 14:48
We've launched Avocode 2.4.4 beta which should fix many issues and there is 32 bit build as well, you can download the build from here:

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
