### ISSUE TITLE
Incorect order of radiuses in border-radius property

### ISSUE THREAD

**Issue by Eugene-Musika** [avocode/avocode#1090] opened 2016-09-08 14:43 UTC
The radiuses must have next order: 
-top-left
-top-right
-bottom-right
-bottom-left
The Avocode has next order:
-top-left
-bottom-left
-bottom-right
-top-right

Please fix it.
![image](https://cloud.githubusercontent.com/assets/19905407/18353649/8418be7e-75eb-11e6-8dff-815baf2ad483.png)
![image](https://cloud.githubusercontent.com/assets/19905407/18353692/b2ea4e84-75eb-11e6-8f02-f8fc1b6f59b4.png)

**Comment by renekopcem** [comment] 2016-09-22 08:53
Hello @Eugene-Musika,

I just tried to replicate this border radius issue, but without any luck. It looks like that it works, so maybe there is an another problem. Could you send us the design to team@avocode.com? I would take a look and try to investigate it.

Thanks!
Roman

**Comment by Eugene-Musika** [comment] 2016-10-10 10:07
https://dl.dropboxusercontent.com/u/29650667/doc%20copy.sketch

Here it is. Sorry for delay.

**Comment by renekopcem** [comment] 2016-10-10 10:33
No problem, now I see where the issue is, we are going to fix it. Thank you for the design and for reporting it!

**Comment by renekopcem** [comment] 2016-12-08 07:23
So, after the investigation. We found out that the object is flipped. That's why the number are wrong (or in a some way correct). For now I'm closing this issue.

**Closed by renekopcem** 2016-12-08 07:23 UTC
Labels: bug, css, onGitlab
