### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by zavod008** [avocode/avocode#1354] opened 2017-03-28 12:29 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.1`
Avocode UID: 132779
```
TypeError: toISOString is not a function
    at String.toJSON (<anonymous>)
    at Object.<anonymous> (/home/john/avocode/resources/app.asar/node_modules/core-js/modules/_ctx.js:18:15)
    at JSON.stringify (<anonymous>)
    at stringify (/home/john/avocode/resources/app.asar/node_modules/json-stringify-safe/stringify.js:5:15)
    at Raven._makeRequest (/home/john/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:1559:22)
    at Raven._sendProcessedPayload (/home/john/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:1485:56)
    at Raven._send (/home/john/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:1442:14)
    at Raven._processException (/home/john/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:1290:14)
    at Raven._handleStackInfo (/home/john/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:1196:14)
    at Raven.captureException (/home/john/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:350:18)
    at e.captureException (file:///home/john/avocode/resources/app.asar/dist/avocode.min.js:41:15444)
    at file:///home/john/avocode/resources/app.asar/dist/avocode.min.js:7:23221
```

**Comment by vojtatranta** [comment] 2017-03-28 13:42
This is a duplicate of #1332

**Closed by vojtatranta** 2017-03-28 13:42 UTC
