### ISSUE TITLE
Problem in exporting the design 

### ISSUE THREAD

**Issue by blockchaintexno** [avocode/avocode#2086] opened 2018-07-11 11:03 UTC
---
* **Version**: 3.2.0
* **Sketch plugin version**: 50.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 369070
---
```
TypeError: Method Date.prototype.toISOString called on incompatible receiver #<Object>
    at Object.toISOString (<anonymous>)
    at Object.toJSON (<anonymous>)
    at JSON.stringify (<anonymous>)
    at stringify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/vendor/json-stringify-safe/stringify.js:23:15)
    at Raven._makeRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1924:39)
    at Raven._sendProcessedPayload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1877:52)
    at Raven._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1811:14)
    at Raven._processException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1568:10)
    at Raven._handleStackInfo (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1442:10)
    at Raven.captureExcep
```

**Comment by vojtatranta** [comment] 2018-07-12 13:08
Hi @Djamshid ,
we know about this and we are preparing a fix for the next release.

**Comment by jakubzitny** [comment] 2018-07-13 09:02
Duplicate of #2069.

**Closed as completed by jakubzitny** 2018-07-13 09:02 UTC
Labels: duplicate, willBeFixed
