### ISSUE TITLE
Constant Downloading

### ISSUE THREAD

**Issue by TrivediKavit** [avocode/avocode#686] opened 2016-02-02 14:07 UTC
Since upgrading to 2.5.2, my Avocode app constantly downloads. Looks like it is downloading every single file from every single project. In the earlier version, it used to let us choose which project to sync. Is there any way to get that back ? 

Avocode is completely congesting my download bandwidth right now. And I don't need all the projects at once on my local machine.

**Comment by Azarakhsh** [comment] 2016-02-12 14:55
The situation is the same on Ubuntu 14.04.

**Comment by petrbrzek** [comment] 2016-02-12 15:04
Please update to the latest version 2.5.4. It should be fixed.

**Closed by petrbrzek** 2016-02-12 15:04 UTC

**Comment by Azarakhsh** [comment] 2016-02-12 17:14
Thanks for the prompt reply.
The problem is resolved.
