### ISSUE TITLE
Error during exporting a document screenshot

### ISSUE THREAD

**Issue by balintgaspar** [avocode/avocode#427] opened 2015-09-04 09:34 UTC
Describe your problem here…

-----

```
TypeError: undefined is not a function
  at _makeDocumentScreenshot (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2278)
  at wrapper (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/lodash/index.js:3602:19)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/export-panel/lib/stores/export.js:1:2097
  at CallbacksRegistry.module.exports.CallbacksRegistry.apply (/Applications/Avocode.app/Contents/Resources/atom.asar/common/api/lib/callbacks-registry.js:35:42)
  at EventEmitter.<anonymous> (/Applications/Avocode.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:146:30)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

**Comment by petrbrzek** [comment] 2015-10-25 20:33
Thanks for your report. I'm unable to reproduce the issue. Does it happen regularly?

**Comment by connor-bean** [comment] 2016-06-14 14:43
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 14:43 UTC
Labels: bug, hardToReproduce, onGitlab
