### ISSUE TITLE
Crash avocode

### ISSUE THREAD

**Issue by AdamColton8** [avocode/avocode#2255] opened 2018-11-12 08:14 UTC
---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: linux
---
```
{ preventDefault: [Function: preventDefault],
  sender:
   WebContents {
     webContents: [Circular],
     history:
      [ 'file:///home/adam/Apps/PhpStorm-182.4892.16/resources/app.asar/desktop-index.html?appDataDirname=%2Fhome%2Fadam%2F.avocode' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Array],
        'did-navigate': [Function],
        destroyed: [Function],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function]
```
---
```
["app-finished-launching","app-crash-reporter-starting","app-crash-reporter-started","appready","appopenlisteners-replacing","appopenlisteners-replaced","appsplash-creating","appsplash-created","createwindow-starting","createwindow-browser-window-preparing","createwindow-browser-window-prepared","createwindow-crash-listener","createwindow-state-manage","createwindow-load-url","createwindow-dom-ready-listener","createwindow-finishing","ipc--calling-methog--setTitle","mainwindow-dom-ready","mainwindow-destroying-splash","mainwindow-showing","mainwindow-shown","mainwindow-opening-init-urls","mainwindow-opening-init-files","mainwindow-initializing-menu-bar","ipc--setting-menu-bar-visibility"]
```

**Comment by crashmajstr** [comment] 2018-11-12 08:22
Hello @AdamColton8  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by AdamColton8** [comment] 2018-11-12 10:26
@crashmajstr 
I used webshorm + gulp. I also used Google Chrome (3-4 tabs in the browser). After the error of this program, I moved the web version. Used the latest version of Avocode, Chrome, Ubuntu

**Comment by crashmajstr** [comment] 2018-11-12 10:27
@AdamColton8 Does this happen like every time or it was only a "one-time" error?

**Comment by AdamColton8** [comment] 2018-11-12 10:29
It was 1 or 2 times

**Comment by crashmajstr** [comment] 2018-11-12 10:31
Ok thanks, we noticed that some of our user ~4 reported this problem as well, but we can't reproduce it on our end. So we'll try to investigate it more on our end. One thing you can try is to delete your ~.avocode folder, maybe it'll help. Otherwise, please use the web app it should work ok. Thank you!

Closing with respect to #2109 #2146

**Closed as completed by crashmajstr** 2018-11-12 10:31 UTC
Labels: linux, hardToReproduce
