### ISSUE TITLE
Can you make Avocode open .ai (Adobe Illustrator) files?

### ISSUE THREAD

**Issue by AlexeyMihaylov** [avocode/avocode#338] opened 2015-07-07 16:43 UTC
Hi,

Sorry for nagging if this question already been asked, but can you make it?

**Comment by rychlis** [comment] 2015-07-08 11:24
Illustrator support is a duplicate of #81 which has been moved to uservoice: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support

You can vote for this feature on uservoice to track any progress

**Closed by rychlis** 2015-07-08 11:24 UTC
