### ISSUE TITLE
Can't seem to add a psd to a new project

### ISSUE THREAD

**Issue by SkoebaSteve** [avocode/avocode#431] opened 2015-09-09 02:39 UTC
IMPORTANT: Please try to describe how did it happen.

I tried to upload a new design through the desktop app and it's stuck at generating preview now. Even the project manager screen is blank now. When reloading the desktop app it says processing failed. It's a pretty simple psd, never had this issue with more complex psd's.
<img width="432" alt="screen shot 2015-09-09 at 12 38 37 pm" src="https://cloud.githubusercontent.com/assets/3404599/9752096/bfe48d00-56ef-11e5-941c-034780a7e11c.png">

-----
App v.2.4.2-d618096
Source UID: 57141
```
Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.
  at invariant (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/invariant.js:42:15)
  at o.Dispatcher.dispatch (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:185:5)
  at o.handleViewAction (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at t.module.exports.t.setDocument (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/active-document.js:1:1668)
  at t._fireNoActiveViewEvents (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:24433)
  at t._fireNoActiveViewEvents (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:999)
  at atom-workspace.<anonymous> (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/avocode.js:1:8427)
  at atom-workspace.handler (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/steefjanssen/Downloads/Avocode.app/Contents/Resources/app.asar/src/command-registry.js:251:29)
  at CommandRegistry.handleCommandEvent
```

**Comment by jankuca** [comment] 2015-09-09 11:32
Thanks for reporting. Duplicate of #421

**Closed by jankuca** 2015-09-09 11:32 UTC
