### ISSUE TITLE
(

### ISSUE THREAD

**Issue by oleg-skliarenko** [avocode/avocode#546] opened 2015-11-30 14:09 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 115787
```
Error: invalid stored block lengths
    at Zlib._handle.onerror (zlib.js:345:17)
```

**Comment by jankuca** [comment] 2015-11-30 20:10
Thank you for the report. We've been investigating this issue for a while. It's a duplicate of #447 which is why I'm going to close this one; we'll let you know when this is resolved there.

**Closed by jankuca** 2015-11-30 20:10 UTC

**Comment by petrbrzek** [comment] 2016-02-05 23:54
This error should be now fixed with the latest Avocode 2.5.3. Please try it and let us know.
