### ISSUE TITLE
Could not download metadata

### ISSUE THREAD

**Issue by reneolivo** [avocode/avocode#1435] opened 2017-05-16 11:43 UTC
I uploaded a PSD file a couple of days ago and I was able to open it at first, but today I was not. Other PSD files seemsto be working fine.

-----
App v. `2.13.6`
Avocode UID: 146890
```
Error: Could not download metadata (revision=10636574)
    at file:///home/reneolivo/Desktop/libs/avocode/resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by vojtatranta** [comment] 2017-05-19 08:12
duplicate of #1442 , please update

**Closed by vojtatranta** 2017-05-19 08:12 UTC
