### ISSUE TITLE
Avocode Sketch sync plugin crashes the app

### ISSUE THREAD

**Issue by dariusb** [avocode/avocode#516] opened 2015-11-05 09:56 UTC
Sketch 3.4.1 (15681)
Sync to Avocode 2.1.4

Hit "Sync to Avocode", then "Sync Updates"
Shows "Exporting metadata" and crashes. Same with "Sync as new design"

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (NSTextTableBlock)'

**Comment by marekhrabe** [comment] 2015-11-05 10:02
Hello, can you please share us the document on team@avocode.com? We cannot reproduce the issue on our own as it seems to be document-specific.

**Comment by dariusb** [comment] 2015-11-05 10:05
Thanks for the quick response, Marek. The document and crash log has been sent to your inbox ;)

**Comment by dariusb** [comment] 2015-11-09 09:20
Guys, any updates?

**Comment by marekhrabe** [comment] 2015-11-13 12:50
I'm working on that right now. I will post updates here as soon as I have something new

**Comment by marekhrabe** [comment] 2015-11-13 17:38
Can you try this pre-release version? https://avocode-media.s3.amazonaws.com/download/sketch-plugin/2.1.5/sketch-plugin-mac-2.1.5.dmg

Although it took some time as the design is really big, I've been successful with syncing it. Let me know

**Comment by rychlis** [comment] 2015-11-16 14:02
We've released 2.1.5 update as stable. I am closing this issue, will re-open in case you still experience same issue with the new version

**Closed by rychlis** 2015-11-16 14:02 UTC
Labels: sketchExtension

**Comment by dariusb** [comment] 2015-11-23 07:23
Thanks, guys. Everything works as it should now.

**Comment by SophiaTS** [comment] 2016-01-28 21:13
Hey Guys, I updated Sketch and have installed the Pre-release Avacode Sketch Plugin but my designs are not syncing. Whenever the modal comes up to choose which art boards to select, it freezes. It's beein doing that all day. Anyone have any advice? 
![screen shot 2016-01-28 at 2 16 08 pm](https://cloud.githubusercontent.com/assets/16945779/12658943/f9ac2d0a-c5d9-11e5-90df-9c24f4f4c035.png)
