### ISSUE TITLE
Error on processing psd

### ISSUE THREAD

**Issue by WebKieth** [avocode/avocode#1426] opened 2017-05-09 04:54 UTC
* **Version**: 2.13.6

* **Web/Desktop**:
Desktop

* **Platform**: 
Ubuntu 16.04 (x64)

Hi everyone. I cant upload new landing page psd design. After uploading on processing step i see a thumb on a design card. Some time after start processing i have an error on a design card "What's wrong? Report us a bug" on red background. 
Proccessing step stops on 30%.
A copy of uploaded psd: https://app.box.com/s/hynt5bnfm6ozqe3yctj04bis61j5qcf0
Screen: https://app.box.com/s/r1p13akk087ip2rb1fb3pfxlrhw5kk3s

**Comment by bolekkerous** [comment] 2017-05-10 15:09
Hey, thanks for the report. 

I've sent a link with the uploaded design to your e-mail.

This problem is caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:09 UTC
Labels: duplicate
