### ISSUE TITLE
Error while exporting.

### ISSUE THREAD

**Issue by squadnik** [avocode/avocode#489] opened 2015-10-26 16:10 UTC
This is how it appears:
http://d.pr/v/22LB

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/squadnik/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment] 2015-10-26 20:45
Duplicate of #472. Thanks for your report though!

**Closed by jankuca** 2015-10-26 20:45 UTC

**Comment by marekhrabe** [comment] 2015-10-26 23:12
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/
