### ISSUE TITLE
Error: Minified exception occurred while deleting a PSD

### ISSUE THREAD

**Issue by Chrisriis** [avocode/avocode#543] opened 2015-11-28 15:39 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.5
Source UID: 9209
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/node_modules/fbjs/lib/invariant.js:35:15)
  at o.dispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/flux/lib/Dispatcher.js:167:160)
  at o.handleViewAction (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/dispatcher.js:1:707)
  at Object.module.exports.deleteGroup (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/actions/project.js:1:1465)
  at [object Object].module.exports.React.createClass._onDeleteClick (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/project-manager/lib/components/document-settings-dropdown.js:1:1020)
  at Object.executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:95:7)
  at Object.executeDispatchesInOrder (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:46:22)
  at forEachAccumulated (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:25:8)
  at Object.EventPluginHub.processEventQueue (/Applications/Avocode.app/Contents/Resources/app
```

**Comment by vojtatranta** [comment] 2015-12-01 09:59
Thank you for your report.
Can you please describe how it happened?

**Comment by jakubzitny** [comment] 2015-12-03 12:41
This is a duplicate of #461. Closing.

**Closed by jakubzitny** 2015-12-03 12:41 UTC
Labels: bug, duplicate, onGitlab
