### ISSUE TITLE
Synching sketch file fails

### ISSUE THREAD

**Issue by chazchumley** [avocode/avocode#524] opened 2015-11-14 20:50 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.4
```
Error: Sketchtool failed to export pages (64A80A7D-BA18-46DD-A95C-BCD05A70DA4E)
    at /Users/cchumley/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/cchumley/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment] 2015-11-16 14:05
This means that Sketch (not our extension) was unable to export the page preview. So far we've been able to reproduce this problem with documents that contained:
- huge canvas background layer used to emulate a different canvas background color 
- huge grid layers used to create a custom grid
- generally any huge layer, huge in this context usually means >10000px in width or height

Removing such layers would make the Sketchtool work.

We are also working on a new major release of Sketch extension for some time. It fixes a lot of bugs and doesn't use Sketchtool anymore so it does not have this problem. We will let you know when the new version is released.

I am closing this issue as it's duplicate of #513. Please follow #513 for more updates

**Closed by rychlis** 2015-11-16 14:05 UTC
