### ISSUE TITLE
design upload gets stuck around 90%+. Tried several times same thing happens. File is pretty big though, around 420mb

### ISSUE THREAD

**Issue by oayoroa** [avocode/avocode#1381] opened 2017-04-11 21:08 UTC
* **Version**: 

* **Web/Desktop**:

* **Platform**:

**Comment by connor-bean** [comment] 2017-04-12 07:28
Hello -

Are you using the plugin to upload the design or directly adding it into Avocode yourself?

**Comment by oayoroa** [comment] 2017-04-12 16:43
Hi, yes I was uploading it directly from the application. I tried using the
web manager and it succesfully uploaded the file. Also the plugin didnt
work as it's for a rather old version of PS. Cheers.

**Comment by bolekkerous** [comment] 2017-05-10 15:12
This problem is caused by huge bitmap images in the design (usually stock images with huge resolutions) or alternatively by huge design resolution or complexity. This should be fixed in the future once we implement our new upload and parsing architecture which we are already working on.

You can either upload the design with our Photoshop plugin, or we can upload it for you if you don't have access to Photoshop. If you want us to upload it for you, just let us know at team@avocode.com or in the in-app chat. Apologies for the inconvenience.

I'll close this issue since it's a duplicate - we're monitoring this issue in #1374

**Closed by bolekkerous** 2017-05-10 15:12 UTC
Labels: duplicate
