### ISSUE TITLE
export button not work

### ISSUE THREAD

**Issue by Catofwanders** [avocode/avocode#2121] opened 2018-08-16 08:09 UTC
Yesterday is ok.  But today export button not work. I reinstall app this don`t help.
I upload psd file.
---
* **Version**: 3.4.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 130765
---
```
No stack trace available
```

**Comment by jakubzitny** [comment] 2018-08-16 09:31
Hi @Catofwanders, thanks for reporting the problem. Does this happen to any layer in any design you uploaded or just a specific layer/design? Can you share the public/private link with us so we can investigate more thoroughly?

Or did the exact same layer work when exporting yesterday, but not today? That would be very weird.

**Comment by Catofwanders** [comment] 2018-08-16 10:06
No matter what layer.  This hapen with all uploaded design. 
https://app.avocode.com/view/c331c813dd8c4c168348821c1eecda98

**Comment by jakubzitny** [comment] 2018-08-16 10:09
Does it happen in web version as well?

**Comment by Catofwanders** [comment] 2018-08-16 10:09
I have an idea, this happen after i update windows10.

**Comment by Catofwanders** [comment] 2018-08-16 10:12
web version work well.

**Comment by jakubzitny** [comment] 2018-08-16 10:14
One more request, can you please try also older version of Avocode? You can download [3.3.2 here](https://media.avocode.com/download/avocode-app/3.3.2/Avocode%20Setup%203.3.2.exe).

**Comment by Catofwanders** [comment] 2018-08-16 10:17
works well.

**Comment by jakubzitny** [comment] 2018-08-16 10:22
Okay, thanks a lot. The `3.4.0` update probably brought some problems. Please use the older one, or web version for now, till we address this.

**Comment by Catofwanders** [comment] 2018-08-20 05:59
How to prevent upload automatic update? It`s give me a lot of problem to my work. Or how fast avocode fix that problem?

**Comment by jakubzitny** [comment] 2018-08-21 10:15
I am sorry to hear that @Catofwanders, we want users to use the latest version of the app as soon as possible in general.

This particular problem is very unique and we have not seen it before. We'll release a new version today, but since we were not able to really reproduce this, it'll probably not help. We'll soon release another version - `3.5.0` with a number of performance and stability. It'll be out at some point next week.

We'd be happy to work with you further to address this problem. Could you please try this beta build we've prepared for you, to see if the export behaviour is better?
https://www.dropbox.com/s/bsuuybi74x1kbqf/Avocode-3.4.0-bootfix-win-signed.zip?dl=0

Also, could you please turn the log level in console (in the build above) to Verbose and send us a video of the whole action (opening export modal and trying to export a layer) so we can investigate whatever happens in the logs in console?

**Comment by Catofwanders** [comment] 2018-08-21 12:05
[-1534853059500.log](https://github.com/avocode/avocode/files/2306173/-1534853059500.log)
video
https://drive.google.com/open?id=11a783r8ifFosUYBgK-Q5Y5mIv7uVztJ6

**Comment by jakubzitny** [comment] 2018-08-21 12:34
Thanks a lot, could you please set `Verbose` in the Console instead of `Info`? I believe this is happening for all PNG, JPG and all other types of export, right?

Before doing the video for Verbose console, could you please try downloading our latest update `3.4.1` and trying if it helps with exporting?

**Comment by Catofwanders** [comment] 2018-08-21 13:08
[-1534856694350.log](https://github.com/avocode/avocode/files/2306353/-1534856694350.log)
video
https://drive.google.com/open?id=1_4CEavx4TuMLFthbnJPCUXqvNMgejTvf

Save work only on svg type export, i show it on video.

**Comment by jakubzitny** [comment] 2018-08-22 13:26
Thanks a lot for the video again, unfortunately, it's not telling us what the exact problem is yet. I have few more tips we can try:

1. Can you please try disabling export optimization in `App Preferences` and try exporting few layers again to see if it helps?

![screenshot 2018-08-22 at 15 23 15](https://user-images.githubusercontent.com/3315662/44466052-a0657200-a61f-11e8-83c4-6e0f37a958f2.png)

2. Can you please change the export path in export modal  to a simpler path (like `C:\Temp`) and make sure it exists?

![screenshot 2018-08-22 at 15 24 33](https://user-images.githubusercontent.com/3315662/44466079-b115e800-a61f-11e8-9e17-d93861901adc.png)


3. Can you please try disabling Monroe rendering engine in App Preferences.


Thanks a lot for help again.

**Comment by jakubzitny** [comment] 2018-08-22 13:39
Actually, we just found out that we have problems with exporting when the Monroe rendering is disabled. Do you have a reason for it to be disabled? Can you try enabling it in App Preferences?

**Comment by Catofwanders** [comment] 2018-08-23 06:02
![image](https://user-images.githubusercontent.com/23452775/44507399-1e268d80-a6b3-11e8-9e20-587c0e4abe70.png)
If i enable Monroe rendering opened file whas label lite, and i can`t export too.

**Comment by jakubzitny** [comment] 2018-08-23 11:16
I see @Catofwanders, that is the main problem we should be addressing actually. We were able to reproduce the export problems when Monroe is disabled. We'll be trying to fix that asap.

In the meantime, we'd really love for all of our users to be able to use Monroe. I prepared another testing build for you, this time with upgraded Chromium core, it should be closer to your web browser where the WebGL engine powering our Monroe rendering works for you. Please try it out, with Monroe enabled and let me know whether exporting works for you: https://we.tl/t-QJvAZEgaRc.

Thanks a lot.

**Comment by Catofwanders** [comment] 2018-08-23 11:47
Thanks. You did good job. All export is work fine.

**Comment by jakubzitny** [comment] 2018-08-23 13:08
Glad to hear that, we'll include the fixes in upcoming releases 🙂

**Comment by Catofwanders** [comment] 2018-08-23 14:16
![image](https://user-images.githubusercontent.com/23452775/44530853-07eef080-a6f8-11e8-9762-7d9043d59240.png)
UPD: some layers don`t save. i use your version  "https://we.tl/t-QJvAZEgaRc.".

**Comment by jakubzitny** [comment] 2018-08-23 14:19
Can you share a public/private link to this design, please @Catofwanders?

**Comment by Catofwanders** [comment] 2018-08-23 15:24
https://app.avocode.com/revisions/29050601?design=18409916

**Comment by jakubzitny** [comment] 2018-09-12 15:18
Hi @Catofwanders, the legacy stage should be fixed in latest release of Avocode. Please update and you should be able to use it and export correctly.

Furthermore, for Avocode `3.6.0` we'll be improving stability and performance even more, so more users should be able to use the latest features from our Monroe engine.

**Closed as completed by jakubzitny** 2018-09-12 15:18 UTC
Labels: bug, electronRelated, willBeFixed

**Comment by Catofwanders** [comment] 2018-09-13 13:48
Hi, export is work fine. But, i have new problem. Layers doesn`t show.  In all my design, i disable/enable Monroe rendering - not show.

**Comment by jakubzitny** [comment] 2018-09-13 13:53
You can "fix" the layers by resizing the layer panel width. It'll fix it forever. We're preparing a fix for next week as well though @Catofwanders.
