### ISSUE TITLE
Error: Sketchtool failed to export pages

### ISSUE THREAD

**Issue by tomrantala** [avocode/avocode#530] opened 2015-11-23 10:40 UTC
IMPORTANT: Please try to describe how did it happen.

Exporting from sketch to avocode with plugin.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.2
```
Error: Sketchtool failed to export pages (BA53E2D5-6CB9-42FF-B691-B876934EC2E0)
    at /Users/tom/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/tom/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by tomrantala** [comment] 2015-11-23 10:45
Also when syncing with the new updated plugin it won't open project manager so I could assign it into project.

**Comment by rychlis** [comment] 2015-12-02 13:34
Hi,

it means that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround. So far we've been able to reproduce this problem with documents that contained:
- huge canvas background layer used to emulate a different canvas background color 
- huge grid layers used to create a custom grid
- generally any huge layer, huge in this context usually means >10000px in width or height

Removing such layers would make the Sketchtool work.

We are also working on a new major release of Sketch extension for some time. It fixes a lot of bugs and doesn't use Sketchtool anymore so it does not have this problem. It also makes it possible to assign document to project inside the extension which should resolve your issue. There is a public beta you can try out, see this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

I am closing this issue as it's a duplicate of https://github.com/avocode/avocode/issues/513

**Closed by rychlis** 2015-12-02 13:34 UTC
Labels: bug
