### ISSUE TITLE
Error while uploading PSD

### ISSUE THREAD

**Issue by yozzh** [avocode/avocode#1355] opened 2017-03-28 13:35 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.1`
Avocode UID: 111514
```
TypeError: toISOString is not a function
    at String.toJSON (<anonymous>)
    at Object.<anonymous> (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/core-js/modules/_ctx.js:18:15)
    at JSON.stringify (<anonymous>)
    at stringify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/json-stringify-safe/stringify.js:5:15)
    at Raven._makeRequest (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1559:22)
    at Raven._sendProcessedPayload (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1485:56)
    at Raven._send (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1442:14)
    at Raven._processException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1290:14)
    at Raven._handleStackInfo (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:1196:14)
    at Raven.captureException (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:350:18)
    at e.captureException (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:15444)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:7:23221
```

**Comment by vojtatranta** [comment] 2017-03-28 13:43
This is a duplicate of #1332

**Closed by vojtatranta** 2017-03-28 13:43 UTC
