### ISSUE TITLE
Sketch Exporter 2.1.5 not working in Sketch 3.4.2

### ISSUE THREAD

**Issue by TheDamianHdez** [avocode/avocode#529] opened 2015-11-19 18:57 UTC
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.2
```
Error: Sketchtool failed to export pages (1494C745-4D9A-4665-9073-D1E8D6F35759)
    at /Users/diseno/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/diseno/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment] 2015-11-19 19:21
Hi it means that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround. So far we've been able to reproduce this problem with documents that contained:
- huge canvas background layer used to emulate a different canvas background color 
- huge grid layers used to create a custom grid
- generally any huge layer, huge in this context usually means >10000px in width or height

Removing such layers would make the Sketchtool work.

We are also working on a new major release of Sketch extension for some time. It fixes a lot of bugs and doesn't use Sketchtool anymore so it does not have this problem. We have just released first beta version of the new extension. See this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

I am closing this issue as it's a duplicate of https://github.com/avocode/avocode/issues/513

**Closed by rychlis** 2015-11-19 19:21 UTC
