### ISSUE TITLE
title bar in macos bad color

### ISSUE THREAD

**Issue by mehdiraized** [avocode/avocode#1069] opened 2016-08-27 08:00 UTC
<img width="1280" alt="screen shot 1395-06-06 at 12 29 18" src="https://cloud.githubusercontent.com/assets/4368004/18026101/09dc1ffe-6c52-11e6-9932-c40cf1cb110e.png">
please fix

**Comment by salexpro** [comment] 2016-08-27 08:49
i think it's not a bug)

**Comment by petrbrzek** [comment] 2016-08-27 10:09
Yeah, that's actually not a bug. I'm closing the issue since the change was intended.

PS: :smile: I've just sent this issue to our product designer and he is a bit sad but he'll get used to it.

**Closed by petrbrzek** 2016-08-27 10:09 UTC
Labels: invalid
