### ISSUE TITLE
Sketch, Sync to Avocode error

### ISSUE THREAD

**Issue by joshhemsley** [avocode/avocode#684] opened 2016-02-02 06:21 UTC
Have been attempting to sync a few sketch files to Avocode using the plugin and continuously receive this error. 

IMPORTANT: Please try to describe how did it happen.
-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-01 22:18:55.692 sketchtool[3781:56212905] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-01 22:18:55.693 sketchtool[3781:56212905] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/jhemsley/InVision/jhemsley@google.com/Pay3.0/Assets/Source%20Files/pay3.0.sketch
((null) MSDocumentDomain:11)


    at /Users/jhemsley/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by vojtatranta** [comment] 2016-02-02 09:10
Thank you for your report.
We are sorry to hear that. But it seems that we have solution for your issue.
The problem is that you are using old Avocode Sketch Extension with newer version of Sketch. You should update it. Here are instructions: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

Let us know whether it worked. Thanks.

**Comment by marekhrabe** [comment] 2016-02-11 10:09
I will close this for now, please let us know if you have further problems.

**Closed by marekhrabe** 2016-02-11 10:09 UTC
Labels: bug, sketchExtension, waitingForUser
