### ISSUE TITLE
Crash after try to upload

### ISSUE THREAD

**Issue by landsman** [avocode/avocode#1431] opened 2017-05-12 09:12 UTC
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.6`
Avocode UID: 78094
```
Invariant Violation: Cannot call hover while not dragging.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/actions/dragDrop.js:107:27)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd/node_modules/dnd-core/lib/DragDropManager.js:92:38)
    at HTML5Backend.handleTopDrop (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:579:20)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by vojtatranta** [comment] 2017-05-12 09:13
You are drag'n'dropping over top bar of avocode, right? 

That's what cause this, just drag'n'drop over right left or bottom edge and everything should be OK.
Or use upload button in the menu / in the Manager

This is konown issue. duplicate of #1249

**Closed by vojtatranta** 2017-05-12 09:13 UTC
