### ISSUE TITLE
Ctr+C Ctr+V on Separaterly export

### ISSUE THREAD

**Issue by sera2007** [avocode/avocode#783] opened 2016-03-05 07:41 UTC
IMPORTANT: Please try to describe how did it happen.

I have chosen 6 images for exporting and I want to create names like - comment1, comment2, ...
After trying to Ctr+C, Ctrl+V comment1 - it was error happened

-----
App v.2.6.0
Source UID: 154159
```
TypeError: menu.sendActionToFirstResponder is not a function
  at HTMLDocument.<anonymous> (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:170:20)
  at HTMLDocument.handler (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:251:29)
  at C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\sergio\AppData\Local\avocode\app-2.6.0\resources\app.asar\src\window-event-handler.js:185:27)

```

**Comment by jankuca** [comment] 2016-03-07 21:10
Hello, thanks for the report. We know about this issue and have a fix ready for the next version. It should be possible to copy & paste the text via right clicking in the meantime.

Duplicate of #404, #781.

**Closed by jankuca** 2016-03-07 21:10 UTC
