### ISSUE TITLE
Can't open big psd file in Avocode

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#70] opened 2014-10-14 12:55 UTC
I couldn't open the psd in Avocode. The sync was fine, but Avocode started a infinite loading with big psd and showed me an alert asking if I want to stop Avocode or waiting.

psd size: 89mb.

**Comment by petrbrzek** [comment] 2015-01-05 15:17
I'm closing this issue because we can't reproduce it. If someone could share problematic PSD, feel free to reopen it.

**Closed by petrbrzek** 2015-01-05 15:17 UTC
Labels: bug
