### ISSUE TITLE
.psd rendering

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#836] opened 2016-04-24 10:18 UTC
Same psd in old avocode (2.6.0) and in new (2.8.0 - beta 2), in was ok in beta 1

old
<img width="677" alt="screen shot 2016-04-24 at 12 15 08" src="https://cloud.githubusercontent.com/assets/12643008/14766778/7129436a-0a16-11e6-9f71-fac21fba4746.png">

new
<img width="762" alt="screen shot 2016-04-24 at 12 15 24" src="https://cloud.githubusercontent.com/assets/12643008/14766779/74406d26-0a16-11e6-9968-5b872fccf4af.png">

Do you want .psd? It is little bit big :)

**Comment by vojtatranta** [comment] 2016-04-25 12:45
Hi,
thank you again so much for your testing and reports.
It would be great if you send us this .psd at team@avocode.com.
Thanks again!

**Comment by jankuca** [comment] 2016-04-25 15:07
We have a fix ready for the next release. The problem is in rendering clipped layers. The layer is being clipped correctly but stretched to the original (unclipped) dimensions which is why it looks distorted.

**Comment by connor-bean** [comment] 2016-06-14 12:20
Hey @janaobzerova -

What OS are you running?

Thanks,
Connor, Avocode Support

**Comment by janaobzerova** [comment] 2016-06-14 12:25
OS X Yosemite

**Comment by connor-bean** [comment] 2016-06-14 14:15
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at manager.avocode.com. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Closed by connor-bean** 2016-06-14 14:15 UTC
Labels: avocodeNext, bug, willBeFixed
