### ISSUE TITLE
don't show styles

### ISSUE THREAD

**Issue by agalar** [avocode/avocode#1791] opened 2017-12-26 19:08 UTC
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 83673
---
```
TypeError: Cannot read property 'toJS' of undefined
    at a (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1385883)
    at Object.s [as convertColor] (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1386024)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:115378
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/nod
```

**Comment by jakubzitny** [comment] 2018-01-02 08:58
Hi @agalar, thanks for reporting this. We're already tracking this problem in #1760, it's caused by some gradients in the design. It will be fixed in Avocode 2.18.0 in upcoming weeks.

**Closed as completed by jakubzitny** 2018-01-02 08:58 UTC
Labels: bug, duplicate
